import {factions} from '../config/factions';
import {actionIds,actionGroups,actionGroup,actionTooltip,actionDescription} from './actionPanel';
import {hotkeys,commandGuide,hotkeyButton} from './hotkeys';
it('every existing action has one group, a distinct guarded hotkey and a complete tooltip/guide',()=>{
 expect(actionGroups).toEqual(['Orders','Build','Train','Research','Spells']);expect(new Set(hotkeys.map(h=>h.key)).size).toBe(hotkeys.length);
 for(const id of actionIds){expect(actionGroups).toContain(actionGroup(id));const h=hotkeys.find(h=>h.button===id)!;expect(h).toBeTruthy();expect(commandGuide).toContain(`${h.key}: ${h.label}`);const tip=actionTooltip(id,{visible:true,cost:'20 wood',reason:'Not enough wood'},'Faction action');expect(tip).not.toContain(h.label);expect(tip).toContain(`[${h.key}]`);expect(actionDescription(id,{visible:true,reason:''},'Faction action')).toContain(h.label);expect(tip).toContain('20 wood');expect(tip).toContain('Not enough wood');expect(hotkeyButton(h.key,{playing:true,repeat:false,focusedTag:'CANVAS'})).toBe(id);}
});
import {expect,it} from 'vitest';import {createMatch} from '../gameplay/match';import {actionPanel} from './actionPanel';import {createNavy} from '../gameplay/navy';import {enqueueProduction} from '../gameplay/productionQueue';
it('shows no actions for empty selection, worker build/stop, and union for mixed selection',()=>{const m=createMatch();expect(Object.values(actionPanel(m,null,true)).some(a=>a.visible)).toBe(false);m.gathering.units[0].selected=true;let a=actionPanel(m,null,true);expect(a['build-farm'].visible).toBe(true);expect(a['stop-units'].visible).toBe(true);expect(a['train-worker'].visible).toBe(false);expect(a['attack-move'].visible).toBe(false);m.gathering.units.push({id:'s-1',kind:'soldier',hp:60,cargo:0,selected:true,position:{x:0,y:0},target:{x:0,y:0},order:{kind:'idle'}});a=actionPanel(m,null,true);expect(a['attack-move'].visible).toBe(true);expect(a['unit-ability'].visible).toBe(true);expect(a['build-farm'].visible).toBe(true);});
it('uses real cost, bank, supply, queue and construction blockers',()=>{const m=createMatch();m.gathering.wood=19;expect(actionPanel(m,'base',true)['train-worker']).toMatchObject({visible:true,cost:'20 wood',reason:'Not enough wood'});m.gathering.wood=100;expect(actionPanel(m,'base',true)['train-worker'].reason).toBe('');for(let i=0;i<3;i++){const r=enqueueProduction(m.gathering,m.production);m.gathering=r.gathering;m.production=r.production;}expect(actionPanel(m,'base',true)['train-worker'].reason).toBe('Queue full');m.production.queue=[];m.production.remainingSeconds=null;m.gathering.units=Array.from({length:8},(_,i)=>({...m.gathering.units[0],id:`u-${i}`}));expect(actionPanel(m,'base',true)['train-worker'].reason).toBe('Population limit reached');m.placement.construction={remainingSeconds:1,builderId:null};expect(actionPanel(m,'barracks',true)['train-soldier'].reason).toBe('Construction unfinished');});
it('build preview blockers show active placement, existing structures, max farms and bank',()=>{const m=createMatch();m.gathering.units[0].selected=true;m.gathering.wood=0;expect(actionPanel(m,null,true)['build-farm'].reason).toBe('Not enough wood');m.placement.active=true;expect(actionPanel(m,null,true)['build-farm'].reason).toBe('Finish or cancel placement');m.placement.active=false;m.placement.barracks={x:0,y:0,width:64,height:64};expect(actionPanel(m,null,true)['build-barracks'].reason).toBe('Not enough wood');});
it('research is accessed through base and explains missing forge, job and completed level',()=>{const m=createMatch();expect(actionPanel(m,null,true)['research-attack'].visible).toBe(false);expect(actionPanel(m,'base',true)['research-attack'].reason).toBe('Complete Forge');m.placement.forge={id:'forge',owner:'player',hp:120,footprint:{x:0,y:0,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};m.gathering.wood=100;m.gathering.goldBalance=100;expect(actionPanel(m,'base',true)['research-attack'].reason).toBe('');m.research!.attack=1;expect(actionPanel(m,'base',true)['research-attack'].reason).toBe('Complete Royal Academy');m.research!.job={kind:'defense',remainingSeconds:3};expect(actionPanel(m,'base',true)['research-defense'].reason).toBe('Research in progress');});
it('explains ability cooldown, transport load and pause without changing state',()=>{const m=createMatch();m.gathering.units=[{id:'s',kind:'soldier',hp:60,cargo:0,selected:true,position:{x:0,y:0},target:{x:0,y:0},order:{kind:'idle'},ability:{activeSeconds:0,cooldownSeconds:2}}];expect(actionPanel(m,null,true)['unit-ability'].reason).toBe('Ability cooling down');m.navy=createNavy();m.navy.ships.push({id:'ship-1',kind:'ship',role:'transport',owner:'player',hp:90,selected:true,passengers:[],position:{x:0,y:0},target:{x:0,y:0},order:{kind:'idle'}});expect(actionPanel(m,null,true)['unload-transport']).toMatchObject({visible:true,reason:'Transport is empty'});const before=structuredClone(m);expect(actionPanel(m,null,false)['stop-units'].reason).toBe('Match is paused or ended');expect(m).toEqual(before);});

it('roster and prerequisite presentation agrees with real admission data',()=>{
 const original=factions.crown;
 factions.crown={...original,units:{...original.units,catapult:{...original.units.catapult,prerequisites:{buildings:['forge'],research:{attack:1}}}}};
 try{
  const m=createMatch();m.gathering.wood=100;m.gathering.goldBalance=100;m.placement.siegeWorks={id:'siegeWorks',owner:'player',hp:180,footprint:{x:640,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null},production:{remainingSeconds:null,nextUnitNumber:4}};
  expect(actionPanel(m,'siegeWorks',true)['train-catapult']).toMatchObject({visible:true,cost:'40 wood + 20 gold',reason:'Complete Forge'});
  m.placement.forge={id:'forge',owner:'player',hp:120,footprint:{x:512,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};
  expect(actionPanel(m,'siegeWorks',true)['train-catapult'].reason).toBe('Research attack 1');m.research!.attack=1;
  expect(actionPanel(m,'siegeWorks',true)['train-catapult'].reason).toBe('');
  factions.crown={...factions.crown,roster:['worker','soldier']};expect(actionPanel(m,'siegeWorks',true)['train-catapult'].visible).toBe(false);
 }finally{factions.crown=original;}
});
it('keeps prerequisites visible after unlocking and identifies active build, research and production',()=>{
 const m=createMatch();m.gathering.wood=1000;m.gathering.goldBalance=1000;m.gathering.units[0].selected=true;m.placement.active=true;m.placement.kind='farm';expect(actionPanel(m,null,true)['build-farm'].active).toBe(true);
 m.placement.active=false;const queued=enqueueProduction(m.gathering,m.production);m.production=queued.production;expect(actionPanel(m,'base',true)['train-worker']).toMatchObject({producing:true,prerequisites:'Completed base'});
 m.placement.forge={id:'forge',owner:'player',hp:120,footprint:{x:512,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};const available=actionPanel(m,'base',true)['research-attack'];expect(available.prerequisites).toContain('Completed forge');m.research!.job={kind:'attack',remainingSeconds:2};expect(actionPanel(m,'base',true)['research-attack'].active).toBe(true);
 expect(actionDescription('research-attack',available,'Attack')).toContain('Requires: Completed forge');expect(actionTooltip('research-attack',available,'Attack')).not.toContain('Requires:');
});

it('keeps hover names and costs once, excluding long ability and spell details',()=>{
 expect(actionTooltip('build-farm',{visible:true,cost:'20 wood',reason:''},'Build Farm – 20 wood [F]')).toBe('Build Farm [F] · 20 wood');
 expect(actionTooltip('cast-heal',{visible:true,cost:'20 mana · Range 200px · Cooldown 10s · Long spell details',reason:'Not enough mana'},'Heal')).toBe('Heal [F2] · 20 mana · Not enough mana');
});
