import {expect,it,vi} from 'vitest';import {bindMinimap} from './minimapView';import {visibleMinimapData} from './minimap';import {createMatch} from '../gameplay/match';
it('minimap owns camera-only left-click navigation, pause gating, context menu and listener cleanup',()=>{const listeners=new Map<string,(event:MouseEvent)=>void>(),context={fillRect:vi.fn(),strokeRect:vi.fn(),save:vi.fn(),restore:vi.fn(),beginPath:vi.fn(),rect:vi.fn(),clip:vi.fn()},canvas={width:200,height:150,clientWidth:200,clientHeight:150,clientLeft:0,clientTop:0,getBoundingClientRect:()=>({left:10,top:20,width:200,height:150}),getContext:()=>context,addEventListener:(name:string,fn:(e:MouseEvent)=>void)=>listeners.set(name,fn),removeEventListener:(name:string)=>listeners.delete(name)} as unknown as HTMLCanvasElement;const m=createMatch('skirmish'),before=structuredClone(m),setScroll=vi.fn();let playing=true;const view=bindMinimap(canvas,()=>({data:visibleMinimapData(m),scroll:{x:0,y:0},viewport:{width:800,height:600}}),setScroll,()=>playing);const event={button:0,clientX:210,clientY:170,stopPropagation:vi.fn(),preventDefault:vi.fn()} as unknown as MouseEvent;listeners.get('click')!(event);expect(setScroll).toHaveBeenLastCalledWith({x:1248,y:1448});expect(m).toEqual(before);setScroll.mockClear();playing=false;listeners.get('click')!(event);playing=true;listeners.get('click')!({...event,button:2} as MouseEvent);expect(setScroll).not.toHaveBeenCalled();listeners.get('contextmenu')!(event);expect(event.preventDefault).toHaveBeenCalledTimes(4);view.destroy();expect(listeners.size).toBe(0);});

it('captures scaled pointer drag, consumes input and gates pause/cancel without mutating gameplay',()=>{
 const listeners=new Map<string,(e:PointerEvent)=>void>(),context={fillRect:vi.fn(),strokeRect:vi.fn(),save:vi.fn(),restore:vi.fn(),beginPath:vi.fn(),rect:vi.fn(),clip:vi.fn()};
 const canvas={width:0,height:0,getBoundingClientRect:()=>({left:10,top:20,width:320,height:320}),getContext:()=>context,setPointerCapture:vi.fn(),hasPointerCapture:()=>true,releasePointerCapture:vi.fn(),addEventListener:(n:string,f:(e:PointerEvent)=>void)=>listeners.set(n,f),removeEventListener:(n:string)=>listeners.delete(n)} as unknown as HTMLCanvasElement;
 const setScroll=vi.fn();let playing=true;
 const view=bindMinimap(canvas,()=>({data:{world:{width:3200,height:1600},terrain:[],scenery:[],markers:[]},scroll:{x:0,y:0},viewport:{width:800,height:600}}),setScroll,()=>playing);
 const event={pointerId:7,button:0,clientX:170,clientY:180,preventDefault:vi.fn(),stopPropagation:vi.fn()} as unknown as PointerEvent;
 listeners.get('pointerdown')!(event);expect(canvas.setPointerCapture).toHaveBeenCalledWith(7);expect(setScroll).toHaveBeenLastCalledWith({x:1200,y:500});
 listeners.get('pointermove')!({...event,clientX:330,clientY:340});expect(setScroll).toHaveBeenLastCalledWith({x:2400,y:1000});
 playing=false;const calls=setScroll.mock.calls.length;listeners.get('pointermove')!(event);expect(setScroll).toHaveBeenCalledTimes(calls);playing=true;
 listeners.get('pointerup')!(event);expect(canvas.releasePointerCapture).toHaveBeenCalledWith(7);listeners.get('click')!(event);expect(setScroll).toHaveBeenCalledTimes(calls);
 listeners.get('pointermove')!(event);expect(setScroll).toHaveBeenCalledTimes(calls);listeners.get('pointerdown')!({...event,button:2});expect(setScroll).toHaveBeenCalledTimes(calls);
 listeners.get('pointerdown')!(event);listeners.get('pointercancel')!(event);const canceled=setScroll.mock.calls.length;listeners.get('pointermove')!(event);expect(setScroll).toHaveBeenCalledTimes(canceled);
 expect(event.stopPropagation).toHaveBeenCalled();expect(event.preventDefault).toHaveBeenCalled();view.destroy();expect(listeners.size).toBe(0);
});
