import {selectedBase} from '../gameplay/extraBases';
import {factionForTeam,type FactionId} from '../config/factions';
import {navyConfig} from '../config/navy';
import {queueConfig} from '../config/production';
import type {BuildingSelection} from '../gameplay/buildingSelection';
import type {MatchState} from '../gameplay/match';
import {artAtlas,motion,unitFrame,type UnitArt} from './animation';
export interface Icon {atlas:'units'|'naval'|'air'|'cavalry'|'healer'|'giant';frame:string}
const icon=(role:UnitArt,faction:FactionId):Icon=>({atlas:artAtlas(role),frame:unitFrame(motion(undefined,{x:0,y:0},'idle',0,role,'player',undefined,faction),0)});
export function selectedIcons(m:MatchState){const faction=factionForTeam(m,'player');return [...m.gathering.units,...(m.navy?.ships??[])].filter(u=>u.selected).map(u=>{const role=u.kind==='ship'?u.role??'warship':u.kind==='worker'?'worker':u.archetype??'soldier',name=role==='transport'||role==='warship'?faction.naval.units[role].name:faction.unitNames[role],max=u.kind==='ship'?faction.naval.units[u.role??'warship'].hp:faction.units[role as 'worker'|'soldier'|'archer'|'catapult'|'specialist'].hp;return {id:u.id,label:`${name} · HP ${Math.ceil(u.hp??max)} / ${max}`,icon:icon(role,faction.id)};});}
export function selectedQueue(m:MatchState,building:BuildingSelection,playing:boolean){const p=selectedBase(m,building)?.production??(building==='academy'?m.placement.academy?.production:building==='stable'?m.placement.stable?.production:building==='barracks'?m.soldierProduction:building==='harbor'?m.navy?.production:undefined),faction=factionForTeam(m,'player');return (p?.queue??[]).map((job,index)=>{const active=index===0,remaining=active?p!.remainingSeconds??job.remainingSeconds:job.remainingSeconds,progress=active?Math.min(1,Math.max(0,1-remaining/job.durationSeconds)):0,name=job.kind==='transport'||job.kind==='warship'?faction.naval.units[job.kind].name:faction.unitNames[job.kind];return {id:job.id,name,active,remaining,progress,refund:active?queueConfig.activeRefund:queueConfig.queuedRefund,disabled:!playing,icon:icon(job.kind,faction.id),status:active?remaining<=0?'Waiting for free exit':`${remaining.toFixed(1)}s remaining`:'Queued'};});}
type Paint=(canvas:HTMLCanvasElement,icon:Icon)=>void;
export function renderSelectedIcons(icons:ReturnType<typeof selectedIcons>,paint:Paint):void {
 const panel=document.getElementById('selection-icons')!;panel.hidden=icons.length<2;const signature=icons.map(i=>i.id).join(',');if(panel.dataset.signature!==signature){panel.dataset.signature=signature;panel.replaceChildren();for(const i of icons){const canvas=document.createElement('canvas');canvas.width=48;canvas.height=48;canvas.dataset.unitId=i.id;panel.append(canvas);}}
 for(const [index,i] of icons.entries()){const canvas=panel.children[index] as HTMLCanvasElement;canvas.title=i.label;canvas.setAttribute('aria-label',i.label);paint(canvas,i.icon);}
}
export function renderSelectedQueue(jobs:ReturnType<typeof selectedQueue>,paint:Paint):void {
 const panel=document.getElementById('production-queue')!,signature=jobs.map(j=>j.id).join(',');if(panel.dataset.signature!==signature){panel.dataset.signature=signature;panel.replaceChildren();if(!jobs.length)panel.textContent='Production queue empty';for(const j of jobs){const button=document.createElement('button');button.type='button';button.dataset.jobId=j.id;const canvas=document.createElement('canvas');canvas.width=32;canvas.height=32;const body=document.createElement('span'),label=document.createElement('span'),progress=document.createElement('progress');label.className='queue-label';progress.max=1;body.append(label,progress);button.append(canvas,body);panel.append(button);}}
 for(const [index,j]of jobs.entries()){const button=panel.children[index] as HTMLButtonElement;button.disabled=j.disabled;button.querySelector('.queue-label')!.textContent=j.active?j.status:'Queued';button.querySelector('progress')!.value=j.progress;button.title=`${j.name} · ${j.status} · Cancel: ${Math.round(j.refund*100)}% refund`;button.setAttribute('aria-label',`${j.name}, ${j.status}. Cancel for ${Math.round(j.refund*100)}% refund`);paint(button.querySelector('canvas')!,j.icon);}
}
