import {createClassicMatch} from './testHelpers/classicMatch';
import {it,expect} from 'vitest';
import {factions,factionIds} from '../config/factions';
import {upgradeMultiplier} from '../config/upgrades';
import {createMatch,updateMatch,type MatchState} from './match';
import {beginPlacement,placeBuilding,placementError,placementObstacles} from './placement';
import {technologyFor,buildingAvailability,techTree} from './productionPrerequisites';
import {startResearch,updateResearch,canResearch,researchRecipe} from './research';
import {updateCombat} from './combat';
import {replaceObstacles,bodyFits} from './map';
import {inspectedBuilding} from './buildingInspection';
import {decodeSave,encodeSave} from './save';
import {missionContent} from '../config/campaignContent';
import {campaignMissions} from '../config/campaign';
import {startCampaignMission} from './campaign';
import {enemyMaximumHP} from './enemyUnits';
import {actionPanel} from '../presentation/actionPanel';
const view={camera:{x:0,y:0},building:null};
function fixture(f:typeof factionIds[number]='crown'){const m=createMatch('skirmish','beginner',{player:f,enemy:'clans'});m.gathering.wood=300;m.gathering.goldBalance=150;m.gathering.units[2].selected=true;m.placement.forge={id:'forge',owner:'player',hp:factions[f].buildings.forge.hp,footprint:{x:288,y:512,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};m.map=replaceObstacles(m.map,[...m.map.obstacles,m.placement.forge.footprint]);m.research={attack:1,defense:1,job:null};return m;}
function build(m:MatchState){const context={gathering:m.gathering,map:m.map,enemies:m.combat.enemies,technology:technologyFor(m,'player')},p=beginPlacement(m.placement,'academy');expect(placementError(p,{x:512,y:384},m.gathering.wood,placementObstacles(m.gathering),context)).toBeNull();const r=placeBuilding(p,{x:512,y:384},m.gathering.wood,placementObstacles(m.gathering),context);expect(r.placement.academy).toBeDefined();return {...m,gathering:r.gathering!,map:r.map!,placement:r.placement};}
function finish(m:MatchState){for(let i=0;i<200&&m.placement.academy!.construction.remainingSeconds>0;i++)m=updateMatch(m,.1);expect(m.placement.academy!.construction.remainingSeconds).toBe(0);return m;}
it.each(factionIds)('%s paid academy admits research II after genuine worker construction',f=>{let m=fixture(f);expect(buildingAvailability(factions[f],'academy',technologyFor(m,'player'))).toBeNull();m.research!.defense=0;expect(buildingAvailability(factions[f],'academy',technologyFor(m,'player'))).toBe('Research defense 1');m.research!.defense=1;m=build(m);expect(m.gathering.wood).toBe(220);expect(m.gathering.goldBalance).toBe(110);expect(canResearch(m.gathering,m.research!,m.placement,'attack')).toBe(false);m=finish(m);const bank=m.gathering.wood,recipe=researchRecipe(factions[f],'attack',1),r=startResearch(m.gathering,m.research!,m.placement,'attack');expect(r.gathering.wood).toBe(bank-recipe.cost.wood);expect(r.research.job?.remainingSeconds).toBe(12);expect(startResearch(r.gathering,r.research,m.placement,'attack').research).toBe(r.research);expect(updateResearch(r.research,m.placement,11.99,true,f).attack).toBe(1);const done=updateResearch(r.research,m.placement,12,true,f);expect(done.attack).toBe(2);expect(canResearch(r.gathering,done,m.placement,'attack')).toBe(false);expect(inspectedBuilding(m,'academy')?.maxHP).toBe(140);expect(techTree(m).join('\n')).toContain('I: forge; II: forge +');});
it.each(factionIds)('%s level-II buffs actual melee damage and armor while worker damage stays weak',f=>{const m=fixture(f),p={x:300,y:300};m.gathering.units=[{id:'unit-4',kind:'soldier',owner:'player',hp:factions[f].units.soldier.hp,cargo:0,selected:false,position:p,target:p,order:{kind:'attack',enemyId:'enemy-1'}}];m.combat.enemies=[{id:'enemy-1',hp:100,position:{x:330,y:300}}];const plain=updateCombat(m.gathering,m.combat,1),upgraded=updateCombat(m.gathering,{...m.combat,upgrades:{attack:2,defense:2}},1);expect(100-upgraded.combat.enemies[0].hp).toBeCloseTo((100-plain.combat.enemies[0].hp)*Math.pow(factions[f].upgrades.attack.multiplier,2));expect(factions[f].units.soldier.hp-upgraded.gathering.units[0].hp!).toBeCloseTo((factions[f].units.soldier.hp-plain.gathering.units[0].hp!)*Math.pow(factions[f].upgrades.defense.multiplier,2));const worker={...m.gathering.units[0],kind:'worker' as const,hp:30,order:{kind:'attack' as const,enemyId:'enemy-1'}};const w=updateCombat({...m.gathering,units:[worker]},m.combat,1),wu=updateCombat({...m.gathering,units:[worker]},{...m.combat,upgrades:{attack:2,defense:2}},1);expect(wu.combat.enemies[0].hp).toBe(w.combat.enemies[0].hp);});
it('academy death cancels only its active advanced research and preserves completed technology',()=>{let m=finish(build(fixture()));const r=startResearch(m.gathering,m.research!,m.placement,'attack');m={...m,gathering:r.gathering,research:r.research};const bank=m.gathering.wood,rect=m.placement.academy!.footprint;m.placement.academy!.hp=0;m=updateMatch(m,0);expect(m.research).toEqual({attack:1,defense:1,job:null});expect(m.gathering.wood).toBe(bank);expect(m.placement.academy).toBeUndefined();expect(inspectedBuilding(m,'academy')).toBeNull();expect(m.map.obstacles).not.toContainEqual(rect);expect(bodyFits(m.map,{x:544,y:416},8)).toBe(true);});
it('Save62 restores construction and advanced jobs, rejects relabelled extras and migrates genuine61',()=>{let m=build(fixture());let loaded=decodeSave(encodeSave(m,view));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);m=finish(m);const r=startResearch(m.gathering,m.research!,m.placement,'defense');m={...m,gathering:r.gathering,research:r.research};m=updateMatch(m,2);const json=encodeSave(m,view);loaded=decodeSave(json);expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(loaded.ok)expect(loaded.match.research).toEqual(m.research);const old=JSON.parse(json);old.configVersion='tribute-config-61';expect(decodeSave(JSON.stringify(old)).ok).toBe(false);const genuine=JSON.parse(encodeSave(createClassicMatch(),view));genuine.configVersion='tribute-config-61';expect(decodeSave(JSON.stringify(genuine)).ok).toBe(true);m=updateMatch(m,10);expect(m.research!.defense).toBe(2);expect(decodeSave(encodeSave(m,view)).ok).toBe(true);});
it('all early campaign missions remain without academy admission, later six/eight introduce it',()=>{for(let i=0;i<campaignMissions.length;i++)expect(missionContent(campaignMissions[i].id).buildings.includes('academy')).toBe(i>=5);expect(upgradeMultiplier(1.25,2)).toBe(1.5625);expect(upgradeMultiplier(.75,2)).toBe(.5625);});
it('the academy action explains prerequisites/costs, construction and max levels',()=>{const m=fixture();expect(actionPanel(m,null,true)['build-academy']).toMatchObject({visible:true,cost:'80 wood + 40 gold',reason:''});m.research!.defense=0;expect(actionPanel(m,null,true)['build-academy'].reason).toBe('Research defense 1');m.research!.defense=1;m.placement.academy={id:'academy',owner:'player',hp:140,footprint:{x:512,y:384,width:64,height:64},construction:{remainingSeconds:1,builderId:null}};expect(actionPanel(m,'academy',true)['research-attack'].reason).toBe('Complete Royal Academy');m.placement.academy.construction.remainingSeconds=0;expect(actionPanel(m,'academy',true)['research-attack'].cost).toBe('80 wood + 20 gold');m.research!.attack=2;expect(actionPanel(m,'academy',true)['research-attack'].reason).toBe('Already researched');});

it.each(factionIds)('%s enemy academy exposes its actual configured HP',f=>{expect(enemyMaximumHP({id:'enemy-academy',kind:'building',buildingType:'academy',hp:140,position:{x:512,y:384}},f)).toBe(140);});

it('legacy story identities also lock advanced construction and saves in early missions',()=>{const m=fixture();m.campaignMission='the-siege';expect(buildingAvailability(factions.crown,'academy',technologyFor(m,'player'))).toBe('Locked for this campaign mission');expect(actionPanel(m,null,true)['build-academy'].reason).toBe('Locked for this campaign mission');m.placement.academy={id:'academy',owner:'player',hp:140,footprint:{x:512,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};const valid=startCampaignMission({version:1,completed:campaignMissions.slice(0,2).map(x=>x.id)},'the-siege','normal',{player:'crown',enemy:'clans'})!;valid.placement.academy=m.placement.academy;expect(()=>encodeSave(valid,view)).toThrow(/campaign academy/);});
