import {cleanDestroyed} from './destruction';
import {issueOrder} from './commandOrders';
import {expect,it} from 'vitest';
import {createMatch,updateMatch} from './match';
import {createNavy,matchPopulation,stopShips,commandShips} from './navy';
import {cancelSelectedTransfers,requestTransport,updateTransportTransfers} from './autoTransport';
import {bodyFits} from './map';
import {encodeSave,decodeSave} from './save';
import {matchFog} from './matchFog';
const view={camera:{x:0,y:0},building:null};
function fixture(){const m=createMatch('skirmish','beginner',undefined,'islands');m.navy={...createNavy(),production:{remainingSeconds:null,nextUnitNumber:2,nextJobNumber:2},ships:[{id:'ship-1',kind:'ship',role:'transport',owner:'player',hp:90,selected:true,passengers:[],position:{x:816,y:432},target:{x:816,y:432},order:{kind:'idle'}}]};m.gathering.node.remaining-=40;m.gathering.gold!.remaining-=10;m.gathering.units.forEach((u,i)=>{u.selected=i<2;u.position={x:640,y:432+i*32};u.target={...u.position};u.order={kind:'idle'};});m.fog=matchFog(m);return m;}
it('boat and two distant workers meet at visible coast and board through ordinary movement',()=>{let m=fixture(),before=matchPopulation(m);m=requestTransport(m,'ship-1','load');expect(m.navy!.ships[0].transfer?.kind).toBe('load');expect(m.gathering.units.filter(u=>u.order.kind==='move')).toHaveLength(2);for(let i=0;i<200&&m.navy!.ships[0].transfer;i++)m=updateMatch(m,.1);expect(m.navy!.ships[0].passengers).toHaveLength(2);expect(m.gathering.units).toHaveLength(1);expect(matchPopulation(m)).toEqual(before);expect(m.navy!.ships[0].selected).toBe(true);});
it('Unload moves to the nearest valid visible coast and lands without a precise click',()=>{let m=fixture();const passengers=m.gathering.units.splice(0,2).map(u=>({...u,selected:false,order:{kind:'idle' as const}}));m.navy!.ships[0].passengers=passengers;const pop=matchPopulation(m);m=requestTransport(m,'ship-1','unload');expect(m.navy!.ships[0].transfer?.kind).toBe('unload');for(let i=0;i<200&&m.navy!.ships[0].transfer;i++)m=updateMatch(m,.1);expect(m.navy!.ships[0].passengers).toHaveLength(0);expect(m.gathering.units).toHaveLength(3);for(const u of m.gathering.units)expect(bodyFits(m.map,u.position,8)).toBe(true);expect(matchPopulation(m)).toEqual(pop);});
it('hidden/far shores and a full ship produce no transfer; pause blocks requests',()=>{const m=fixture();m.fog!.teams.player.visible.fill(false);expect(requestTransport(m,'ship-1','load')).toBe(m);m.fog=matchFog(m);m.navy!.ships[0].position={x:2400,y:1040};m.navy!.ships[0].target={...m.navy!.ships[0].position};expect(requestTransport(m,'ship-1','load')).toBe(m);expect(requestTransport({...m,paused:true},'ship-1','unload').navy!.ships[0].transfer).toBeUndefined();});
it('pending movement survives Save/load; Stop or a replacement destination cancels it',()=>{let m=requestTransport(fixture(),'ship-1','load');const saved=decodeSave(encodeSave(m,view));expect(saved.ok,saved.ok?'':saved.error).toBe(true);if(!saved.ok)throw Error(saved.error);expect(saved.match.navy!.ships[0].transfer).toEqual(m.navy!.ships[0].transfer);for(let i=0;i<200&&saved.match.navy!.ships[0].transfer;i++)saved.match=updateMatch(saved.match,.1);expect(saved.match.navy!.ships[0].passengers).toHaveLength(2);m.navy=stopShips(m.navy);expect(m.navy!.ships[0].transfer).toBeUndefined();m=requestTransport(fixture(),'ship-1','load');m.navy=commandShips(m,{x:784,y:528});expect(m.navy!.ships[0].transfer).toBeUndefined();});
it('replacement ground commands and expired work cancel without teleporting or boarding',()=>{let m=requestTransport(fixture(),'ship-1','load');m.gathering.units[0].target={x:200,y:300};m=updateTransportTransfers(m,.1);expect(m.navy!.ships[0].transfer).toBeUndefined();expect(m.navy!.ships[0].passengers).toHaveLength(0);m=requestTransport(fixture(),'ship-1','load');m=updateTransportTransfers(m,31);expect(m.navy!.ships[0].transfer).toBeUndefined();});
it('strict saves reject forged boarding refs and preserve genuine config57 geometry',()=>{const m=requestTransport(fixture(),'ship-1','load'),raw=JSON.parse(encodeSave(m,view));raw.state.navy.ships[0].transfer.unitIds=['unit-999'];expect(decodeSave(JSON.stringify(raw)).ok).toBe(false);const old=JSON.parse(encodeSave(fixture(),view));old.configVersion='tribute-config-57';delete old.state.discoveries;expect(decodeSave(JSON.stringify(old)).ok).toBe(true);raw.configVersion='tribute-config-57';expect(decodeSave(JSON.stringify(raw)).ok).toBe(false);});

it('Hold cancels boarding even after troops have reached the exact meeting point',()=>{let m=requestTransport(fixture(),'ship-1','load');const job=m.navy!.ships[0].transfer!;m.navy!.ships[0].selected=false;for(const u of m.gathering.units.filter(u=>job.unitIds.includes(u.id))){u.position={...job.goals[u.id]};u.target={...u.position};u.order={kind:'idle'};}m=issueOrder(m,{kind:'hold'});expect(m.navy!.ships[0].transfer).toBeUndefined();expect(m.navy!.ships[0].passengers).toHaveLength(0);});

it('Stop selection and participant death clear jobs before a possible immediate Save',()=>{let m=requestTransport(fixture(),'ship-1','load');m.navy!.ships[0].selected=false;m=cancelSelectedTransfers(m);expect(m.navy!.ships[0].transfer).toBeUndefined();m=requestTransport(fixture(),'ship-1','load');m.gathering.units[0].hp=0;m=cleanDestroyed(m);expect(m.navy!.ships[0].transfer).toBeUndefined();expect(decodeSave(encodeSave(m,view)).ok).toBe(true);});
