import {expect,it} from 'vitest';
import {factions,factionIds,type FactionId,type UnitRole} from '../config/factions';
import {createMatch} from './match';
import {updateCombat} from './combat';
import {canAttackDomain} from './domains';
import {castSpell,advanceSpells,spellTargetReason} from './spells';
import {advanceMana} from './mana';
import {spellForSlot} from '../config/spells';
import {matchFog} from './matchFog';
import {nextEnemyRole,updateEnemyProduction} from './enemyProduction';
import type {Soldier} from './gathering';
import type {NavyState} from './navy';
import type {Enemy} from './combat';
type Role=Exclude<UnitRole,'worker'>;
const reports:unknown[]=[];
const cost=(f:FactionId,roles:Role[])=>roles.reduce((r,role)=>({wood:r.wood+factions[f].units[role].cost.wood,gold:r.gold+factions[f].units[role].cost.gold}),{wood:0,gold:0});
const total=(f:FactionId,role:Role)=>{const c=factions[f].units[role].cost;return c.wood+c.gold;};
const equal=(f:FactionId,role:Role,budget:number)=>Array.from({length:Math.max(1,Math.round(budget/total(f,role)))},()=>role);
/** Explicit open-field fixture. Real profiles/projectiles/casts; no human micro, economy or global fog claim. */
function battle(p:FactionId,own:Role[],e:FactionId,hostile:Role[],gap=120,magic=false){
 let m=createMatch('skirmish','normal',{player:p,enemy:e});
 m.gathering.units=own.map((role,i):Soldier=>{const r=factions[p].units[role],position={x:400,y:280+i*48};return {id:`unit-${i+1}`,kind:'soldier',...(role==='soldier'?{}:{archetype:role}),faction:p,owner:'player',hp:r.hp,cargo:0,selected:false,position,target:position,order:{kind:'idle'},...(r.mana?{mana:r.mana.initial}:{})};});
 m.combat={baseHP:0,upgrades:{attack:1,defense:1},enemyUpgrades:{attack:1,defense:1},enemies:hostile.map((role,i):Enemy=>{const r=factions[e].units[role];return {id:`enemy-produced-${i+1}`,kind:'unit',owner:'enemy',role,hp:r.hp,position:{x:400+gap,y:280+i*48},order:{kind:'idle'},...(r.mana?{mana:r.mana.initial}:{})};})};
 let time=0,casts=0;for(let frame=0;frame<900&&m.gathering.units.length&&m.combat.enemies.length;frame++){
  m=advanceMana(advanceSpells(m,.1),.1);m.fog=matchFog(m);
  if(magic&&frame%5===0)for(const team of ['player','enemy'] as const){const f=team==='player'?p:e,candidates=team==='player'?m.gathering.units.filter(u=>u.kind==='soldier'&&u.archetype==='specialist'):m.combat.enemies.filter(u=>u.role==='specialist');for(const caster of candidates){let done=false;for(const slot of ['heal','hex','ward'] as const){const id=spellForSlot(f,slot);if(!id)continue;for(const target of [...m.gathering.units,...m.combat.enemies])if(!spellTargetReason(m,caster.id,id,target.id,team)){const r=castSpell(m,caster.id,id,target.id,team);if(r.match!==m){m=r.match;casts++;done=true;break;}}if(done)break;}}}
  m.gathering.units=m.gathering.units.map(u=>{if(u.kind!=='soldier')return u;const targets=m.combat.enemies.filter(t=>canAttackDomain(u,t,p)).sort((a,b)=>Math.hypot(a.position.x-u.position.x,a.position.y-u.position.y)-Math.hypot(b.position.x-u.position.x,b.position.y-u.position.y));return {...u,order:targets.length?{kind:'attack',enemyId:targets[0].id}:{kind:'idle'}};});
  m.combat.enemies=m.combat.enemies.map(u=>{const targets=m.gathering.units.filter(t=>canAttackDomain(u,t,e)).sort((a,b)=>Math.hypot(a.position.x-u.position.x,a.position.y-u.position.y)-Math.hypot(b.position.x-u.position.x,b.position.y-u.position.y));return {...u,order:targets.length?{kind:'defend',targetId:targets[0].id}:{kind:'idle'}};});
  const r=updateCombat(m.gathering,m.combat,.1,undefined,undefined,()=>true,()=>true,()=>true,undefined,undefined,()=>true,e);m={...m,...r,gathering:{...r.gathering,units:r.gathering.units.filter(u=>u.hp!>0)},combat:{...r.combat,enemies:r.combat.enemies.filter(u=>u.hp>0)}};time+=.1;
 }
 const result={player:p,enemy:e,own,hostile,gap,magic,ownCost:cost(p,own),enemyCost:cost(e,hostile),ownSurvivors:m.gathering.units.length,enemySurvivors:m.combat.enemies.length,ownHP:m.gathering.units.reduce((n,u)=>n+u.hp!,0),enemyHP:m.combat.enemies.reduce((n,u)=>n+u.hp,0),seconds:Math.round(time*10)/10,casts};return result;
}
it.each(factionIds)('%s early ground AA counters similarly priced aircraft and still has a ground counter',f=>{
 const budget=total(f,'air')*2,aa=equal(f,'archer',budget),air=battle(f,aa,f,['air','air']),close=battle(f,equal(f,'soldier',cost(f,aa).wood+cost(f,aa).gold),f,aa,32),siege=battle(f,aa,f,equal(f,'catapult',budget));reports.push({case:'groundAA-v-air',...air},{case:'melee-v-AA-close',...close},{case:'AA-v-siege',...siege});expect(air.enemySurvivors).toBe(0);expect(air.ownSurvivors).toBeGreaterThan(0);expect(close.enemySurvivors).toBe(0);expect(close.ownSurvivors).toBeGreaterThan(0);
});
it('bombers need escort; cost-equivalent air interceptors cannot be attacked by unescorted bombers',()=>{
 const solo=battle('goblins',['air','air'],'elves',equal('elves','air',240)),escorted=battle('goblins',['air','archer','archer','archer','archer'],'elves',equal('elves','air',224)),land=battle('goblins',['air','air'],'dwarves',equal('dwarves','soldier',240));reports.push({case:'bomber-v-interceptor',...solo},{case:'bomber-with-ground-AA-escort',...escorted},{case:'bomber-v-melee',...land});expect(solo.ownSurvivors).toBe(0);expect(solo.enemyHP).toBe(180);expect(escorted.enemySurvivors).toBe(0);expect(land.enemySurvivors).toBe(0);
});
it.each(factionIds)('%s combined land/magic retains paid mana decisions against equivalent ground groups',f=>{const roster:Role[]=['specialist','soldier','archer'],budget=cost(f,roster).wood+cost(f,roster).gold,normal=battle(f,roster,f,equal(f,'soldier',budget),64),magic=battle(f,roster,f,equal(f,'soldier',budget),64,true);reports.push({case:'mixed-no-spells',...normal},{case:'mixed-with-spells',...magic});expect(magic.casts).toBeGreaterThan(0);expect(Number.isFinite(magic.ownHP)).toBe(true);});
it.each(factionIds)('%s AI pays for air and counters observed air with early archers',f=>{
 const m=createMatch('skirmish','normal',{player:f,enemy:f}),tech={buildings:['base','barracks','forge'] as const,research:{attack:1,defense:1}},base=m.combat.enemies.find(e=>e.kind==='base')!,site:Enemy={id:'enemy-barracks',kind:'building',buildingType:'barracks',owner:'enemy',hp:120,position:{x:800,y:400},footprint:{x:768,y:368,width:64,height:64},construction:{remainingSeconds:0,builderId:null}},state={...m.enemyProduction!,acceptedJobs:4,wood:500,gold:200,cap:20};expect(nextEnemyRole(state,f,tech)).toBe('air');const air=updateEnemyProduction(state,{...m.combat,enemies:[base,site]},m.gathering,m.map,30,f,{site,technology:tech,population:{cap:20,used:0,reserved:0}});expect(air.combat.enemies.some(u=>u.role==='air')).toBe(true);expect(air.state.wood).toBeLessThan(500);const counter=updateEnemyProduction(state,{...m.combat,enemies:[base,site]},m.gathering,m.map,0,f,{site,technology:tech,population:{cap:20,used:0,reserved:0},airThreat:true});expect(counter.state.production.queue!.slice(0,2).map(j=>j.kind)).toEqual(['archer','archer']);reports.push({case:'AI-paid-air-and-counter',faction:f,queue:counter.state.production.queue,produced:air.combat.enemies.filter(e=>e.role==='air').length});
});
it.each(factionIds)('%s sea/air: warships retaliate with weaker anti-air without changing land damage',f=>{const m=createMatch('skirmish','normal',{player:f,enemy:'crown'}),r=factions[f].naval.units.warship;m.gathering.units=[];m.combat={baseHP:0,enemies:[{id:'enemy-produced-1',kind:'unit',owner:'enemy',role:'air',hp:130,position:{x:500,y:300},order:{kind:'defend',targetId:'ship-1'}}]};let navy:NavyState={harbor:null,production:{remainingSeconds:null,nextUnitNumber:2},ships:[{id:'ship-1',kind:'ship' as const,owner:'player' as const,hp:r.hp,selected:true,position:{x:400,y:300},target:{x:400,y:300},order:{kind:'attack' as const,enemyId:'enemy-produced-1'}}]};for(let i=0;i<80;i++){const v=updateCombat(m.gathering,m.combat,.1,undefined,undefined,()=>true,()=>true,()=>true,undefined,navy,()=>true,'crown');m.combat=v.combat;navy=v.navy!;}reports.push({case:'sea-v-air-after',faction:f,ownCost:r.cost,shipHP:navy.ships[0]?.hp??0,airHP:m.combat.enemies[0]?.hp??0});expect(m.combat.enemies[0]?.hp??0).toBeLessThan(130);});
for(const defender of factionIds)for(const attacker of factionIds)it(`${defender} ground AA is a practical counter to ${attacker} air at comparable resource cost`,()=>{const r=battle(defender,equal(defender,'archer',2*total(attacker,'air')),attacker,['air','air']);reports.push({case:'cross-race-ground-AA',...r});expect(r.enemySurvivors).toBe(0);expect(r.ownSurvivors).toBeGreaterThan(0);});
for(const defender of ['crown','clans','elves','dwarves'] as const)for(const attacker of ['crown','clans','elves','dwarves'] as const)it(`${defender}/${attacker} air roles retain distinct cost-comparable outcomes`,()=>{const r=battle(defender,equal(defender,'air',400),attacker,equal(attacker,'air',400));reports.push({case:'air-v-air',...r});expect(r.ownSurvivors===0||r.enemySurvivors===0).toBe(true);if(defender==='elves'&&attacker==='clans'||defender==='dwarves'&&attacker==='elves'){expect(r.enemySurvivors).toBe(0);expect(r.ownSurvivors).toBeGreaterThan(0);}});
for(const defender of factionIds)for(const attacker of ['crown','clans'] as const)it(`${defender} navy counters ${attacker} air with comparable groups in actual water`,()=>{
 const m=createMatch('skirmish','normal',{player:defender,enemy:attacker},'islands'),r=factions[defender].naval.units.warship,air=factions[attacker].units.air,count=Math.round(2*total(attacker,'air')/(r.cost.wood+r.cost.gold));m.gathering.units=[];m.combat={baseHP:0,enemies:[0,1].map(i=>({id:`enemy-produced-${i+1}`,kind:'unit',owner:'enemy',role:'air',hp:air.hp,position:{x:840,y:350+i*48},order:{kind:'idle'}}))};let navy:NavyState={harbor:null,production:{remainingSeconds:null,nextUnitNumber:count+1},ships:Array.from({length:count},(_,i)=>({id:`ship-${i+1}`,kind:'ship',owner:'player',hp:r.hp,selected:false,position:{x:750,y:350+i*48},target:{x:750,y:350+i*48},order:{kind:'attack',enemyId:'enemy-produced-1'}}))};let time=0;for(let i=0;i<900&&navy.ships.length&&m.combat.enemies.length;i++){navy.ships=navy.ships.map(s=>({...s,order:{kind:'attack',enemyId:m.combat.enemies.slice().sort((a,b)=>Math.hypot(a.position.x-s.position.x,a.position.y-s.position.y)-Math.hypot(b.position.x-s.position.x,b.position.y-s.position.y))[0].id}}));const v=updateCombat(m.gathering,m.combat,.1,m.map,undefined,()=>true,()=>true,()=>true,undefined,navy,()=>true,attacker);m.combat={...v.combat,enemies:v.combat.enemies.filter(e=>e.hp>0)};navy={...v.navy!,ships:v.navy!.ships.filter(s=>s.hp>0)};time+=.1;}reports.push({case:'cost-matched-sea-AA',defender,attacker,count,ownCost:{wood:r.cost.wood*count,gold:r.cost.gold*count},enemyCost:{wood:air.cost.wood*2,gold:air.cost.gold*2},shipSurvivors:navy.ships.length,airSurvivors:m.combat.enemies.length,seconds:Math.round(time*10)/10});expect(m.combat.enemies).toHaveLength(0);expect(navy.ships.length).toBeGreaterThan(0);
});
it('exports reproducible scenario results',()=>{for(const row of reports)console.info('W2T_BALANCE_ROW='+JSON.stringify(row));expect(reports.length).toBe(89);});
