import {it,expect} from 'vitest';
import {createMatch,updateMatch,type MatchState} from './match';
import {beginPlacement,placeBuilding,placementObstacles,placementError} from './placement';
import {trainBaseWorker,hasMainBase,syncDropoffs} from './extraBases';
import {matchPopulation} from './navy';
import {factions} from '../config/factions';
import {decodeSave,encodeSave} from './save';
import {cancelProduction} from './productionQueue';
import {visionObservers} from './matchFog';
import {playerTargets} from './targets';
import {inspectedBuilding} from './buildingInspection';
import {replaceObstacles} from './map';
import {orderRepair} from './repair';
function fixture(){const m=createMatch('skirmish');m.gathering.wood=300;m.gathering.goldBalance=160;m.gathering.units[2].selected=true;return m;}
function build(m:MatchState,point={x:512,y:384}){const p=beginPlacement(m.placement,'base'),context={map:m.map,gathering:m.gathering,enemies:m.combat.enemies};expect(placementError(p,point,m.gathering.wood,placementObstacles(m.gathering),context)).toBeNull();const r=placeBuilding(p,point,m.gathering.wood,placementObstacles(m.gathering),context);expect(r.placement.bases?.length).toBe((m.placement.bases?.length??0)+1);return {...m,placement:r.placement,gathering:r.gathering!,map:r.map!};}
function finish(m:MatchState){for(let i=0;i<240&&m.placement.bases!.some(b=>b.construction.remainingSeconds>0);i++)m=updateMatch(m,.1);expect(m.placement.bases![0].construction.remainingSeconds).toBe(0);return m;}
const view={camera:{x:0,y:0},building:null};
it('paid worker construction creates a blocking foundation before supply/vision/production',()=>{let m=build(fixture());expect(m.gathering.wood).toBe(200);expect(m.gathering.goldBalance).toBe(100);expect(m.placement.bases![0]).toMatchObject({id:'base-1',owner:'player',construction:{remainingSeconds:12,builderId:'unit-3'}});expect(matchPopulation(m).cap).toBe(8);expect(trainBaseWorker(m,'base-1')).toBe(m);expect(visionObservers(m).some(o=>o.id==='base-1')).toBe(false);expect(playerTargets(m.gathering,m.combat,m.placement).some(t=>t.id==='base-1')).toBe(true);expect(inspectedBuilding(m,'base-1')?.remaining).toBe(12);m=finish(m);expect(matchPopulation(m).cap).toBe(16);expect(visionObservers(m).some(o=>o.id==='base-1')).toBe(true);});
it('separate queues reserve common supply, spawn locally and advance one shared unit sequence',()=>{let m=finish(build(fixture()));m=trainBaseWorker(trainBaseWorker(m,'base'),'base-1');expect(m.production.queue).toHaveLength(1);expect(m.placement.bases![0].production.queue).toHaveLength(1);expect(matchPopulation(m).reserved).toBe(2);m=updateMatch(m,5);expect(m.gathering.units.map(u=>u.id)).toEqual(['unit-1','unit-2','unit-3','unit-4','unit-5']);expect(m.production.nextUnitNumber).toBe(6);expect(m.placement.bases![0].production.nextUnitNumber).toBe(6);expect(m.gathering.units[4].position.x).toBeGreaterThan(480);m=trainBaseWorker(m,'base-1');const p=m.placement.bases![0].production,bank=m.gathering.wood,r=cancelProduction(m.gathering,p,p.queue![0].id);expect(r.production.queue).toHaveLength(0);expect(r.gathering.wood).toBeGreaterThan(bank);});
it('completed expansion receives cargo after the original base dies and defeats only on last completed base',()=>{let m=finish(build(fixture()));m.combat.baseHP=0;m.gathering.units[0]={...m.gathering.units[0],kind:'worker',position:{x:500,y:416},target:{x:500,y:416},cargo:4,order:{kind:'deliver',nodeId:m.gathering.node.id}};const bank=m.gathering.wood;m=updateMatch(m,.1);expect(m.outcome).toBe('playing');expect(hasMainBase(m)).toBe(true);expect(m.gathering.wood).toBe(bank+4);expect(m.gathering.units[0].cargo).toBe(0);expect(matchPopulation(m).cap).toBe(8);m=trainBaseWorker(m,'base-1');m=updateMatch(m,5);expect(m.gathering.units).toHaveLength(4);const rect=m.placement.bases![0].footprint;m.placement.bases![0].hp=0;m=updateMatch(m,0);expect(m.outcome).toBe('defeat');expect(m.placement.bases).toHaveLength(0);expect(m.map.obstacles).not.toContainEqual(rect);});
it('foundations do not prevent defeat and campaign still protects original base',()=>{let m=build(fixture());m.combat.baseHP=0;expect(updateMatch(m,0).outcome).toBe('defeat');m=finish(build(fixture()));m.campaignMission='forest-watch';m.combat.baseHP=0;expect(updateMatch(m,0).outcome).toBe('defeat');});
it('Save61 validates construction, queues/counters and excludes extras from genuine older documents',()=>{let m=build(fixture());let json=encodeSave(m,view);let loaded=decodeSave(json);expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(!loaded.ok)return;expect(loaded.match.placement.bases).toEqual(m.placement.bases);m=finish(m);m=trainBaseWorker(m,'base-1');m=updateMatch(m,1);m.combat.baseHP=0;m=updateMatch(m,0);json=encodeSave(m,view);loaded=decodeSave(json);expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);const doc=JSON.parse(json);doc.state.placement.bases[0].production.nextUnitNumber=1;expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);doc.state.placement.bases[0].production.nextUnitNumber=4;doc.configVersion='tribute-config-60';expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);const old=JSON.parse(encodeSave(createMatch(),view));old.configVersion='tribute-config-60';expect(decodeSave(JSON.stringify(old)).ok).toBe(true);});
it('damaged expansions are repairable and independent bases add supply for every faction',()=>{for(const f of Object.keys(factions) as (keyof typeof factions)[]){const m=fixture();m.factions!.player=f;m.gathering.faction=f;m.placement.bases=[{id:'base-1',owner:'player',hp:factions[f].buildings.base.hp-10,footprint:{x:512,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null},production:{remainingSeconds:null,nextUnitNumber:4}}];m.map=replaceObstacles(m.map,[...m.map.obstacles,m.placement.bases[0].footprint]);expect(matchPopulation(m).cap).toBe(factions[f].buildings.base.populationCapacity*2);expect(orderRepair(m,'base-1').gathering.units[2].order).toEqual({kind:'repair',buildingId:'base-1'});expect(syncDropoffs(m).gathering.dropoffs).toEqual([m.placement.bases[0].footprint]);}});
it('two additional bases use stable IDs, enforce the live limit, and survive destruction independently',()=>{let m=finish(build(fixture()));m.gathering.wood=200;m.gathering.goldBalance=120;m=build(m,{x:288,y:512});m=finish(m);expect(m.placement.bases!.map(b=>b.id)).toEqual(['base-1','base-2']);expect(beginPlacement(m.placement,'base')).toBe(m.placement);m=trainBaseWorker(trainBaseWorker(m,'base-1'),'base-2');const dead=m.placement.bases![0].footprint;m.placement.bases![0].hp=0;m=updateMatch(m,.1);expect(m.placement.bases!.map(b=>b.id)).toEqual(['base-2']);expect(inspectedBuilding(m,'base-1')).toBeNull();expect(m.placement.bases![0].production.queue).toHaveLength(1);expect(m.map.obstacles).not.toContainEqual(dead);expect(m.outcome).toBe('playing');expect(beginPlacement(m.placement,'base').active).toBe(true);expect(m.placement.nextBaseNumber).toBe(3);});
it('a shared base upgrade pauses every worker queue and resumes exact remaining work',async()=>{const {startBaseUpgrade}=await import('./baseUpgrade');let m=finish(build(fixture()));m.gathering.wood=300;m.gathering.goldBalance=160;m=trainBaseWorker(trainBaseWorker(m,'base'),'base-1');m=startBaseUpgrade(m);const remaining=m.placement.bases![0].production.remainingSeconds;m=updateMatch(m,1);expect(m.placement.bases![0].production.remainingSeconds).toBe(remaining);expect(m.gathering.units).toHaveLength(3);m=updateMatch(m,24);expect(m.combat.baseDevelopment?.level).toBe(2);expect(m.gathering.units).toHaveLength(5);});
// Construction advances all three owners before the Save roundtrip.
// This integration needs a shared-runner budget rather than the unit default.
it('team match keeps human orders and validated snapshots after losing the first of two bases',async()=>{const {matchPlayers}=await import('./players'),{isSpectating}=await import('./teamResults'),{issueOrder}=await import('./commandOrders');let m=createMatch('skirmish','normal',undefined,'plains96',1,'balanced',matchPlayers(undefined,undefined,3));m.gathering.wood=300;m.gathering.goldBalance=160;m.gathering.units[2].selected=true;m=finish(build(m));m.combat.baseHP=0;m=updateMatch(m,.25);expect(m.outcome).toBe('playing');expect(isSpectating(m)).toBe(false);expect(issueOrder(m,{kind:'move',destination:{x:650,y:430}})).not.toBe(m);const loaded=decodeSave(encodeSave(m,view));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(loaded.ok)expect(loaded.match.placement.bases).toEqual(m.placement.bases);},30000);
