import {legacyTerrainFixture} from './testHelpers/legacyTerrainFixture';
import {expect,it} from 'vitest';
import {factions,factionIds} from '../config/factions';
import {factionSpells,spellForSlot,spellDefinition,spellAIConfig} from '../config/spells';
import {createMatch,updateMatch} from './match';
import {matchFog} from './matchFog';
import {castSpell,spellCasterReason,spellModifiers,advanceSpells} from './spells';
import {prepareEnemySpells,untilSpellBoundary} from './enemySpells';
import {encodeSave,decodeSave} from './save';
import {actionPanel} from '../presentation/actionPanel';
import {selectionInfo} from '../presentation/selectionInfo';
import type {Soldier} from './gathering';
function fixture(f:typeof factionIds[number]='crown'){
 const m=createMatch('skirmish','normal',{player:f,enemy:f}),profile=factions[f];
 const own=(id:string,x:number,hp:number,archetype?:'specialist'):Soldier=>({kind:'soldier',...(archetype?{archetype,faction:f}:{}),id,owner:'player',selected:!!archetype,cargo:0,hp,autoDisabled:true,position:{x,y:300},target:{x,y:300},order:{kind:'idle'},...(archetype?{mana:profile.units.specialist.mana!.max}:{})});
 m.gathering.units.push(own('unit-4',400,profile.units.specialist.hp,'specialist'),own('unit-5',460,profile.units.soldier.hp*.35));m.production.nextUnitNumber=6;m.soldierProduction.nextUnitNumber=6;
 m.combat.enemies.push({id:'enemy-produced-1',owner:'enemy',kind:'unit',role:'specialist',hp:profile.units.specialist.hp,mana:profile.units.specialist.mana!.max,position:{x:530,y:300},order:{kind:'idle'}},{id:'enemy-produced-2',owner:'enemy',kind:'unit',role:'soldier',hp:profile.units.soldier.hp*.35,position:{x:540,y:360},order:{kind:'idle'}});m.enemyProduction!.production.nextUnitNumber=3;m.enemyProduction!.acceptedJobs=2;m.fog=matchFog(m);return m;
}
it.each(factionIds)('%s has a distinct role-based loadout, real effects, correct HUD slots and save/restart state',f=>{
 let m=fixture(f);const caster=m.gathering.units[3] as Soldier;let paid=0;
 for(const id of factionSpells[f]){const cfg=spellDefinition(id,f),target=cfg.targetTeam==='enemy'?'enemy-produced-2':'unit-5';const cast=castSpell(m,caster.id,id,target);expect(cast.reason).toBeNull();m=cast.match;paid+=cfg.manaCost;expect((m.gathering.units[3] as Soldier).mana).toBe(caster.mana!-paid);const u=cfg.targetTeam==='enemy'?m.combat.enemies.at(-1)!:m.gathering.units[4] as Soldier;if(cfg.kind==='heal')expect(u.hp).toBe(Math.min(factions[f].units.soldier.hp,factions[f].units.soldier.hp*.35+cfg.healHP!));else{expect(u.spellEffects).toMatchObject([{spell:id,remainingSeconds:cfg.duration}]);expect(spellModifiers(u)).toMatchObject({attack:cfg.attackMultiplier??1,defense:cfg.defenseMultiplier??1});}}
 for(const slot of ['heal','ward','hex'] as const){expect(actionPanel(m,null,true)[`cast-${slot}`].visible).toBe(!!spellForSlot(f,slot));}
 const json=encodeSave(m,{camera:{x:0,y:0},building:null}),loaded=decodeSave(json);expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(loaded.ok){expect(loaded.match.gathering.units).toEqual(m.gathering.units);expect(loaded.match.combat.enemies).toEqual(m.combat.enemies);}
 expect(createMatch('skirmish','normal',{player:f,enemy:f}).gathering.units.some(u=>'spellEffects'in u||'spellCooldowns'in u||'mana'in u)).toBe(false);
});
it('five loadouts are different, foreign spells are unavailable and goblin overclock has a real damage tradeoff',()=>{expect(new Set(factionIds.map(f=>factionSpells[f].join(','))).size).toBe(5);const m=fixture('goblins');expect(spellCasterReason(m,'unit-4','ward')).toMatch(/unavailable/);const cast=castSpell(m,'unit-4','overclock','unit-5').match;expect(spellModifiers(cast.gathering.units[4] as Soldier)).toEqual({attack:1.4,defense:1.2});expect(selectionInfo({...cast,gathering:{...cast.gathering,units:cast.gathering.units.map(u=>({...u,selected:u.id==='unit-5'}))}},null).stats).toContain('Effects: Overclock 5.0s');});
it.each(['crown','elves','dwarves'] as const)('%s AI heals the most injured valid ally and pays the same costs/cooldowns',f=>{const m=fixture(f),id=spellForSlot(f,'heal')!,cfg=spellDefinition(id,f),next=prepareEnemySpells(m);expect(next.combat.enemies.at(-1)!.hp).toBe(factions[f].units.soldier.hp*.35+cfg.healHP!);expect(next.combat.enemies.at(-2)).toMatchObject({mana:factions[f].units.specialist.mana!.max-cfg.manaCost,spellCooldowns:{[id]:cfg.cooldown}});expect(next.gathering.units).toEqual(m.gathering.units);});
it.each(['clans','goblins'] as const)('%s AI applies debuff then a battle-relevant buff without stacking or spending between decisions',f=>{let m=fixture(f),initial=factions[f].units.specialist.mana!.max;m=prepareEnemySpells(m);const hex=spellForSlot(f,'hex')!,buff=spellForSlot(f,'ward')!;expect((m.gathering.units[4] as Soldier).spellEffects).toMatchObject([{spell:hex}]);expect(prepareEnemySpells({...m,waves:{...m.waves,elapsedSeconds:.25}}).combat.enemies).toBe(m.combat.enemies);m={...m,waves:{...m.waves,elapsedSeconds:spellAIConfig.decisionSeconds}};m=prepareEnemySpells(m);expect(m.combat.enemies.at(-2)).toMatchObject({mana:initial-spellDefinition(hex,f).manaCost-spellDefinition(buff,f).manaCost,spellEffects:[{spell:buff}]});const third=prepareEnemySpells({...m,waves:{...m.waves,elapsedSeconds:1}});expect(third.combat.enemies.at(-2)!.mana).toBe(m.combat.enemies.at(-2)!.mana);});
it('AI respects pause/end, fog, mana, range, team and target lifetime; no peacetime buff',()=>{let m=fixture('clans');expect(prepareEnemySpells({...m,paused:true})).toMatchObject({combat:m.combat});expect(prepareEnemySpells({...m,outcome:'defeat'})).toMatchObject({combat:m.combat});m.fog!.teams.enemy.visible.fill(false);expect(prepareEnemySpells(m).combat.enemies).toBe(m.combat.enemies);m.fog=matchFog(m);m.combat.enemies.at(-2)!.mana=0;expect(prepareEnemySpells(m).combat.enemies).toBe(m.combat.enemies);m.combat.enemies.at(-2)!.mana=80;m.gathering.units=m.gathering.units.filter(u=>u.kind==='worker');expect(prepareEnemySpells(m).combat.enemies).toBe(m.combat.enemies);m.combat.enemies.at(-2)!.hp=0;expect(prepareEnemySpells(m)).toBe(m);});
it('refresh replaces one channel, debuff can coexist and all effects expire without changing orders',()=>{let m=fixture('goblins');m=castSpell(m,'unit-4','overclock','unit-4').match;m=castSpell(m,'enemy-produced-1','corrode','unit-4','enemy').match;expect((m.gathering.units[3] as Soldier).spellEffects).toHaveLength(2);expect(spellModifiers(m.gathering.units[3] as Soldier)).toEqual({attack:1.4,defense:1.5});m=advanceSpells(m,2);(m.gathering.units[3] as Soldier).spellCooldowns={};m=castSpell(m,'unit-4','overclock','unit-4').match;expect((m.gathering.units[3] as Soldier).spellEffects).toHaveLength(2);expect((m.gathering.units[3] as Soldier).spellEffects!.find(e=>e.spell==='overclock')!.remainingSeconds).toBe(5);const tick=advanceSpells(m,5);expect(spellModifiers(tick.gathering.units[3] as Soldier)).toEqual({attack:1,defense:1});expect(tick.gathering.units[3].order).toEqual({kind:'idle'});});
it('migrates39 without reinterpreting existing faction effects/cooldowns, rejects forged new IDs',()=>{const m=fixture('clans');(m.gathering.units[3] as Soldier).spellCooldowns={ward:7};(m.gathering.units[4] as Soldier).spellEffects=[{spell:'ward',sourceFaction:'clans',remainingSeconds:4}];const old=JSON.parse(encodeSave(m,{camera:{x:0,y:0},building:null}));legacyTerrainFixture(old);old.configVersion='tribute-config-39';const loaded=decodeSave(JSON.stringify(old));expect(loaded.ok).toBe(true);if(loaded.ok){expect(spellModifiers(loaded.match.gathering.units[4] as Soldier).defense).toBe(.75);expect(loaded.match.gathering.units[3]).toMatchObject({spellCooldowns:{ward:7}});}old.state.gathering.units[3].spellCooldowns.rally=1;expect(decodeSave(JSON.stringify(old)).ok).toBe(false);});
it('match steps exactly at effect expiration and AI decision boundaries even for a long update',()=>{let m=fixture('crown');m.combat.enemies=m.combat.enemies.filter(e=>e.kind!=='unit');(m.gathering.units[3] as Soldier).spellEffects=[{spell:'ward',sourceFaction:'crown',remainingSeconds:.25}];expect(untilSpellBoundary(m)).toBe(.25);const n=updateMatch(m,.5);expect((n.gathering.units.find(u=>u.id==='unit-4') as Soldier).spellEffects).toEqual([]);const ai=fixture('clans');expect(untilSpellBoundary(ai)).toBe(.5);const stepped=updateMatch(ai,.6);expect(stepped.combat.enemies.find(e=>e.id==='enemy-produced-1')).toMatchObject({spellCooldowns:{intimidate:9.4,rally:9.9}});});
