import {describe,it,expect} from 'vitest';
import {factions,factionIds,factionsForPlayer} from '../config/factions';
import {createMatch} from './match';
import {trainGiant} from './giants';
import {trainHealer,updateHealerProduction,healerTargetReason} from './healers';
import {matchPopulation} from './navy';
import {encodeSave,decodeSave} from './save';
import {updateCombat} from './combat';
import {commandMappedMove,advanceRoute,findRoute} from './navigation';
import {selectUnitAt} from './selection';
import {combatUnitStats} from '../config/unit';
import {unitOrigin} from '../presentation/animation';
import {createMap,bodyFits} from './map';
import {prepareEnemyConstruction,updateEnemyConstruction} from './enemyConstruction';
import {updateEnemyProduction} from './enemyProduction';
const view={camera:{x:0,y:0},building:null};
function ready(id= 'crown' as typeof factionIds[number]){const m=createMatch('skirmish','normal',factionsForPlayer(id));m.gathering.wood=300;m.gathering.goldBalance=300;m.research={...m.research!,attack:2,defense:2};m.combat.baseDevelopment={level:3,remainingSeconds:null};const footprint={x:512,y:384,width:64,height:64};m.placement.academy={id:'academy',owner:'player',hp:factions[id].buildings.academy.hp,footprint,construction:{remainingSeconds:0,builderId:null}};m.map.obstacles.push(footprint);return m;}
const giant=(m:ReturnType<typeof ready>)=>m.gathering.units.find(u=>u.kind==='soldier'&&u.archetype==='giant')!;
describe('high-tier giants',()=>{
 it.each(factionIds)('%s pays the high-supply Academy recipe and restores production/unit after Save',id=>{let m=trainGiant(ready(id));expect(m.gathering.wood).toBe(210);expect(m.gathering.goldBalance).toBe(230);expect(matchPopulation(m).reserved).toBe(4);const loaded=decodeSave(encodeSave(m,view));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(!loaded.ok)return;m=updateHealerProduction(loaded.match,23.9);expect(m.gathering.units).toHaveLength(3);m=updateHealerProduction(m,.1);expect(giant(m)).toMatchObject({hp:320,faction:id,archetype:'giant'});expect(matchPopulation(m).used).toBe(7);expect(decodeSave(encodeSave(m,view)).ok).toBe(true);expect(unitOrigin('giant').y).toBe(56/64);});
 it('requires base III, both research II, a ready Academy and enough gold/supply',()=>{const m=ready();m.combat.baseDevelopment!.level=2;expect(trainGiant(m).gathering).toBe(m.gathering);m.combat.baseDevelopment!.level=3;m.research!.attack=1;expect(trainGiant(m).gathering).toBe(m.gathering);m.research!.attack=2;m.gathering.goldBalance=69;expect(trainGiant(m).gathering).toBe(m.gathering);m.gathering.goldBalance=300;m.placement.academy!.construction.remainingSeconds=1;expect(trainGiant(m).gathering).toBe(m.gathering);m.placement.academy!.construction.remainingSeconds=0;const q=trainGiant(m);expect(trainGiant(q).gathering).toBe(q.gathering);});
 it('mixed Academy FIFO preserves distinct roles and exact paid durations',()=>{let m=ready();const footprint={x:608,y:384,width:64,height:64};m.placement.nextFarmNumber=2;m.placement.farms=[{id:'farm-1',owner:'player',hp:factions.crown.buildings.farm.hp,footprint,construction:{remainingSeconds:0,builderId:null}}];m.map.obstacles.push(footprint);m=trainHealer(trainGiant(m));expect(m.placement.academy!.production!.queue!.map(j=>j.kind)).toEqual(['giant','healer']);m=updateHealerProduction(m,24);expect(giant(m).hp).toBe(320);expect(m.gathering.units.some(u=>u.kind==='soldier'&&u.archetype==='healer')).toBe(false);m=updateHealerProduction(m,10);expect(m.gathering.units.at(-1)).toMatchObject({archetype:'healer',hp:55});expect(decodeSave(encodeSave(m,view)).ok).toBe(true);});
 it('does 2.5× melee building damage, ordinary unit damage and symmetric AI building damage',()=>{let m=updateHealerProduction(trainGiant(ready()),24);const g=giant(m);g.position={x:600,y:460};g.target={...g.position};g.order={kind:'attack',enemyId:'enemy-building'};const building={id:'enemy-building',kind:'building' as const,buildingType:'forge' as const,hp:1000,position:{x:630,y:460},footprint:{x:614,y:444,width:32,height:32}};let r=updateCombat({...m.gathering,units:[g]}, {baseHP:240,enemies:[building]},1);expect(r.combat.enemies[0].hp).toBe(925);g.order={kind:'attack',enemyId:'enemy-unit'};r=updateCombat({...m.gathering,units:[g]}, {baseHP:240,enemies:[{id:'enemy-unit',kind:'unit',hp:100,position:{x:630,y:460},order:{kind:'idle'}}]},1);expect(r.combat.enemies[0].hp).toBe(70);m.gathering.units=[];r=updateCombat(m.gathering,{baseHP:240,enemies:[{id:'enemy-produced-1',kind:'unit',owner:'enemy',role:'giant',hp:320,position:{x:m.gathering.base.x+35,y:m.gathering.base.y},order:{kind:'defend',targetId:'base'}}]},1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,'clans');expect(r.combat.baseHP).toBe(165);});
 it('navigates a normal 32px corridor and selects through the larger sprite click box',()=>{const m=updateHealerProduction(trainGiant(ready()),24),g=giant(m);if(g.kind!=='soldier')throw Error('giant');const map={...createMap(),width:320,height:192,obstacles:[{x:0,y:0,width:320,height:64},{x:0,y:96,width:320,height:96}],bodyHalf:15};const a={x:48,y:80},b={x:272,y:80};expect(findRoute(map,a,b).ok).toBe(true);const moved=commandMappedMove([{...g,position:a,target:a,selected:true},{...g,id:'unit-5',position:{x:100,y:80},target:{x:100,y:80},selected:true}],b,map);for(const u of moved){expect(u.navigation!.status).not.toBe('blocked');let p=u.position,r=u.navigation!;for(let i=0;i<80;i++){const next=advanceRoute(map,p,r,65,.1);p=next.position;r=next.route;expect(bodyFits(map,p,15)).toBe(true);}expect(r.status).toBe('arrived');}expect(selectUnitAt([{...g,selected:false,position:a}],{x:a.x+20,y:a.y},combatUnitStats(g).selectionSize!)[0].selected).toBe(true);});
 it('AI pays base III once after Academy and research II, preserves its exact tier/timer',()=>{let m=ready();const base=m.combat.enemies.find(e=>e.kind==='base')!;for(const kind of ['forge','academy'] as const)m.combat.enemies.push({...base,id:'enemy-'+kind,kind:'building',buildingType:kind,hp:120,construction:{remainingSeconds:0,builderId:null}});m.enemyPolicy!.research={...m.enemyPolicy!.research,attack:2,defense:2};m.enemyProduction={...m.enemyProduction!,wood:120,gold:100,baseDevelopment:{level:2,remainingSeconds:null}};m=prepareEnemyConstruction(m);expect(m.enemyProduction).toMatchObject({wood:0,gold:0,baseDevelopment:{level:2,remainingSeconds:30}});expect(prepareEnemyConstruction(m).enemyProduction!.wood).toBe(0);m=updateEnemyConstruction(m,29.9).match;expect(m.enemyProduction!.baseDevelopment!.level).toBe(2);m=updateEnemyConstruction(m,.1).match;expect(m.enemyProduction!.baseDevelopment).toEqual({level:3,remainingSeconds:null});const valid=ready();valid.enemyProduction!.baseDevelopment={level:3,remainingSeconds:null};expect(decodeSave(encodeSave(valid,view)).ok).toBe(true);});
 it('AI uses the Academy giant recipe without timing discounts',()=>{const m=ready('clans'),a=m.placement.academy!,e={id:'enemy-academy',kind:'building' as const,buildingType:'academy' as const,owner:'enemy' as const,hp:160,position:{x:900,y:500},footprint:{...a.footprint,x:868,y:468},construction:{remainingSeconds:0,builderId:null}};m.combat.enemies.push(e);const r=updateEnemyProduction({...m.enemyProduction!,wood:90,gold:70,acceptedJobs:7,roster:true},m.combat,m.gathering,m.map,24,'clans',{technology:{baseLevel:3,buildings:['base','academy'],research:{attack:2,defense:2}},site:e,population:{cap:8,used:0,reserved:0}});expect(r.state.wood).toBe(0);expect(r.state.gold).toBe(0);expect(r.combat.enemies.find(e=>e.role==='giant')).toMatchObject({hp:320});});
});
