import {describe,it,expect} from 'vitest';
import {factionIds,factions,factionsForPlayer} from '../config/factions';
import {createMatch,updateMatch,type MatchState} from './match';
import {trainHealer,updateHealerProduction,healerTargetReason,castHeal,prepareHealers,toggleHealAutocast} from './healers';
import {castSpell,selectedSpellForSlot,spellTargetAt} from './spells';
import {advanceSpells} from './spells';
import {advanceMana} from './mana';
import {matchPopulation} from './navy';
import {decodeSave,encodeSave} from './save';
import {matchPlayers} from './players';
import {projectMultiplePlayers} from './multiplePlayers';
import {cleanDestroyed} from './destruction';
import {createFog} from './fog';
import {matchFog} from './matchFog';
import {updateEnemyProduction} from './enemyProduction';
import {cancelProduction} from './productionQueue';
import type {Soldier} from './gathering';
const view={camera:{x:0,y:0},building:null};
function ready(id= 'crown' as typeof factionIds[number]){const m=createMatch('skirmish','normal',factionsForPlayer(id));m.gathering.wood=200;m.gathering.goldBalance=200;const footprint={x:512,y:384,width:64,height:64};m.placement.academy={id:'academy',owner:'player',hp:factions[id].buildings.academy.hp,footprint,construction:{remainingSeconds:0,builderId:null}};m.map.obstacles.push(footprint);return m;}
function fixture(){let m=updateHealerProduction(trainHealer(ready()),10);delete m.fog;const u=m.gathering.units.find((u):u is Soldier=>u.kind==='soldier'&&u.archetype==='healer')!;u.position={x:600,y:460};u.target={...u.position};u.selected=true;const w=m.gathering.units[0];w.position={x:630,y:460};w.target={...w.position};w.hp=10;return m;}
const caster=(m:MatchState)=>m.gathering.units.find((u):u is Soldier=>u.kind==='soldier'&&u.archetype==='healer')!;
describe('healing support production and shared target rules',()=>{
 it.each(factionIds)('%s pays the Academy recipe and saves its independent queue',id=>{let m=ready(id);const before=m.gathering.units.length;m=trainHealer(m);expect(m.gathering.wood).toBe(160);expect(m.gathering.goldBalance).toBe(170);expect(matchPopulation(m).reserved).toBe(2);let loaded=decodeSave(encodeSave(m,view));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(!loaded.ok)return;m=updateHealerProduction(loaded.match,9.99);expect(m.gathering.units).toHaveLength(before);m=updateHealerProduction(m,.01);expect(caster(m)).toMatchObject({hp:55,mana:50,healAutocast:false,faction:id,autoDisabled:true});expect(new Set(m.gathering.units.map(u=>u.id)).size).toBe(before+1);loaded=decodeSave(encodeSave(m,view));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);expect(createMatch().placement.academy).toBeUndefined();});
 it('rejects missing/incomplete Academy and insufficient resources/supply, refunds only once and destroys queue',()=>{const m=ready();m.placement.academy!.construction.remainingSeconds=1;expect(trainHealer(m).gathering).toBe(m.gathering);m.placement.academy!.construction.remainingSeconds=0;m.gathering.goldBalance=29;expect(trainHealer(m).gathering).toBe(m.gathering);m.gathering.goldBalance=200;let q=trainHealer(m);const job=q.placement.academy!.production!.queue![0];const r=cancelProduction(q.gathering,q.placement.academy!.production!,job.id);expect(r.gathering.goldBalance).toBe(185);expect(cancelProduction(r.gathering,r.production,job.id).gathering).toBe(r.gathering);q.placement.academy!.hp=0;q=cleanDestroyed(q);expect(q.placement.academy).toBeUndefined();});
 it('AI pays the identical recipe and produces a ready autocast healer at ten seconds',()=>{const m=ready(),a=m.placement.academy!;const enemy={id:'enemy-academy',kind:'building' as const,buildingType:'academy' as const,owner:'enemy' as const,hp:160,position:{x:900,y:500},footprint:{...a.footprint,x:868,y:468},construction:{remainingSeconds:0,builderId:null}};m.combat.enemies.push(enemy);const r=updateEnemyProduction({...m.enemyProduction!,wood:40,gold:30,acceptedJobs:6,roster:true},m.combat,m.gathering,m.map,10,'clans',{technology:{baseLevel:2,buildings:['base','academy'],research:{}},site:enemy,population:{cap:8,used:0,reserved:0}});expect(r.state.wood).toBe(0);expect(r.state.gold).toBe(0);expect(r.combat.enemies.find(e=>e.role==='healer')).toMatchObject({mana:50,healAutocast:true,hp:55});});
 it('queue reservations prevent a third healer from exceeding population',()=>{let m=trainHealer(trainHealer(ready()));expect(matchPopulation(m).reserved).toBe(4);const balance=m.gathering.goldBalance;m=trainHealer(m);expect(m.gathering.goldBalance).toBe(balance);expect(m.placement.academy!.production!.queue).toHaveLength(2);});
 it('manual Heal restores workers with clamp, spends mana/cooldown and produces a transient pulse',()=>{let m=fixture();const c=caster(m),w=m.gathering.units[0];expect(selectedSpellForSlot(m,'heal')).toBe('heal');expect(selectedSpellForSlot(m,'ward')).toBeUndefined();expect(spellTargetAt(m,'heal',w.position)).toBe(w.id);const healed=castSpell(m,c.id,'heal',w.id);expect(healed.reason).toBeNull();m=healed.match;expect(m.gathering.units[0].hp).toBe(factions.crown.units.worker.hp);expect(caster(m).mana).toBe(30);expect(caster(m).spellCooldowns!.heal).toBe(6);expect(m.gathering.units[0].healFlash).toBe(.6);expect(castHeal(m,c.id,w.id).match).toBe(m);m=advanceMana(advanceSpells(m,6),6);expect(caster(m).mana).toBe(36);expect(caster(m).spellCooldowns!.heal).toBe(0);m.fog=matchFog(m);expect(encodeSave(m,view)).not.toContain('healFlash');});
 it('rejects self/dead/buildings/mechanical/hostile/out of range/hidden targets atomically',()=>{const m=fixture(),c=caster(m),w=m.gathering.units[0];expect(healerTargetReason(m,c.id,c.id)).toBe('Cannot heal self');w.hp=0;expect(castHeal(m,c.id,w.id).match).toBe(m);w.hp=10;w.position.x=c.position.x+161;expect(healerTargetReason(m,c.id,w.id)).toMatch(/range/);w.position.x=630;m.fog=createFog(m.map);expect(healerTargetReason(m,c.id,w.id)).toMatch(/vision/);delete m.fog;const machine={...c,id:'unit-5',archetype:'catapult' as const,hp:10,position:{x:630,y:460}};m.gathering.units.push(machine);expect(healerTargetReason(m,c.id,machine.id)).toMatch(/Mechanical/);const base=m.combat.enemies.find(e=>e.kind==='base')!;expect(castHeal(m,c.id,base.id).match).toBe(m);const enemy={id:'enemy-produced-1',kind:'unit' as const,owner:'enemy' as const,role:'soldier' as const,hp:10,position:{x:630,y:460}};m.combat.enemies.push(enemy);expect(healerTargetReason(m,c.id,enemy.id)).toMatch(/allied/);});
 it('autocast opts in, uses fresh HP and conserves the second healer mana on a small injury',()=>{let m=fixture();const c=caster(m);c.healAutocast=true;m.gathering.units[0].hp=29;m.gathering.units.push({...c,id:'unit-5',position:{x:600,y:490},target:{x:600,y:490}});m=prepareHealers(m);expect(m.gathering.units[0].hp).toBe(30);expect(caster(m).mana).toBe(30);expect((m.gathering.units.find(u=>u.id==='unit-5') as Soldier).mana).toBe(50);m=toggleHealAutocast(m);expect(caster(m).healAutocast).toBe(false);});
 it('multiple healers can restore heavily wounded allies but skip hidden/dead targets and bounded decisions',()=>{let m=fixture();const c=caster(m);c.healAutocast=true;m.gathering.units.push({...c,id:'unit-5',hp:10,selected:false,healAutocast:false,position:{x:640,y:460},target:{x:640,y:460}});m=prepareHealers(m);expect(m.gathering.units.find(u=>u.id==='unit-5')!.hp).toBe(35);const later={...m,waves:{...m.waves,elapsedSeconds:.1}};expect(prepareHealers(later)).toBe(later);});
 it('persists autocast and rejects malformed flags, maintains cooldown after save/load',()=>{let m=fixture();m=toggleHealAutocast(m);m=castHeal(m,caster(m).id,m.gathering.units[0].id).match;m.fog=matchFog(m);const doc=JSON.parse(encodeSave(m,view));const saved=decodeSave(JSON.stringify(doc));expect(saved.ok,saved.ok?'':saved.error).toBe(true);if(saved.ok)expect(caster(saved.match)).toMatchObject({healAutocast:true,mana:30,spellCooldowns:{heal:6}});const u=doc.state.gathering.units.find((u:Soldier)=>u.archetype==='healer');u.healAutocast='yes';expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);});
 it('heals allied AI units and synchronizes authoritative HP; rejects hostile teams',()=>{const roster=matchPlayers(undefined,undefined,3);roster[2].teamId=1;let m=createMatch('skirmish','normal',undefined,'plains96',1,'balanced',roster);delete m.fog;const template:Soldier={id:'unit-4',kind:'soldier',owner:'player',archetype:'healer',cargo:0,hp:55,mana:50,selected:true,position:{x:500,y:400},target:{x:500,y:400},order:{kind:'idle'}};m.gathering.units.push(template);const bot=m.multiplePlayers!.ai[1];bot.state.combat.enemies.push({id:'enemy-produced-1',kind:'unit',owner:'enemy',role:'soldier',hp:10,position:{x:530,y:400}});m=projectMultiplePlayers(m);const target=m.combat.enemies.find(e=>e.playerId==='ai-2'&&e.role==='soldier')!;expect(healerTargetReason(m,'unit-4',target.id)).toBeNull();m=castHeal(m,'unit-4',target.id).match;expect(m.multiplePlayers!.ai[1].state.combat.enemies.find(e=>e.id==='enemy-produced-1')!.hp).toBe(35);m.multiplePlayers!.roster[2].teamId=2;caster(m).spellCooldowns={};expect(healerTargetReason(m,'unit-4',target.id)).toMatch(/allied/);});
 it('gameplay updates drive opt-in healing and mana using bounded decisions',()=>{let m=fixture();m=toggleHealAutocast(m);m=updateMatch(m,.1);expect(m.gathering.units[0].hp).toBe(30);expect(caster(m).mana).toBeCloseTo(30.1);});
});
