import {describe,it,expect} from 'vitest';
import {createMatch,updateMatch} from './match';
import {scenarioConfig,scenarioWaves,initialScenario} from '../config/scenarios';
import {matchLabels} from '../presentation/hud';
describe('three configured mission objectives',()=>{
 it.each(['mission-waves','mission-base','mission-outpost'] as const)('creates isolated %s start/map/instruction and resets progress',id=>{const a=createMatch(id),b=createMatch(id);expect(a.scenario).toBe(id);expect(a.gathering.wood).toBe(scenarioConfig[id].initial.wood);expect(a.gathering.goldBalance).toBe(scenarioConfig[id].initial.gold);expect(a.combat.enemies.some(e=>e.kind==='base')).toBe(id==='mission-base');expect(initialScenario(id)).toBe(id);expect(scenarioConfig[id].instruction.length).toBeGreaterThan(50);a.gathering.wood=999;a.waves.elapsedSeconds=80;a.fog!.teams.player.explored.fill(true);expect(b.waves.elapsedSeconds).toBe(0);expect(b.gathering.wood).toBe(scenarioConfig[id].initial.wood);expect(b.fog!.teams.player.explored.every(Boolean)).toBe(false);});
 it('timer ends at exactly 90 gameplay seconds even with enemies alive and a large delta',()=>{const s=createMatch('mission-outpost');s.waves.elapsedSeconds=89;s.waves.nextWave=3;s.combat.enemies=[{id:'alive',hp:36,position:{x:1200,y:900},order:{kind:'idle'}}];const won=updateMatch(s,200);expect(won.outcome).toBe('victory');expect(won.waves.elapsedSeconds).toBe(90);expect(won.combat.enemies).toHaveLength(1);expect(updateMatch(won,100)).toBe(won);});
 it('does not end early, freezes timer in pause and gives simultaneous defeat priority',()=>{const s=createMatch('mission-outpost');s.waves.elapsedSeconds=89.99;s.waves.nextWave=3;expect(updateMatch(s,0).outcome).toBe('playing');expect(updateMatch({...s,paused:true},500).waves.elapsedSeconds).toBe(89.99);const same={...s,waves:{...s.waves,elapsedSeconds:90},combat:{...s.combat,baseHP:0}};expect(updateMatch(same,0).outcome).toBe('defeat');});
 it('also gives actual lethal damage at the timer boundary priority',()=>{const s=createMatch('mission-outpost');s.waves.elapsedSeconds=89.9;s.waves.nextWave=3;s.combat.baseHP=.1;s.combat.enemies=[{id:'attacker',hp:36,position:{x:450,y:450}}];const end=updateMatch(s,1);expect(end.outcome).toBe('defeat');expect(end.waves.elapsedSeconds).toBeCloseTo(90);});
 it('wave/base missions require their different objectives, never just a timer',()=>{const w=createMatch('mission-waves');w.waves.elapsedSeconds=999;expect(updateMatch(w,0).outcome).toBe('playing');w.waves.nextWave=3;expect(updateMatch(w,0).outcome).toBe('victory');const b=createMatch('mission-base');b.waves.elapsedSeconds=999;expect(updateMatch(b,0).outcome).toBe('playing');b.combat.enemies[0]!.hp=0;expect(updateMatch(b,0).outcome).toBe('victory');});
 it('configures outpost pressure per profile while preserving classic difficulty waves',()=>{expect(scenarioWaves('mission-outpost','normal')).toEqual([{atSeconds:30,count:1},{atSeconds:60,count:2},{atSeconds:80,count:2}]);expect(scenarioWaves('mission-outpost','hard')[0]).toEqual({atSeconds:25,count:2});expect(scenarioWaves('mission-outpost','easy')[0]).toEqual({atSeconds:40,count:1});expect(matchLabels(createMatch('mission-outpost')).wave).toContain('90.0 s');expect(createMatch().gathering.wood).toBe(0);});
});
