import {expect,it} from 'vitest';
import {constructionRate} from '../config/construction';
import {createMatch} from './match';
import {createClassicMatch} from './testHelpers/classicMatch';
import {placeBarracks,placementObstacles} from './placement';
import {resumeConstruction,updateConstruction} from './construction';
import {cleanDestroyed} from './destruction';
import {encodeSave,decodeSave} from './save';
function fixture(){let m=createMatch();m.gathering.wood=100;m.gathering.units[0].selected=true;const r=placeBarracks({...m.placement,active:true},{x:512,y:384},100,placementObstacles(m.gathering),{map:m.map,gathering:m.gathering,enemies:[]});m={...m,gathering:r.gathering!,placement:r.placement,map:r.map!};m.gathering.units.forEach((u,i)=>{u.position=[{x:496,y:400},{x:496,y:432},{x:544,y:464}][i];u.target=u.position;u.selected=true;u.navigation=undefined;});return {...m,...resumeConstruction(m.gathering,m.placement,m.map)};}
const tick=(m:ReturnType<typeof fixture>,seconds:number)=>({...m,...updateConstruction(m.gathering,m.placement,m.map,seconds)});
it('joins three workers without cost and uses configurable diminishing contributions',()=>{let m=fixture();expect(m.gathering.wood).toBe(60);expect(constructionRate(3)).toBe(1.75);expect(m.gathering.units.every(u=>u.order.kind==='build')).toBe(true);m=tick(m,1);expect(m.placement.construction!.remainingSeconds).toBeCloseTo(3.25);expect(m.gathering.wood).toBe(60);m=tick(m,10);expect(m.placement.construction!.remainingSeconds).toBe(0);expect(m.gathering.units.every(u=>u.order.kind==='idle')).toBe(true);expect(tick(m,10).placement.construction).toEqual(m.placement.construction);});
it('new orders and dead primary worker leave remaining assistants working',()=>{let m=fixture();m=tick(m,1);m.gathering.units[1].order={kind:'move'};m.gathering.units[0].hp=0;m=cleanDestroyed(m);const before=m.placement.construction!.remainingSeconds;m=tick(m,1);expect(m.placement.construction!.remainingSeconds).toBeCloseTo(before-1);expect(m.placement.construction!.builderId).toBe('unit-3');expect(m.gathering.wood).toBe(60);});
it('blocked assistants contribute nothing while reachable workers continue',()=>{let m=fixture();m.gathering.units[1].position={x:800,y:400};m.gathering.units[2].position={x:800,y:432};m.map={...m.map,revision:m.map.revision+1,obstacles:[...m.map.obstacles,{x:736,y:0,width:32,height:m.map.height}]};m=tick(m,1);expect(m.placement.construction!.remainingSeconds).toBeCloseTo(4);expect(m.gathering.units[1].navigation!.status).toBe('blocked');});
it('save/load retains all orders and partial progress; timestep subdivision and restart agree',()=>{let m=fixture();m=tick(m,1);const loaded=decodeSave(encodeSave(m,{camera:{x:0,y:0},building:null}));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(!loaded.ok)return;expect(loaded.match.gathering.units.filter(u=>u.order.kind==='build')).toHaveLength(3);expect(tick(loaded.match,1).placement.construction!.remainingSeconds).toBeCloseTo(1.5);let small=fixture();for(let i=0;i<100;i++)small=tick(small,.02);expect(small.placement.construction!.remainingSeconds).toBeCloseTo(tick(fixture(),2).placement.construction!.remainingSeconds);expect(createMatch().placement.construction).toBeUndefined();});
it('all workers leaving pauses and a selected worker rejoins the same paid building',()=>{let m=fixture();m=tick(m,1);m.gathering.units.forEach(u=>{u.order={kind:'idle'};u.selected=false;});const remaining=m.placement.construction!.remainingSeconds;m=tick(m,10);expect(m.placement.construction!.remainingSeconds).toBe(remaining);m.gathering.units[2].selected=true;m={...m,...resumeConstruction(m.gathering,m.placement,m.map)};m=tick(m,1);expect(m.placement.construction!.remainingSeconds).toBeCloseTo(remaining-1);expect(m.gathering.wood).toBe(60);});
it('harbor workers join the same paid site and all release on completion',async()=>{const {placeHarbor,resumeHarbor,updateNavy}=await import('./navy');let m=createClassicMatch('mission-outpost','easy');m.gathering.wood=1000;m.gathering.goldBalance=1000;m.gathering.units.forEach((u,i)=>u.selected=i===0);m.placement={...m.placement,active:true,kind:'harbor'};m=placeHarbor(m,{x:192,y:416});expect(m.navy?.harbor).toBeTruthy();const bank=m.gathering.wood;m.gathering.units.forEach(u=>u.selected=true);m=resumeHarbor(m);expect(m.gathering.units.filter(u=>u.order.kind==='build')).toHaveLength(3);m=updateNavy(m,100);expect(m.navy!.harbor!.construction.remainingSeconds).toBe(0);expect(m.gathering.units.every(u=>u.order.kind!=='build')).toBe(true);expect(m.gathering.wood).toBe(bank);});
