import {legacyTerrainFixture} from './testHelpers/legacyTerrainFixture';
import {expect,it} from 'vitest';
import {operationConfig,operationFor} from '../config/operations';
import {campaignMissions,campaignPreset} from '../config/campaign';
import {factions} from '../config/factions';
import {createMatch,updateMatch,type MatchState} from './match';
import {operationOutcome,controlsCapture} from './operations';
import {operationMarkers,operationMessage} from '../presentation/operations';
import {bodyFits} from './map';
import {findRoute} from './navigation';
import {matchPopulation} from './navy';
import {matchStats} from './matchStats';
import {encodeSave,decodeSave} from './save';
const view={camera:{x:0,y:0},building:null};
const operationMatch=(scenario:'mission-escort'|'mission-rescue'|'mission-capture')=>{const mission=campaignMissions.find(m=>m.scenario===scenario)!;return {...createMatch(scenario,'normal',campaignPreset(mission.id)),campaignMission:mission.id};};
/** Explicit goal fixtures isolate objective rules; paid playthroughs are separate. */
function soldier(m:MatchState,position:{x:number;y:number}){const id=`unit-${m.production.nextUnitNumber++}`;m.soldierProduction.nextUnitNumber=m.production.nextUnitNumber;m.gathering.units.push({id,kind:'soldier',owner:'player',position:{...position},target:{...position},hp:factions[m.factions!.player].units.soldier.hp,cargo:0,selected:false,order:{kind:'idle'}});return m.gathering.units.at(-1)!;}
for(const scenario of Object.keys(operationConfig) as (keyof typeof operationConfig)[]){
 it(`${scenario}: authored entities, legal geometry, starting stats/supply and fresh Save`,()=>{
  const m=operationMatch(scenario),o=operationConfig[scenario];expect(m.outcome).toBe('playing');expect(m.combat.enemies.map(e=>e.id)).toEqual(o.guards.map(g=>g.id));
  expect(m.combat.enemies.every(e=>e.role==='soldier'&&e.hp===factions[m.factions!.enemy].units.soldier.hp)).toBe(true);
  for(const e of m.combat.enemies)expect(bodyFits(m.map,e.position,12)).toBe(true);expect(bodyFits(m.map,o.zone,20)).toBe(true);
  if(o.kind==='escort'){const courier=m.gathering.units.find(u=>u.id===o.courier.id)!;expect(bodyFits(m.map,courier.position,12)).toBe(true);expect(findRoute(m.map,courier.position,o.zone).ok).toBe(true);}
  if(o.kind==='rescue')expect(findRoute(m.map,m.gathering.units[0].position,o.zone).ok).toBe(true);
  expect(matchStats(m).player).toMatchObject({added:0,lost:0,killed:0});expect(matchStats(m).enemy).toMatchObject({added:0,lost:0,killed:0});expect(matchPopulation(m).used).toBe(o.kind==='escort'?4:3);
  expect(decodeSave(encodeSave({...m,paused:true},view)).ok).toBe(true);expect(updateMatch({...m,paused:true},20).waves.elapsedSeconds).toBe(0);
 });
 it(`${scenario}: base death has precedence and freezes simulation`,()=>{const m=operationMatch(scenario);m.combat.baseHP=0;const ended=updateMatch(m,100);expect(ended.outcome).toBe('defeat');expect(updateMatch(ended,100)).toBe(ended);expect(decodeSave(encodeSave(ended,view)).ok).toBe(true);});
}
it('escort requires the named courier alive, both guards dead and arrival; ordinary worker loss is not defeat',()=>{
 const m=operationMatch('mission-escort'),o=operationConfig['mission-escort'],courier=m.gathering.units.find(u=>u.id===o.courier.id)!;
 m.gathering.units=m.gathering.units.filter(u=>u.id!=='unit-1');expect(operationOutcome(m)).toBe('playing');courier.position={...o.zone};expect(operationOutcome(m)).toBe('playing');m.combat.enemies=[];expect(operationOutcome(m)).toBe('victory');courier.hp=0;expect(operationOutcome(m)).toBe('defeat');
});
it('escort cannot be completed by a different worker, and courier loss ends an otherwise live match',()=>{const m=operationMatch('mission-escort'),o=operationConfig['mission-escort'];m.combat.enemies=[];m.gathering.units[0].position={...o.zone};expect(operationOutcome(m)).toBe('playing');m.gathering.units=m.gathering.units.filter(u=>u.id!==o.courier.id);expect(updateMatch(m,0).outcome).toBe('defeat');expect(decodeSave(encodeSave(updateMatch(m,0),view)).ok).toBe(true);});
it('escort success at the zone boundary preserves starting casualty/production counts through Save',()=>{const m=operationMatch('mission-escort'),o=operationConfig['mission-escort'];m.combat.enemies=[];m.gathering.units.find(u=>u.id===o.courier.id)!.position={x:o.zone.x+o.radius,y:o.zone.y};const ended=updateMatch(m,0);expect(ended.outcome).toBe('victory');expect(matchStats(ended).player.added).toBe(0);expect(matchStats(ended).enemy).toMatchObject({added:0,lost:2});expect(decodeSave(encodeSave(ended,view)).ok).toBe(true);});
it('rescue requires both named guards and living land combat presence; workers and unrelated enemies do not substitute',()=>{const m=operationMatch('mission-rescue'),o=operationConfig['mission-rescue'];m.gathering.units[0].position={...o.zone};m.combat.enemies=[];expect(operationOutcome(m)).toBe('playing');const unit=soldier(m,{x:o.zone.x+o.radius,y:o.zone.y});expect(operationOutcome(m)).toBe('victory');unit.hp=0;expect(operationOutcome(m)).toBe('playing');});
it('rescue combat presence does not bypass either living guard',()=>{const m=operationMatch('mission-rescue'),o=operationConfig['mission-rescue'];soldier(m,o.zone);expect(operationOutcome(m)).toBe('playing');m.combat.enemies.pop();expect(operationOutcome(m)).toBe('playing');m.combat.enemies=[];expect(updateMatch(m,0).outcome).toBe('victory');});
it('capture ignores workers and counts enemies on the boundary as contesting',()=>{const m=operationMatch('mission-capture'),o=operationConfig['mission-capture'];m.combat.enemies=[];m.gathering.units[0].position={...o.zone};expect(controlsCapture(m)).toBe(false);soldier(m,o.zone);expect(controlsCapture(m)).toBe(true);m.combat.enemies.push({id:'enemy-1',owner:'enemy',kind:'unit',role:'soldier',hp:70,position:{x:o.zone.x+o.radius,y:o.zone.y},order:{kind:'attack-move',destination:{...o.guards[0].position}}});expect(controlsCapture(m)).toBe(false);});
it('capture absence resets accumulated time, reentry starts from zero, and base death wins a simultaneous hold',()=>{let m:MatchState=operationMatch('mission-capture');const o=operationConfig['mission-capture'];m.combat.enemies=[];const u=soldier(m,o.zone);m=updateMatch(m,10);expect(m.capture?.holdSeconds).toBeCloseTo(10);m.gathering.units[0].position={x:500,y:450};m.gathering.units.find(v=>v.id===u.id)!.position={x:o.zone.x+100,y:o.zone.y};m=updateMatch(m,.1);expect(m.capture?.holdSeconds).toBe(0);m.gathering.units.find(v=>v.id===u.id)!.position={...o.zone};m=updateMatch(m,20);expect(m.capture?.holdSeconds).toBe(20);expect(m.outcome).toBe('playing');m.combat.baseHP=0;m.capture!.holdSeconds=30;expect(updateMatch(m,0).outcome).toBe('defeat');});
it('capture has equal gameplay timing over different deltas, exact completion and partial Save/load',()=>{
 for(const delta of [.05,.2,1,7]){let m:MatchState=operationMatch('mission-capture');m.combat.enemies=[];soldier(m,operationConfig['mission-capture'].zone);m=updateMatch(m,12);const loaded=decodeSave(encodeSave({...m,paused:true},view));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(!loaded.ok)continue;m={...loaded.match,paused:false};expect(m.capture?.holdSeconds).toBe(12);for(let i=0;i<1000&&m.outcome==='playing';i++)m=updateMatch(m,delta);expect(m.outcome).toBe('victory');expect(m.waves.elapsedSeconds).toBeCloseTo(30,7);expect(m.capture?.holdSeconds).toBe(30);expect(decodeSave(encodeSave(m,view)).ok).toBe(true);}
});
it('capture zero delta and pause add no hold time',()=>{const m=operationMatch('mission-capture');m.combat.enemies=[];soldier(m,operationConfig['mission-capture'].zone);expect(updateMatch(m,0).capture?.holdSeconds).toBe(0);expect(updateMatch({...m,paused:true},100).capture?.holdSeconds).toBe(0);});
it('mission markers respect fog and name real courier/guards; status explains goals',()=>{const m=operationMatch('mission-escort');expect(operationMarkers(m).map(m=>m.label)).toEqual(['Ridge Courier']);expect(operationMessage(m)).toMatch(/Guards remaining: 2/);const o=operationFor(m.scenario)!;m.fog=undefined;expect(operationMarkers(m).map(m=>m.label)).toEqual(['Safe Zone','Ridge Courier',...o.guards.map(g=>g.name)]);});
it('config31 campaign migration preserves existing match identity and does not inject operation state',()=>{const m={...createMatch('tutorial','beginner',{player:'elves',enemy:'dwarves'}),campaignMission:'first-steps' as const},doc=JSON.parse(encodeSave(m,view));legacyTerrainFixture(doc);doc.configVersion='tribute-config-31';const loaded=decodeSave(JSON.stringify(doc));expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(loaded.ok){expect(loaded.match.factions).toEqual(m.factions);expect(loaded.match.capture).toBeUndefined();}});
it('strict Save rejects spoofed courier, guards, capture time and operation state in legacy/other missions',()=>{
 const escort=operationMatch('mission-escort'),capture=operationMatch('mission-capture'),doc=JSON.parse(encodeSave(escort,view));doc.state.gathering.units.find((u:{id:string})=>u.id==='unit-4').kind='soldier';expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);
 const wrong=JSON.parse(encodeSave(escort,view));wrong.state.combat.enemies[0].id='enemy-99';expect(decodeSave(JSON.stringify(wrong)).ok).toBe(false);
 const badTime=JSON.parse(encodeSave(capture,view));badTime.state.capture.holdSeconds=31;expect(decodeSave(JSON.stringify(badTime)).ok).toBe(false);badTime.state.capture.holdSeconds=1;expect(decodeSave(JSON.stringify(badTime)).ok).toBe(false);
 const legacy=JSON.parse(encodeSave(capture,view));legacyTerrainFixture(legacy);legacy.configVersion='tribute-config-31';expect(decodeSave(JSON.stringify(legacy)).ok).toBe(false);
 const other=JSON.parse(encodeSave(createMatch('tutorial'),view));other.state.capture={holdSeconds:0};expect(decodeSave(JSON.stringify(other)).ok).toBe(false);
});

it('contesting an already controlled banner resets its hold and requires a new full interval',()=>{let m:MatchState=operationMatch('mission-capture');const o=operationConfig['mission-capture'],guard={...m.combat.enemies[0],position:{...o.zone}};m.combat.enemies=[];soldier(m,o.zone);m=updateMatch(m,10);expect(m.capture?.holdSeconds).toBe(10);m.combat.enemies=[guard];m=updateMatch(m,.1);expect(m.capture?.holdSeconds).toBe(0);m.combat.enemies=[];m=updateMatch(m,29);expect(m.outcome).toBe('playing');m=updateMatch(m,1);expect(m.outcome).toBe('victory');});
it('ships and embarked combatants cannot capture or rescue; an embarked living courier is not dead',()=>{const m=operationMatch('mission-capture'),o=operationConfig['mission-capture'];m.combat.enemies=[];const unit=soldier(m,o.zone);m.gathering.units=m.gathering.units.filter(u=>u.id!==unit.id);m.navy={harbor:null,ships:[{id:'ship-1',kind:'ship',role:'transport',owner:'player',hp:100,selected:false,position:{...o.zone},target:{...o.zone},order:{kind:'idle'},passengers:[unit]}],production:{remainingSeconds:null,nextUnitNumber:2}};expect(controlsCapture(m)).toBe(false);const escort=operationMatch('mission-escort'),courier=escort.gathering.units.find(u=>u.id==='unit-4')!;escort.gathering.units=escort.gathering.units.filter(u=>u.id!==courier.id);escort.navy={...m.navy,ships:[{...m.navy.ships[0],passengers:[courier]}]};expect(operationOutcome(escort)).toBe('playing');});
it('old five-completion local progression remains valid and unlocks the new convoy',async()=>{const {validateCampaignProgress,campaignMissionStatus}=await import('./campaign');const old={version:1,completed:campaignMissions.slice(0,5).map(m=>m.id)},progress=validateCampaignProgress(old);expect(progress).toEqual(old);expect(campaignMissionStatus(progress,'ridge-convoy')).toBe('available');expect(campaignMissionStatus(progress,'valley-rescue')).toBe('locked');});

it('a zero-time objective check resets lost control without advancing the match clock',()=>{let m:MatchState=operationMatch('mission-capture');m.combat.enemies=[];const u=soldier(m,operationConfig['mission-capture'].zone);m=updateMatch(m,10);m.gathering.units=m.gathering.units.filter(v=>v.id!==u.id);m=updateMatch(m,0);expect(m.capture?.holdSeconds).toBe(0);expect(m.waves.elapsedSeconds).toBe(10);});

it('dead courier and guards never appear as living mission markers or status',()=>{const m=operationMatch('mission-escort');m.fog=undefined;m.gathering.units.find(u=>u.id==='unit-4')!.hp=0;for(const e of m.combat.enemies)e.hp=0;expect(operationMarkers(m).map(v=>v.label)).toEqual(['Safe Zone']);expect(operationMessage(m)).toMatch(/Courier: lost/);expect(operationMessage(m)).toMatch(/remaining: 0/);});
