import {expect,it} from 'vitest';
import {createMatch} from './match';
import {startResearch,updateResearch,researchSummary} from './research';
import {encodeSave,decodeSave} from './save';
const view={camera:{x:0,y:0},building:null};
function ready(){const m=createMatch();m.gathering.wood=1000;m.gathering.goldBalance=1000;const footprint={x:256,y:384,width:64,height:64};m.placement.forge={id:'forge',owner:'player',hp:120,footprint,construction:{remainingSeconds:0,builderId:null}};m.map.obstacles.push(footprint);return m;}
it('pays once, reserves unique kinds, preserves FIFO across completion and leftover time',()=>{const m=ready();let r=startResearch(m.gathering,m.research!,m.placement,'attack');r=startResearch(r.gathering,r.research,m.placement,'defense');r=startResearch(r.gathering,r.research,m.placement,'workerTools');expect(r.research.queue).toEqual(['defense','workerTools']);const bank=r.gathering;for(const kind of ['attack','defense','workerTools'] as const)expect(startResearch(bank,r.research,m.placement,kind).gathering).toBe(bank);const next=updateResearch(r.research,m.placement,9);expect(next.attack).toBe(1);expect(next.job).toEqual({kind:'defense',remainingSeconds:7});expect(next.queue).toEqual(['workerTools']);expect(researchSummary(next)).toMatch(/13%.*7.0s.*1. Worker Tools/);const done=updateResearch(next,m.placement,22);expect(done).toMatchObject({attack:1,defense:1,workerTools:1,job:null,queue:[]});});
it('rejects unaffordable or prerequisite-ineligible jobs, respects pause and producer loss',()=>{const m=ready();const first=startResearch(m.gathering,m.research!,m.placement,'attack');expect(startResearch({...first.gathering,wood:0},first.research,m.placement,'defense').research).toBe(first.research);expect(startResearch(first.gathering,first.research,m.placement,'cavalryArmor').research).toBe(first.research);const second=startResearch(first.gathering,first.research,m.placement,'defense');const third=startResearch(second.gathering,second.research,m.placement,'workerTools');expect(updateResearch(third.research,m.placement,20,false)).toBe(third.research);m.placement.forge!.hp=0;const next=updateResearch(third.research,m.placement,0);expect(next.job?.kind).toBe('workerTools');expect(next.queue).toEqual([]);expect(next.attack).toBe(0);expect(next.defense).toBe(0);});
it('restores paid queue/progress and rejects duplicate, unknown and unqualified saved jobs',()=>{const m=ready();let r=startResearch(m.gathering,m.research!,m.placement,'attack');r=startResearch(r.gathering,r.research,m.placement,'defense');m.gathering=r.gathering;m.research=updateResearch(r.research,m.placement,2);const encoded=encodeSave(m,view),loaded=decodeSave(encoded);expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(loaded.ok){expect(loaded.match.research).toEqual(m.research);expect(loaded.match.gathering.wood).toBe(m.gathering.wood);}for(const queue of [['attack'],['defense','defense'],['unknown'],['cavalryArmor']]){const doc=JSON.parse(encoded);doc.state.research.queue=queue;expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);}expect(createMatch().research?.queue??[]).toEqual([]);});
