import {expect,it} from 'vitest';
import {resourceServices} from './resourceQueue';
import {updateGathering,orderUnits,type GatheringState,type Worker} from './gathering';
import type {WorldMap} from './map';
import {createMatch,updateMatch} from './match';
import {encodeSave,decodeSave} from './save';
const map:WorldMap={width:800,height:600,tileSize:32,revision:0,obstacles:[{x:380,y:180,width:40,height:40}]};
function fixture():GatheringState{return {node:{id:'wood',position:{x:400,y:200},remaining:100},base:{x:200,y:400},wood:0,units:Array.from({length:8},(_,i):Worker=>({id:`worker-${i+1}`,kind:'worker',selected:false,hp:30,position:{x:320,y:250+i*25},target:{x:400,y:200},order:{kind:'gather',nodeId:'wood'},cargo:0}))};}
it('admits at most three workers, with distinct contact and waiting points outside range',()=>{const s=fixture(),places=resourceServices(s,map,0);expect([...places.values()].filter(p=>p.working)).toHaveLength(3);expect(new Set([...places.values()].map(p=>`${p.point.x},${p.point.y}`)).size).toBe(8);s.units=s.units.map(u=>({...u,position:places.get(u.id)!.point}));const next=updateGathering(s,1,map,{elapsedSeconds:0});expect(next.node.remaining).toBe(97);expect(next.units.filter(u=>u.cargo>0)).toHaveLength(3);});
it('rotates service fairly, conserves wood, delivers the final cargo and leaves no stranded orders',()=>{let s=fixture();const served=new Set<string>();for(let i=0;i<2400;i++){s=updateGathering(s,.05,map,{elapsedSeconds:i*.05});for(const u of s.units)if(u.cargo>0)served.add(u.id);expect(s.node.remaining+s.wood+s.units.reduce((a,u)=>a+u.cargo,0)).toBeCloseTo(100,8);expect(s.node.remaining).toBeGreaterThanOrEqual(0);}expect(served.size).toBe(8);expect(s.node.remaining).toBe(0);expect(s.wood).toBeCloseTo(100);expect(s.units.every(u=>u.cargo===0&&u.order.kind==='idle')).toBe(true);});
it('new orders and dead workers leave service immediately; cancellation retains cargo',()=>{const s=fixture();s.units[0]={...(s.units[0] as Worker),selected:true,cargo:2};s.units=orderUnits(s.units,{x:300,y:400});s.units[1].hp=0;const services=resourceServices(s,map,0);expect(services.has('worker-1')).toBe(false);expect(services.has('worker-2')).toBe(false);expect(s.units[0].cargo).toBe(2);expect([...services.values()].filter(p=>p.working)).toHaveLength(3);});
it('service is derived identically after save/load and pause does not rotate it',()=>{let m=createMatch('skirmish');m.gathering.units=Array.from({length:8},(_,i)=>({...m.gathering.units[i%3],id:`unit-${i+1}`,position:{x:300+i*28,y:300}}));m.production.nextUnitNumber=9;m.soldierProduction.nextUnitNumber=9;m.waves.elapsedSeconds=7;m.gathering.units=m.gathering.units.map(u=>u.kind==='worker'?({...u,order:{kind:'gather',nodeId:m.gathering.node.id}}):u);m=updateMatch(m,.5);const saved=decodeSave(encodeSave(m,{camera:{x:0,y:0},building:null}));expect(saved.ok).toBe(true);if(!saved.ok)return;expect(resourceServices(saved.match.gathering,saved.match.map,saved.match.waves.elapsedSeconds)).toEqual(resourceServices(m.gathering,m.map,m.waves.elapsedSeconds));expect(resourceServices(m.gathering,m.map,m.waves.elapsedSeconds).size).toBe(8);const resumed=updateMatch({...saved.match,paused:false},.05),continued=updateMatch(m,.05);expect(resumed.gathering.units.map(u=>[u.id,u.order,u.cargo])).toEqual(continued.gathering.units.map(u=>[u.id,u.order,u.cargo]));expect(resumed.gathering.node.remaining).toBeCloseTo(continued.gathering.node.remaining);for(let i=0;i<resumed.gathering.units.length;i++){const a=resumed.gathering.units[i],b=continued.gathering.units[i];expect(Math.hypot(a.position.x-b.position.x,a.position.y-b.position.y)).toBeLessThanOrEqual(10.4);}m.paused=true;expect(updateMatch(m,10)).toBe(m);});
it('delivery trips release service slots so the remaining gatherers can work',()=>{const s=fixture();s.units=s.units.map((u,i)=>u.kind==='worker'&&i<5?{...u,order:{kind:'deliver',nodeId:'wood'}}:u);const services=resourceServices(s,map,0);expect([...services.values()].some(p=>p.working)).toBe(false);expect(services.has('worker-6')).toBe(false);});
it('returning carriers cannot bypass the shared slot limit inside a large delta',()=>{const s=fixture();s.units=s.units.map((u,i)=>u.kind==='worker'&&i<5?{...u,position:{x:260,y:400},cargo:1,order:{kind:'deliver',nodeId:'wood'}}:u);const next=updateGathering(s,20,map,{elapsedSeconds:0});expect(next.wood).toBeGreaterThanOrEqual(5);expect(next.units.slice(0,5).every(u=>u.cargo===0&&u.order.kind==='gather')).toBe(true);});
