import {it,expect} from 'vitest';
import {factions,factionIds,factionsForPlayer} from '../config/factions';
import {roleResearchKinds,roleResearchConfig,cavalryArmorMultiplier,trainedHealerMana,scoutDetectorRadius} from '../config/roleResearch';
import {createMatch,updateMatch} from './match';
import {startResearch,updateResearch,canResearch} from './research';
import {advanceMana,manaFor} from './mana';
import {encodeSave,decodeSave} from './save';
import {updateCombat} from './combat';
import {trainCavalry,updateCavalryProduction} from './cavalry';
import {trainHealer,updateHealerProduction} from './healers';
import {prepareEnemyPolicy} from './enemyPolicy';
const view={camera:{x:0,y:0},building:null};
function ready(id='crown' as typeof factionIds[number]){const m=createMatch('skirmish','normal',factionsForPlayer(id));m.gathering.wood=1000;m.gathering.goldBalance=1000;m.combat.baseDevelopment={level:2,remainingSeconds:null};for(const [i,kind]of ['forge','stable','academy','aviary'].entries()){const key=kind as 'forge'|'stable'|'academy'|'aviary',footprint={x:512+i*96,y:384,width:64,height:64};Object.assign(m.placement,{[key]:{id:key,owner:'player',hp:factions[id].buildings[key].hp,footprint,construction:{remainingSeconds:0,builderId:null},...(key==='stable'||key==='aviary'?{production:{remainingSeconds:null,nextUnitNumber:4}}:{})}});m.map.obstacles.push(footprint);}return m;}
it.each(factionIds)('%s shares cost/time/prerequisites, rejects duplicate research, preserves finished and active jobs',id=>{let m=ready(id);for(const kind of roleResearchKinds){const before=m.gathering,started=startResearch(before,m.research!,m.placement,kind);expect(before.wood-started.gathering.wood).toBe(45);expect(before.goldBalance!-started.gathering.goldBalance!).toBe(30);m={...m,gathering:started.gathering,research:started.research};expect(m.research!.job).toEqual({kind,remainingSeconds:12});expect(decodeSave(encodeSave(m,view)).ok).toBe(true);expect(startResearch(m.gathering,m.research!,m.placement,kind).research).toBe(m.research);m.research=updateResearch(m.research!,m.placement,11.9);expect(m.research[kind]??0).toBe(0);m.research=updateResearch(m.research,m.placement,.1);expect(m.research[kind]).toBe(1);expect(canResearch(m.gathering,m.research,m.placement,kind)).toBe(false);expect(decodeSave(encodeSave(m,view)).ok).toBe(true);}expect(createMatch('skirmish').research).not.toMatchObject({cavalryArmor:1});});
it('missing/dead producer blocks/cancels the job without refund and keeps completed bonuses',()=>{const m=ready();m.placement.stable!.construction.remainingSeconds=1;expect(canResearch(m.gathering,m.research!,m.placement,'cavalryArmor')).toBe(false);m.placement.stable!.construction.remainingSeconds=0;const started=startResearch(m.gathering,m.research!,m.placement,'cavalryArmor');m.placement.stable!.hp=0;expect(updateResearch(started.research,m.placement,12).job).toBeNull();expect(started.gathering.wood).toBe(955);expect(cavalryArmorMultiplier('worker',1)).toBe(1);expect(cavalryArmorMultiplier('archer',1)).toBe(1);expect(cavalryArmorMultiplier('cavalry',2)).toBe(.8);expect(trainedHealerMana('specialist',1)).toBe(0);expect(scoutDetectorRadius('air',1)).toBe(0);expect(scoutDetectorRadius('scout',1)).toBe(128);});
it('armor stacks once with ordinary defense, applies to existing cavalry symmetrically and leaves workers unchanged',()=>{let m=updateCavalryProduction(trainCavalry(ready()),12);const u=m.gathering.units.at(-1)!;if(u.kind!=='soldier')throw Error('cavalry');u.position={x:400,y:300};u.target={...u.position};u.autoDisabled=true;const enemy={id:'e',kind:'unit' as const,role:'cavalry' as const,hp:110,position:{x:428,y:300},order:{kind:'defend' as const,targetId:u.id}},combat={baseHP:240,enemies:[enemy]};const plain=updateCombat({...m.gathering,units:[u]},combat,1),armor=updateCombat({...m.gathering,units:[u]},{...combat,upgrades:{attack:0,defense:1,cavalryArmor:1}},1);expect(u.hp!-armor.gathering.units[0].hp!).toBeCloseTo((u.hp!-plain.gathering.units[0].hp!)*.75*.8);const attacked={...u,autoDisabled:false,order:{kind:'attack' as const,enemyId:'e'}};const a=updateCombat({...m.gathering,units:[attacked]},combat,1),b=updateCombat({...m.gathering,units:[attacked]},{...combat,enemyUpgrades:{attack:0,defense:1,cavalryArmor:1}},1);expect(110-b.combat.enemies[0].hp).toBeCloseTo((110-a.combat.enemies[0].hp)*factions.clans.upgrades.defense.multiplier*.8);});
it('training changes only healer maximum, retains initial/regen and survives 150 mana save; AI research costs match',()=>{let m=updateHealerProduction(trainHealer(ready()),10);const h=m.gathering.units.at(-1)!;if(h.kind!=='soldier')throw Error('healer');expect(h.mana).toBe(50);m.research!.healerTraining=1;expect(manaFor(h,'crown',m.research)).toMatchObject({max:150,initial:50,regenerationPerSecond:1});m=advanceMana(m,100);expect(m.gathering.units.at(-1)).toMatchObject({mana:150});expect(decodeSave(encodeSave(m,view)).ok).toBe(true);const future=updateHealerProduction(trainHealer(m),10);expect(future.gathering.units.at(-1)).toMatchObject({archetype:'healer',mana:50});expect(manaFor(future.gathering.units.at(-1)!,'crown',future.research)?.max).toBe(150);const ai=ready(),base=ai.combat.enemies.find(e=>e.kind==='base')!;for(const kind of ['barracks','farm','forge','stable','academy','aviary','siegeWorks'] as const)ai.combat.enemies.push({...base,id:'enemy-'+kind,kind:'building',buildingType:kind,hp:factions.clans.buildings[kind].hp,construction:{remainingSeconds:0,builderId:null}});ai.enemyProduction!.baseDevelopment={level:3,remainingSeconds:null};ai.enemyPolicy!.research={attack:2,defense:2,job:null};ai.enemyProduction!.wood=100;ai.enemyProduction!.gold=100;ai.combat.enemies.push(...[1,2,3,4,5,6].map(i=>({id:'enemy-produced-'+i,kind:'unit' as const,role:'soldier' as const,hp:60,position:base.position})));delete ai.enemyRecovery;const r=prepareEnemyPolicy(ai);expect(r.enemyPolicy!.research.job).toEqual({kind:'cavalryArmor',remainingSeconds:12});expect(r.enemyProduction).toMatchObject({wood:55,gold:70});});
