import {saveConfig} from '../config/save';
import {scenarioConfig,scenarioWaves,enemyBaseConfig,type MatchScenario} from '../config/scenarios';
import {difficultyProfiles,type Difficulty} from '../config/difficulty';
import {gatheringConfig,goldConfig} from '../config/gathering';
import {combatConfig} from '../config/combat';
import {archerConfig} from '../config/archer';
import {catapultConfig} from '../config/catapult';
import {unitStats,combatUnitStats} from '../config/unit';
import {costs} from '../config/economy';
import {forgeConfig,upgradeConfig} from '../config/upgrades';
import {queueConfig,productionConfig,soldierProductionConfig} from '../config/production';
import {createMap,bodyFits} from './map';
import {placementObstacles,type Footprint} from './placement';
import {matchFog} from './matchFog';
import {updateMatch,type MatchState} from './match';
import type {Position} from './movement';
export interface SavedView {camera:Position;building:'base'|'barracks'|null}
export interface SaveDocument {schemaVersion:number;configVersion:string;map:'arena';state:MatchState;view:SavedView}
export type LoadResult={ok:true;match:MatchState;view:SavedView}|{ok:false;error:string};
type Data=Record<string,unknown>;
function ensure(test:unknown,label:string):asserts test {if(!test)throw new Error(`Ogiltig sparning: ${label}`);}
function r(value:unknown,label:string,keys:string[]):Data {ensure(value!==null&&typeof value==='object'&&!Array.isArray(value),label);const o=value as Data;ensure(Object.keys(o).every(k=>keys.includes(k)),`${label} fält`);return o;}
function arr(value:unknown,label:string,max=saveConfig.maxUnits):unknown[]{ensure(Array.isArray(value)&&value.length<=max,label);return value;}
function num(value:unknown,label:string,min=0,max=1e6):number {ensure(typeof value==='number'&&Number.isFinite(value)&&value>=min&&value<=max,label);return value;}
function integer(value:unknown,label:string,min=0,max=1e6):number{const n=num(value,label,min,max);ensure(Number.isInteger(n),label);return n;}
function text(value:unknown,label:string):string{ensure(typeof value==='string'&&value.length>0&&value.length<=128,label);return value;}
function choice(value:unknown,label:string,choices:readonly unknown[]){ensure(choices.includes(value),label);}
function bool(value:unknown,label:string){ensure(typeof value==='boolean',label);}
function optional(value:unknown,check:(v:unknown)=>unknown){if(value!==undefined)check(value);}
function position(value:unknown,label:string):Position{const o=r(value,label,['x','y']);return {x:num(o.x,label,0,1279.999999),y:num(o.y,label,0,959.999999)};}
function footprint(value:unknown,label:string):Footprint{const o=r(value,label,['x','y','width','height']),p=position({x:o.x,y:o.y},label),w=num(o.width,label,1,1280),h=num(o.height,label,1,960);ensure(p.x+w<=1280&&p.y+h<=960,label);return {...p,width:w,height:h};}
function samePosition(a:Position,b:Position){return a.x===b.x&&a.y===b.y;}
function sameFoot(a:Footprint,b:Footprint){return samePosition(a,b)&&a.width===b.width&&a.height===b.height;}
function construction(value:unknown,ids:Set<string>){const o=r(value,'construction',['remainingSeconds','builderId']);num(o.remainingSeconds,'construction time',0,5);ensure(o.builderId===null||typeof o.builderId==='string'&&ids.has(o.builderId),'builder ref');}
function production(value:unknown,allowed:readonly string[],duration?:number){
 const p=r(value,'production',['remainingSeconds','queue','nextJobNumber','rally','nextUnitNumber']);integer(p.nextUnitNumber,'next unit',1);optional(p.nextJobNumber,v=>integer(v,'next job',1));if(p.remainingSeconds!==null)num(p.remainingSeconds,'production time',0,10);optional(p.rally,v=>position(v,'rally'));
 if(p.queue!==undefined){const jobs=arr(p.queue,'queue',queueConfig.maxJobs),ids=new Set<string>();for(const value of jobs){const j=r(value,'job',['id','kind','supply','cost','durationSeconds','remainingSeconds']),id=text(j.id,'job id');ensure(!ids.has(id),'duplicate job');ids.add(id);choice(j.kind,'job kind',allowed);const type=j.kind as keyof typeof costs,cost=r(j.cost,'job cost',['wood','gold']);ensure(cost.wood===costs[type].wood&&cost.gold===costs[type].gold,'job cost/config');const expected=duration??(type==='archer'?archerConfig.durationSeconds:type==='catapult'?catapultConfig.durationSeconds:type==='worker'?productionConfig.durationSeconds:soldierProductionConfig.durationSeconds);ensure(j.durationSeconds===expected,'job duration/config');num(j.remainingSeconds,'job remaining',0,expected);optional(j.supply,v=>ensure(v===(type==='catapult'?2:1),'job supply'));}
 ensure(Number(p.nextJobNumber??1)>Math.max(0,...[...ids].map(id=>Number(id.split('-').at(-1)))),'job counter');
 ensure(jobs.length? p.remainingSeconds===(jobs[0] as Data).remainingSeconds:p.remainingSeconds===null,'head timer');}
 return p;
}
function checkTree(value:unknown){let nodes=0;function visit(v:unknown,depth:number){ensure(++nodes<=saveConfig.maxNodes&&depth<=30,'size/depth');if(typeof v==='number')ensure(Number.isFinite(v),'finite number');if(v&&typeof v==='object')for(const [k,x] of Object.entries(v)){ensure(!['__proto__','constructor','prototype'].includes(k),'unsafe key');visit(x,depth+1);}}visit(value,0);}
/** Validate before any mutation; then derive physical obstacles and current vision from live state. */
export function decodeSave(json:string):LoadResult {
 try{
  ensure(json.length<=saveConfig.maxBytes&&new TextEncoder().encode(json).byteLength<=saveConfig.maxBytes,'size');const raw:unknown=JSON.parse(json);checkTree(raw);
  const doc=r(raw,'document',['schemaVersion','configVersion','map','state','view']);ensure(doc.schemaVersion===saveConfig.schemaVersion,'schema version (ingen migration stöds)');ensure(doc.configVersion===saveConfig.configVersion,'config version');ensure(doc.map==='arena','map');
  const s=r(doc.state,'match',['map','gathering','combat','placement','production','soldierProduction','waves','outcome','paused','research','scenario','difficulty','enemyProduction','enemyAI','fog','controlGroups']);
  choice(s.scenario,'scenario',Object.keys(scenarioConfig));choice(s.difficulty,'difficulty',['easy','normal','hard']);choice(s.outcome,'outcome',['playing','victory','defeat']);bool(s.paused,'pause');const scenario=s.scenario as MatchScenario,difficulty=s.difficulty as Difficulty,profile=difficultyProfiles[difficulty];
  const map=r(s.map,'world',['width','height','tileSize','revision','obstacles']);ensure(map.width===1280&&map.height===960&&map.tileSize===32,'world config');integer(map.revision,'revision');const obstacleValues=arr(map.obstacles,'obstacles',128).map(o=>footprint(o,'obstacle'));
  const g=r(s.gathering,'economy',['units','node','gold','goldBalance','base','wood','lostCargo']);num(g.wood,'wood',0,400+scenarioConfig[scenario].initial.wood);num(g.goldBalance,'gold',0,300+scenarioConfig[scenario].initial.gold);ensure(samePosition(position(g.base,'base'),gatheringConfig.basePosition),'base position');
  const nodes=new Set<string>();for(const [value,id,type,expected,initial] of [[g.node,'wood-1','wood',gatheringConfig.nodePosition,400],[g.gold,'gold-1','gold',goldConfig.position,300]] as const){const n=r(value,'node',['id','resource','position','remaining']);ensure(n.id===id&&n.resource===type,'resource ID/type');ensure(samePosition(position(n.position,'node'),expected),'node position');num(n.remaining,'remaining',0,initial);nodes.add(id);}
  optional(g.lostCargo,v=>{const lost=r(v,'lost cargo',['wood','gold']);num(lost.wood,'lost wood');num(lost.gold,'lost gold');});
  const units=arr(g.units,'units'),ownIds=new Set<string>(),workerIds=new Set<string>();for(const value of units){const u=r(value,'unit',['id','kind','owner','hp','position','target','selected','order','cargo','cargoType','archetype','attackCooldown','autoOrigin','attackMoveTarget','autoDisabled']),id=text(u.id,'unit id');ensure(/^unit-[1-9]\d*$/.test(id)&&!ownIds.has(id),'unit ID');ownIds.add(id);choice(u.kind,'unit kind',['worker','soldier']);ensure(u.owner==='player','owner');position(u.position,'unit position');position(u.target,'unit target');bool(u.selected,'selected');optional(u.autoOrigin,v=>position(v,'auto origin'));optional(u.attackMoveTarget,v=>position(v,'attack-move'));optional(u.autoDisabled,v=>bool(v,'auto disabled'));optional(u.attackCooldown,v=>num(v,'cooldown',0,2));
   const order=r(u.order,'order',['kind','enemyId','nodeId','buildingId']);if(u.kind==='worker'){workerIds.add(id);ensure(u.archetype===undefined,'worker archetype');num(u.hp,'worker HP',Number.MIN_VALUE,combatConfig.workerHP);num(u.cargo,'cargo',0,gatheringConfig.capacity);optional(u.cargoType,v=>choice(v,'cargo type',['wood','gold']));choice(order.kind,'worker order',['idle','move','gather','deliver','build']);if(order.kind==='gather'||order.kind==='deliver')ensure(typeof order.nodeId==='string'&&nodes.has(order.nodeId),'node ref');}
   else{optional(u.archetype,v=>choice(v,'archetype',['archer','catapult']));num(u.hp,'combat HP',Number.MIN_VALUE,u.archetype==='archer'?archerConfig.hp:u.archetype==='catapult'?catapultConfig.hp:combatConfig.soldierHP);ensure(u.cargo===0&&u.cargoType===undefined,'combat cargo');choice(order.kind,'combat order',['idle','move','attack']);if(order.kind==='attack')text(order.enemyId,'attack ref');}
  }
  const c=r(s.combat,'combat',['baseOwner','baseHP','enemies','projectiles','nextProjectileNumber','upgrades']);ensure(c.baseOwner==='player','base owner');num(c.baseHP,'base HP',0,combatConfig.baseHP);
  const enemies=arr(c.enemies,'enemies'),enemyIds=new Set<string>();for(const value of enemies){const e=r(value,'enemy',['owner','kind','order','id','position','hp','footprint']),id=text(e.id,'enemy id');ensure(!ownIds.has(id)&&!enemyIds.has(id),'duplicate enemy');enemyIds.add(id);ensure(e.owner==='enemy','enemy owner');optional(e.kind,v=>choice(v,'enemy kind',['unit','base']));position(e.position,'enemy position');num(e.hp,'enemy HP',Number.MIN_VALUE,e.kind==='base'?enemyBaseConfig.hp:combatConfig.enemyHP);if(e.kind==='base'){ensure(id===enemyBaseConfig.id&&sameFoot(footprint(e.footprint,'enemy base'),enemyBaseConfig.footprint),'enemy base config');ensure(samePosition(position(e.position,'enemy base center'),{x:1008,y:144}),'enemy base center');}else ensure(e.footprint===undefined,'enemy unit footprint');if(e.order!==undefined){const o=r(e.order,'enemy order',['kind','targetId','destination']);choice(o.kind,'enemy order kind',['idle','defend','muster','attack-move']);if(o.kind==='defend')text(o.targetId,'defend ref');if(o.kind==='muster'||o.kind==='attack-move')position(o.destination,'enemy goal');}}
  const p=r(s.placement,'placement',['kind','farms','forge','nextFarmNumber','construction','active','barracks','barracksOwner','barracksHP']);bool(p.active,'placement active');optional(p.kind,v=>choice(v,'placement kind',['barracks','farm','forge']));optional(p.nextFarmNumber,v=>integer(v,'next farm',1));const buildingIds=new Set<string>();
  if(p.barracks!==null){const f=footprint(p.barracks,'barracks');ensure(f.width===64&&f.height===64&&f.x%32===0&&f.y%32===0,'barracks footprint');ensure(p.barracksOwner==='player','barracks owner');num(p.barracksHP,'barracks HP',Number.MIN_VALUE,combatConfig.barracksHP);construction(p.construction,workerIds);buildingIds.add('barracks');}
  for(const value of arr(p.farms,'farms',3)){const f=r(value,'farm',['id','owner','hp','footprint','construction']),id=text(f.id,'farm id');ensure(/^farm-[1-9]\d*$/.test(id)&&!buildingIds.has(id),'farm ID');buildingIds.add(id);ensure(f.owner==='player','farm owner');num(f.hp,'farm HP',Number.MIN_VALUE,combatConfig.farmHP);const rect=footprint(f.footprint,'farm footprint');ensure(rect.width===64&&rect.height===64&&rect.x%32===0&&rect.y%32===0,'farm size/grid');construction(f.construction,workerIds);}
  if(p.forge!==undefined){const f=r(p.forge,'forge',['id','owner','hp','footprint','construction']);ensure(f.id==='forge'&&f.owner==='player','forge ID/owner');num(f.hp,'forge HP',Number.MIN_VALUE,forgeConfig.hp);const rect=footprint(f.footprint,'forge footprint');ensure(rect.width===64&&rect.height===64&&rect.x%32===0&&rect.y%32===0,'forge size/grid');construction(f.construction,workerIds);buildingIds.add('forge');}
  ensure(Number(p.nextFarmNumber??1)>Math.max(0,...[...buildingIds].filter(id=>id.startsWith('farm-')).map(id=>Number(id.slice(5)))),'farm counter');
  for(const value of units){const u=value as Data,o=u.order as Data;if(o.kind==='attack')ensure(enemyIds.has(o.enemyId as string),'broken attack ID');if(o.kind==='build')ensure(buildingIds.has(o.buildingId as string),'broken building ID');}
  const targets=new Set([...ownIds,...buildingIds,...(Number(c.baseHP)>0?['base']:[])]);for(const e of enemies){const o=(e as Data).order as Data|undefined;if(o?.kind==='defend')ensure(targets.has(o.targetId as string),'broken defender target');}
  const prod=production(s.production,['worker']),army=production(s.soldierProduction,['soldier','archer','catapult']);const maxOwn=Math.max(0,...[...ownIds].map(id=>Number(id.slice(5))));ensure(Number(prod.nextUnitNumber)>maxOwn&&Number(army.nextUnitNumber)>maxOwn,'unit counter');
  const waves=r(s.waves,'waves',['elapsedSeconds','nextWave','nextEnemyNumber']);num(waves.elapsedSeconds,'match time',0,86400);integer(waves.nextWave,'wave index',0,scenarioWaves(scenario,difficulty).length);integer(waves.nextEnemyNumber,'wave counter',1);ensure(Number(waves.nextEnemyNumber)>Math.max(0,...[...enemyIds].filter(id=>/^enemy-\d+$/.test(id)).map(id=>Number(id.slice(6)))),'enemy counter');
  const research=r(s.research,'research',['attack','defense','job']);integer(research.attack,'attack level',0,1);integer(research.defense,'defense level',0,1);if(research.job!==null){const j=r(research.job,'research job',['kind','remainingSeconds']);choice(j.kind,'research kind',['attack','defense']);num(j.remainingSeconds,'research time',Number.MIN_VALUE,upgradeConfig.durationSeconds);ensure(p.forge!==undefined&&Number(c.baseHP)>0,'research building');}
  optional(c.upgrades,v=>{const u=r(v,'upgrades',['attack','defense']);integer(u.attack,'combat upgrade',0,1);integer(u.defense,'combat upgrade',0,1);});
  optional(c.nextProjectileNumber,v=>integer(v,'next projectile',1));const shotIds=new Set<string>();for(const value of arr(c.projectiles??[],'projectiles',256)){const x=r(value,'projectile',['id','shooterId','targetId','position','destination','splashRadius','targetFootprint','speed','remainingLife','damage','hitRadius']),id=text(x.id,'shot ID');ensure(!shotIds.has(id),'duplicate projectile');shotIds.add(id);text(x.targetId,'historical projectile target');optional(x.shooterId,v=>text(v,'historical shooter'));position(x.position,'shot position');position(x.destination,'shot destination');num(x.speed,'shot speed',1,1000);num(x.remainingLife,'shot lifetime',Number.MIN_VALUE,3);num(x.damage,'shot damage',0,1000);num(x.hitRadius,'shot radius',0,100);optional(x.splashRadius,v=>num(v,'splash',1,100));optional(x.targetFootprint,v=>footprint(v,'shot footprint'));}
  ensure(Number(c.nextProjectileNumber??1)>Math.max(0,...[...shotIds].filter(id=>/^arrow-\d+$/.test(id)).map(id=>Number(id.slice(6)))),'projectile counter');
  if(s.enemyProduction!==undefined){ensure(scenarioConfig[scenario].enemyBase,'unexpected enemy production');const e=r(s.enemyProduction,'enemy production',['wood','gold','cap','production','acceptedJobs','durationSeconds']);num(e.wood,'enemy wood',0,profile.budget.wood);num(e.gold,'enemy gold',0,profile.budget.gold);ensure(e.cap===profile.cap,'enemy cap');integer(e.acceptedJobs,'enemy accepted');optional(e.durationSeconds,v=>ensure(v===profile.durationSeconds,'enemy duration'));const ep=production(e.production,['soldier'],profile.durationSeconds);ensure(Number(ep.nextUnitNumber)>Math.max(0,...[...enemyIds].filter(id=>/^enemy-produced-\d+$/.test(id)).map(id=>Number(id.slice(15)))),'enemy production counter');}
  if(s.enemyAI!==undefined){const ai=r(s.enemyAI,'AI',['reserve','defenders','threatId','elapsedSeconds','nextGroupNumber','groups','lastDispatchSeconds']);num(ai.elapsedSeconds,'AI time',0,86400);integer(ai.nextGroupNumber,'group counter',1);if(ai.lastDispatchSeconds!==null)num(ai.lastDispatchSeconds,'dispatch time',0,Number(ai.elapsedSeconds));ensure(ai.threatId===null||ownIds.has(ai.threatId as string),'threat ref');const groups=arr(ai.groups,'groups'),groupIds=new Set<string>();for(const value of groups){const group=r(value,'group',['id','status','members','destinations','startedAt','dispatchedAt']),id=text(group.id,'group ID');ensure(!groupIds.has(id),'duplicate group');groupIds.add(id);choice(group.status,'group status',['muster','ready','attack']);num(group.startedAt,'group time',0,Number(ai.elapsedSeconds));optional(group.dispatchedAt,v=>num(v,'group dispatch',0,Number(ai.elapsedSeconds)));for(const id of arr(group.members,'group members'))ensure(enemyIds.has(id as string),'group member ref');const dest=r(group.destinations,'group destinations',[...enemyIds]);for(const v of Object.values(dest))position(v,'group goal');}ensure(Number(ai.nextGroupNumber)>Math.max(0,...[...groupIds].map(id=>Number(id.split('-').at(-1)))),'group counter');for(const id of arr(ai.reserve,'reserve'))ensure(enemyIds.has(id as string),'reserve ref');for(const value of arr(ai.defenders,'defenders')){const d=r(value,'defender',['id','groupId','destination']);ensure(enemyIds.has(d.id as string),'defender ID');optional(d.groupId,v=>ensure(groupIds.has(v as string),'defender group'));optional(d.destination,v=>position(v,'defender goal'));}}
  const fog=r(s.fog,'fog',['width','height','tileSize','columns','rows','teams']);ensure(fog.width===1280&&fog.height===960&&fog.tileSize===32&&fog.columns===40&&fog.rows===30,'fog shape');const teams=r(fog.teams,'teams',['player','enemy']);for(const key of ['player','enemy']){const team=r(teams[key],'fog team',['visible','explored']);for(const field of ['visible','explored']){const flags=arr(team[field],'fog flags',1200);ensure(flags.length===1200&&flags.every(v=>typeof v==='boolean'),'fog cells');}ensure((team.visible as boolean[]).every((v,i)=>!v||(team.explored as boolean[])[i]),'visible implies explored');}
  optional(s.controlGroups,v=>{const groups=r(v,'control groups',['1','2','3','4','5','6','7','8','9']);for(const ids of Object.values(groups)){const a=arr(ids,'control refs');ensure(new Set(a).size===a.length&&a.every(id=>ownIds.has(id as string)),'control group ID');}});
  const view=r(doc.view,'view',['camera','building']),camera=position(view.camera,'camera');ensure(camera.x<=480&&camera.y<=360,'camera bounds');choice(view.building,'building selection',[null,'base','barracks']);
  const state=s as unknown as MatchState,expected=[...createMap().obstacles,...placementObstacles(state.gathering).slice(Number(c.baseHP)>0?0:1),...(state.placement.barracks?[state.placement.barracks]:[]),...(state.placement.farms??[]).map(f=>f.footprint),...(state.placement.forge?[state.placement.forge.footprint]:[]),...state.combat.enemies.filter(e=>e.kind==='base').map(e=>e.footprint!)];
  const footKey=(f:Footprint)=>`${f.x},${f.y},${f.width},${f.height}`;ensure(JSON.stringify(obstacleValues.map(footKey).sort())===JSON.stringify(expected.map(footKey).sort()),'physical obstacle refs');
  state.map={...state.map,obstacles:obstacleValues};for(const u of state.gathering.units)ensure(bodyFits(state.map,u.position,(u.kind==='worker'?unitStats.size:combatUnitStats(u).size)/2),'unit clearance');for(const e of state.combat.enemies)if(e.kind!=='base')ensure(bodyFits(state.map,e.position,combatConfig.enemySize/2),'enemy clearance');
  ensure(updateMatch({...state,paused:false,outcome:'playing'},0).outcome===state.outcome,'outcome/objective');
  ensure(view.building===null||view.building==='base'&&Number(c.baseHP)>0||view.building==='barracks'&&buildingIds.has('barracks'),'selected building ref');
  state.placement={...state.placement,active:false};state.fog=matchFog(state);
  return {ok:true,match:state,view:{camera,building:view.building as SavedView['building']}};
 }catch(error){return {ok:false,error:error instanceof Error?error.message:'Sparningen kunde inte läsas'};}
}
export function encodeSave(state:MatchState,view:SavedView):string{
 const json=JSON.stringify({schemaVersion:saveConfig.schemaVersion,configVersion:saveConfig.configVersion,map:'arena',state,view},(key,value)=>['navigation','blockedSpawnKey','rallyError','bodyHalf','destroyedEnemyFootprints'].includes(key)?undefined:value);
 const result=decodeSave(json);if(!result.ok)throw new Error(result.error);return json;
}
export interface SaveStorage {getItem(key:string):string|null;setItem(key:string,value:string):void}
export function storeSave(storage:SaveStorage|(()=>SaveStorage),state:MatchState,view:SavedView):{ok:boolean;error?:string}{try{const target=typeof storage==='function'?storage():storage;target.setItem(saveConfig.key,encodeSave(state,view));return {ok:true};}catch(e){return {ok:false,error:e instanceof Error?e.message:'Lagring ej tillgänglig'};}}
export function readSave(storage:SaveStorage|(()=>SaveStorage)):LoadResult{try{const target=typeof storage==='function'?storage():storage;const json=target.getItem(saveConfig.key);return json===null?{ok:false,error:'Ingen lokal sparning finns'}:decodeSave(json);}catch{return {ok:false,error:'Lokal lagring kunde inte läsas'};}}
