import {describe,it,expect} from 'vitest';
import {createMatch,updateMatch} from './match';
import {encodeSave,decodeSave,storeSave,readSave,type SavedView} from './save';
import {enqueueProduction} from './productionQueue';
import {placeBuilding,beginPlacement,placementObstacles} from './placement';
import {orderUnits} from './gathering';
import {saveConfig} from '../config/save';
const view:SavedView={camera:{x:240,y:180},building:null};
function roundtrip(m:ReturnType<typeof createMatch>){const json=encodeSave(m,view),result=decodeSave(json);expect(result.ok,result.ok?'':result.error).toBe(true);if(!result.ok)throw Error(result.error);return result.match;}
function withoutCache(m:unknown){return JSON.parse(JSON.stringify(m,(key,value)=>['navigation','blockedSpawnKey','rallyError','bodyHalf','destroyedEnemyFootprints'].includes(key)?undefined:value));}
describe('validated local snapshots',()=>{
 it.each(['survival','skirmish','mission-waves','mission-base','mission-outpost'] as const)('roundtrips every %s difficulty and independent arrays without wall-time',scenario=>{for(const difficulty of ['beginner','easy','normal','hard'] as const){const m=createMatch(scenario,difficulty),copy=roundtrip(m);expect(copy).toEqual(withoutCache(m));copy.gathering.units[0]!.position.x+=1;expect(m.gathering.units[0]!.position.x).toBe(280);expect(copy.waves.elapsedSeconds).toBe(0);}});
 it('preserves cargo/delivery/order, fog, groups, production reservation and actual construction mid-progress',()=>{
  let m=createMatch();m.gathering.wood=100;m.gathering.goldBalance=30;m.gathering.units[2]!.selected=true;
  const placed=placeBuilding(beginPlacement(m.placement),{x:512,y:384},m.gathering.wood,placementObstacles(m.gathering),{map:m.map,gathering:m.gathering,enemies:[]});if(!('gathering' in placed)||!placed.gathering||!placed.map)throw Error('fixture placement');m={...m,placement:placed.placement,gathering:placed.gathering,map:placed.map};
  const q=enqueueProduction(m.gathering,m.production,{kind:'base'});m={...m,gathering:q.gathering,production:q.production};m=updateMatch(m,3);m.controlGroups={'1':['unit-3']};m.gathering.units[0]={...m.gathering.units[0]!,kind:'worker',cargo:3,cargoType:'wood',order:{kind:'deliver',nodeId:'wood-1'}};m.paused=true;
  const copy=roundtrip(m);expect(copy.placement.construction).toEqual(m.placement.construction);expect(copy.production.queue).toEqual(m.production.queue);expect(copy.gathering.units[0]!.cargo).toBe(3);expect(copy.controlGroups).toEqual(m.controlGroups);expect(copy.fog).toEqual(m.fog);expect(updateMatch(copy,999)).toBe(copy);
 });
 it('replans movement from a stripped cache and neither teleports nor pays/spawns twice',()=>{let m=createMatch();m.gathering.wood=40;m.gathering.units[0]!.selected=true;m.gathering.units=orderUnits(m.gathering.units,{x:500,y:320});const queued=enqueueProduction(m.gathering,m.production,{kind:'base'});m={...m,gathering:queued.gathering,production:queued.production};m=updateMatch(m,1);const copy=roundtrip(m);expect(Object.keys(copy.fog!).sort()).toEqual(['columns','height','rows','teams','tileSize','width']);expect(copy.gathering.units[0]!.navigation).toBeUndefined();expect(copy.gathering.units[0]!.position).toEqual(m.gathering.units[0]!.position);const finished=updateMatch(copy,4);expect(finished.gathering.units).toHaveLength(4);expect(finished.gathering.wood).toBe(20);expect(updateMatch(finished,.1).gathering.units).toHaveLength(4);});
 it('preserves mid-flight projectiles, historical dead target/shooter IDs and enemy budget/group/research state',()=>{let m=createMatch('skirmish');m=updateMatch(m,20);m.combat.projectiles=[{id:'arrow-1',shooterId:'unit-99',targetId:'dead-target',position:{x:850,y:144},destination:{x:950,y:144},speed:180,remainingLife:2,damage:24,hitRadius:0,splashRadius:48}];m.combat.nextProjectileNumber=2;m.research!.attack=1;m.combat.upgrades={attack:1,defense:0};const c=roundtrip(m);expect(c.combat.projectiles).toEqual(m.combat.projectiles);expect(c.enemyProduction).toEqual(withoutCache(m.enemyProduction));expect(c.enemyAI).toEqual(withoutCache(m.enemyAI));expect(c.research).toEqual(m.research);});
 it('roundtrips an active upgrade and completed farm supply without restarting or double-paying research',()=>{let m=createMatch();const forge={x:608,y:384,width:64,height:64},farm={x:704,y:384,width:64,height:64};m.placement.forge={id:'forge',owner:'player',hp:120,footprint:forge,construction:{remainingSeconds:0,builderId:null}};m.placement.farms=[{id:'farm-1',owner:'player',hp:80,footprint:farm,construction:{remainingSeconds:0,builderId:null}}];m.placement.nextFarmNumber=2;m.map.obstacles.push(forge,farm);m.research!.job={kind:'defense',remainingSeconds:3};m=updateMatch(m,0);const copy=roundtrip(m);expect(copy.placement.farms).toEqual(m.placement.farms);expect(copy.research!.job!.remainingSeconds).toBe(3);const done=updateMatch(copy,3);expect(done.research!.defense).toBe(1);expect(done.research!.job).toBeNull();expect(done.gathering.wood).toBe(0);});
 it('restores an observed siege projectile once with the same damage as uninterrupted simulation',()=>{let m=createMatch('skirmish');m.gathering.units[0]!.position={x:840,y:144};m.combat.projectiles=[{id:'arrow-1',shooterId:'unit-99',targetId:'enemy-base',targetFootprint:{x:960,y:96,width:96,height:96},position:{x:910,y:144},destination:{x:1008,y:144},speed:180,remainingLife:2,damage:24,hitRadius:0,splashRadius:48}];m.combat.nextProjectileNumber=2;m=updateMatch(m,0);const loaded=roundtrip(m),expected=updateMatch(m,.6),actual=updateMatch(loaded,.6);expect(actual.combat.enemies.find(e=>e.id==='enemy-base')!.hp).toBe(216);expect(actual.combat.enemies.find(e=>e.id==='enemy-base')!.hp).toBe(expected.combat.enemies.find(e=>e.id==='enemy-base')!.hp);expect(actual.combat.projectiles).toEqual([]);expect(updateMatch(actual,.1).combat.enemies.find(e=>e.id==='enemy-base')!.hp).toBe(216);});
 it('roundtrips ended outcomes and never resurrects a dead base or enemy-base obstacle',()=>{let m=createMatch('skirmish');m.combat.enemies[0]!.hp=0;m=updateMatch(m,0);expect(roundtrip(m).outcome).toBe('victory');m=createMatch();m.combat.baseHP=0;m=updateMatch(m,0);const c=roundtrip(m);expect(c.outcome).toBe('defeat');expect(c.map.obstacles).toEqual(m.map.obstacles);});
 it.each([['future version',(d:any)=>d.schemaVersion=saveConfig.schemaVersion+1],['old version',(d:any)=>d.schemaVersion=0],['config version',(d:any)=>d.configVersion='future'],['negative cargo',(d:any)=>d.state.gathering.units[0].cargo=-1],['missing order',(d:any)=>delete d.state.gathering.units[0].order],['duplicate ID',(d:any)=>d.state.gathering.units[1].id='unit-1'],['broken node',(d:any)=>d.state.gathering.units[0].order={kind:'gather',nodeId:'no-node'}],['counter',(d:any)=>d.state.production.nextUnitNumber=1],['false outcome',(d:any)=>d.state.outcome='victory'],['bad fog',(d:any)=>d.state.fog.teams.enemy.explored.pop()],['map mismatch',(d:any)=>d.state.map.obstacles=[]],['unsafe field',(d:any)=>d.state.gathering.units[0].constructor={bad:true}]])('atomically rejects %s',(_label,mutate)=>{const m=createMatch(),before=JSON.stringify(m),doc=JSON.parse(encodeSave(m,view));mutate(doc);expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);expect(JSON.stringify(m)).toBe(before);});
 it('rejects malformed/oversized JSON and broken combat references',()=>{expect(decodeSave('{')).toMatchObject({ok:false});expect(decodeSave(' '.repeat(saveConfig.maxBytes+1)).ok).toBe(false);const doc=JSON.parse(encodeSave(createMatch(),view));doc.state.gathering.units[0]={...doc.state.gathering.units[0],kind:'soldier',hp:60,cargo:0,order:{kind:'attack',enemyId:'missing'}};expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);});
 it('handles absent saves and quota/access failures without changing old slot or active match',()=>{let old:string|null=null;const storage={getItem:()=>old,setItem:(_key:string,value:string)=>{old=value;}};const m=createMatch();expect(readSave(storage)).toMatchObject({ok:false});expect(storeSave(storage,m,view).ok).toBe(true);expect(readSave(storage).ok).toBe(true);const before=old;expect(storeSave({...storage,setItem:()=>{throw Error('quota');}},m,view)).toMatchObject({ok:false,error:'quota'});expect(old).toBe(before);expect(readSave({...storage,getItem:()=>{throw Error('denied');}})).toMatchObject({ok:false});expect(storeSave(()=>{throw Error('access');},m,view)).toMatchObject({ok:false,error:'access'});expect(readSave(()=>{throw Error('access');})).toMatchObject({ok:false});});
});
