import {trainFlyer,updateFlightProduction} from './flightProduction';
import {it,expect} from 'vitest';
import {factionIds,factions,factionsForPlayer} from '../config/factions';
import {createMatch,updateMatch} from './match';
import {enqueueProduction,updateQueuedProduction} from './productionQueue';
import {autoScout,setScoutRoute,prepareScouting,autoScoutGoal} from './scouting';
import {issueOrder} from './commandOrders';
import {stopSelected} from './orders';
import {encodeSave,decodeSave} from './save';
import {visionObservers} from './matchFog';
import {canAttackDomain,movementMap} from './domains';
import {bodyFits} from './map';
const view={camera:{x:0,y:0},building:null};
function ready(id= 'crown' as typeof factionIds[number]){let m=createMatch('skirmish','normal',factionsForPlayer(id));m.gathering.wood=300;m.gathering.goldBalance=300;m.combat.baseDevelopment={level:2,remainingSeconds:null};m.placement.aviary={id:'aviary',owner:'player',hp:150,footprint:{x:512,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null},production:{remainingSeconds:null,nextUnitNumber:4}};m.map.obstacles.push(m.placement.aviary.footprint);m=updateFlightProduction(trainFlyer(m,'scout'),6);m.gathering.units.forEach(u=>u.selected=u.kind==='soldier');return m;}
it.each(factionIds)('%s trains before heavy air, has owner vision, no attacks and saves route/auto',id=>{let m=ready(id);const u=m.gathering.units.at(-1)!;expect(u).toMatchObject({archetype:'scout',hp:35,faction:id});expect(m.gathering.wood).toBe(275);expect(m.gathering.goldBalance).toBe(285);expect(visionObservers(m).find(o=>o.id===u.id)).toMatchObject({radius:288,airborne:true});expect(canAttackDomain(u,{kind:'unit'},id)).toBe(false);m=setScoutRoute(m,[{x:600,y:400},{x:700,y:480},{x:550,y:500}]);expect(decodeSave(encodeSave(m,view)).ok).toBe(true);m=autoScout(m);expect(decodeSave(encodeSave(m,view)).ok).toBe(true);expect(createMatch('skirmish').gathering.units.some(u=>u.kind==='soldier'&&u.archetype==='scout')).toBe(false);});
it('loops multiple waypoints over obstacles and valid manual orders cancel the route',()=>{let m=ready();const p=m.map.obstacles[0],points=[{x:p.x+p.width/2,y:p.y+p.height/2},{x:650,y:420},{x:580,y:500}];m=setScoutRoute(m,points);const seen=new Set<number>();for(let i=0;i<200;i++){m=updateMatch(m,.1);const u=m.gathering.units.at(-1)!;if(u.kind!=='soldier')throw Error('scout');seen.add(u.scouting!.index);expect(bodyFits(movementMap(m.map,u),u.position,11)).toBe(true);}expect([...seen].sort()).toEqual([0,1,2]);expect(setScoutRoute(m,[{x:0,y:0},{x:500,y:400}])).toBe(m);m=issueOrder(m,{kind:'move',destination:{x:600,y:450}});expect(m.gathering.units.at(-1)).toMatchObject({order:{kind:'move'},scouting:undefined});m=autoScout(m);expect(stopSelected(m.gathering.units,true).at(-1)).toMatchObject({scouting:undefined,order:{kind:'idle'}});});
it('uses only explored bits, throttles automatic replanning, rejects malformed saved routes',()=>{let m=ready();const a=autoScoutGoal(m,{x:400,y:300},'player');const hidden={...m,combat:{...m.combat,enemies:[]}};expect(autoScoutGoal(hidden,{x:400,y:300},'player')).toEqual(a);m=prepareScouting(autoScout(m));let u=m.gathering.units.at(-1)!;if(u.kind!=='soldier')throw Error('scout');expect(u.scouting!.nextPlanSeconds).toBe(5);u.position={...u.scouting!.waypoints[0]};u.target={...u.position};m.waves.elapsedSeconds=1;expect(prepareScouting(m).gathering.units.at(-1)).toMatchObject({scouting:{nextPlanSeconds:5}});const saved=JSON.parse(encodeSave(m,view));saved.state.gathering.units.at(-1).scouting.waypoints=[{x:-1,y:400}];expect(decodeSave(JSON.stringify(saved)).ok).toBe(false);});
it('AI scouts pay the same six seconds and are routed independently of combat groups',async()=>{const {updateEnemyProduction}=await import('./enemyProduction');const m=ready(),base=m.combat.enemies.find(e=>e.kind==='base')!,site={...base,id:'enemy-aviary',kind:'building' as const,buildingType:'aviary' as const,construction:{remainingSeconds:0,builderId:null}};const r=updateEnemyProduction({...m.enemyProduction!,roster:true,acceptedJobs:8,wood:25,gold:15}, {...m.combat,enemies:[base,site]},m.gathering,m.map,6,'crown',{site,technology:{baseLevel:2,buildings:['base','aviary'],research:{}},population:{cap:8,used:0,reserved:0}});expect(r.state.wood).toBe(0);expect(r.state.gold).toBe(0);expect(r.combat.enemies.find(e=>e.role==='scout')).toMatchObject({hp:35,scouting:{mode:'auto'}});const routed=prepareScouting({...m,combat:r.combat});expect(routed.combat.enemies.find(e=>e.role==='scout')!.order?.kind).toBe('muster');});
it('Barracks rejects both flyer recipes; dedicated flight queue reserves supply and disappears on destruction',async()=>{const {cleanDestroyed}=await import('./destruction');let m=ready();const b={kind:'barracks' as const,footprint:m.placement.aviary!.footprint,technology:{baseLevel:2,buildings:['base','barracks','aviary','forge'] as const,research:{attack:1,defense:1}}};for(const role of ['air','scout'] as const)expect(enqueueProduction(m.gathering,m.soldierProduction,{...b,unitType:role}).production).toBe(m.soldierProduction);m=trainFlyer(m,'scout');expect(m.placement.aviary!.production.queue).toHaveLength(1);expect(decodeSave(encodeSave(m,view)).ok).toBe(true);m.placement.aviary!.hp=0;m=cleanDestroyed(m);expect(m.placement.aviary).toBeUndefined();expect(m.map.obstacles.some(o=>o.x===512&&o.y===384)).toBe(false);});
