import {describe,it,expect} from 'vitest';
import {factions,factionIds,factionsForPlayer} from '../config/factions';
import {createMatch} from './match';
import {siegeBuilding,trainSiege,updateSiegeProduction} from './siegeProduction';
import {enqueueProduction} from './productionQueue';
import {matchPopulation} from './navy';
import {encodeSave,decodeSave} from './save';
import {cleanDestroyed} from './destruction';
import {rangedStats} from '../config/unit';
import {canAttackDomain} from './domains';
import {updateCombat} from './combat';
import {actionPanel} from '../presentation/actionPanel';
const view={camera:{x:0,y:0},building:null};
function ready(id:typeof factionIds[number]='crown'){const m=createMatch('skirmish','normal',factionsForPlayer(id));m.gathering.wood=400;m.gathering.goldBalance=400;m.combat.baseDevelopment={level:2,remainingSeconds:null};m.placement.forge={id:'forge',owner:'player',hp:factions[id].buildings.forge.hp,footprint:{x:640,y:352,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};m.placement.siegeWorks={id:'siegeWorks',owner:'player',hp:180,footprint:{x:512,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null},production:{remainingSeconds:null,nextUnitNumber:4}};m.placement.farms=[{id:'farm-1',owner:'player',hp:factions[id].buildings.farm.hp,footprint:{x:640,y:448,width:64,height:64},construction:{remainingSeconds:0,builderId:null}}];m.placement.nextFarmNumber=2;m.map.obstacles.push(m.placement.forge.footprint,m.placement.siegeWorks.footprint,m.placement.farms[0].footprint);return m;}
describe('dedicated siege works',()=>{
 it.each(factionIds)('%s queues both paid siege roles only at the works, saves FIFO and produces distinct live units',id=>{let m=ready(id);const f=factions[id],c=f.units.catapult,b=f.units.ballista;expect(enqueueProduction(m.gathering,m.soldierProduction,{...siegeBuilding(m),producer:'barracks'}).gathering).toBe(m.gathering);expect(actionPanel(m,'barracks',true)['train-catapult'].visible).toBe(false);expect(actionPanel(m,'siegeWorks',true)['train-ballista'].visible).toBe(true);m=trainSiege(trainSiege(m,'catapult'),'ballista');expect(m.gathering.wood).toBe(400-c.cost.wood-b.cost.wood);expect(matchPopulation(m).reserved).toBe(c.supply+b.supply);const saved=decodeSave(encodeSave(m,view));expect(saved).toMatchObject({ok:true});if(!saved.ok)throw Error(saved.error);m=updateSiegeProduction(saved.match,c.durationSeconds+b.durationSeconds);expect(m.gathering.units.map(u=>u.kind==='soldier'?u.archetype:undefined)).toEqual([undefined,undefined,undefined,'catapult','ballista']);expect(new Set(m.gathering.units.map(u=>u.id)).size).toBe(5);expect(decodeSave(encodeSave(m,view))).toMatchObject({ok:true});expect(createMatch().placement.siegeWorks).toBeUndefined();});
 it('requires completed works, Forge, tier II and supply; destruction clears queue and collision',()=>{let m=ready();m.placement.siegeWorks!.construction.remainingSeconds=1;expect(trainSiege(m,'ballista').gathering).toBe(m.gathering);m.placement.siegeWorks!.construction.remainingSeconds=0;m.combat.baseDevelopment!.level=1;expect(trainSiege(m,'ballista').gathering).toBe(m.gathering);m.combat.baseDevelopment!.level=2;m.placement.forge!.hp=0;expect(trainSiege(m,'ballista').gathering).toBe(m.gathering);m=ready();m=trainSiege(m,'ballista');m.placement.siegeWorks!.hp=0;m=cleanDestroyed(m);expect(m.placement.siegeWorks).toBeUndefined();expect(matchPopulation(m).reserved).toBe(0);expect(m.map.obstacles).not.toContainEqual({x:512,y:384,width:64,height:64});});
 it('ballista fires a direct land-only projectile with double building damage, symmetrically',()=>{const m=updateSiegeProduction(trainSiege(ready(),'ballista'),16),u=m.gathering.units.at(-1)!;if(u.kind!=='soldier')throw Error('ballista');expect(rangedStats(u)).not.toHaveProperty('splashRadius');expect(canAttackDomain(u,{kind:'ship'},'crown')).toBe(false);expect(canAttackDomain(u,{role:'air'},'crown')).toBe(false);const unit={...u,position:{x:400,y:300},target:{x:400,y:300},order:{kind:'attack' as const,enemyId:'enemy-forge'}};const combat={baseHP:240,enemies:[{id:'enemy-forge',kind:'building' as const,buildingType:'forge' as const,hp:1000,position:{x:500,y:300},footprint:{x:468,y:268,width:64,height:64},order:{kind:'idle' as const}}]};const hit=updateCombat({...m.gathering,units:[unit]},combat,.5);expect(1000-hit.combat.enemies[0].hp).toBe(44);const enemy={id:'enemy-produced-1',kind:'unit' as const,role:'ballista' as const,hp:90,owner:'enemy' as const,position:{x:400,y:300},order:{kind:'defend' as const,targetId:'forge'}};const placement={...m.placement,forge:{...m.placement.forge!,hp:1000,footprint:{x:468,y:268,width:64,height:64}}};const opposing=updateCombat({...m.gathering,units:[]},{baseHP:240,enemies:[enemy]},.5,undefined,placement);expect(1000-opposing.placement!.forge!.hp).toBe(44);});
 it('migrates old Barracks catapult jobs with one validated full refund and keeps existing units',()=>{const m=ready();delete m.placement.siegeWorks;m.map.obstacles=m.map.obstacles.filter(o=>o.x!==512||o.y!==384);const r=factions.crown.units.catapult;m.soldierProduction={...m.soldierProduction,nextJobNumber:2,remainingSeconds:r.durationSeconds,queue:[{id:'barracks-job-1',kind:'catapult',supply:r.supply,cost:r.cost,durationSeconds:r.durationSeconds,remainingSeconds:r.durationSeconds}]};m.gathering.wood-=r.cost.wood;m.gathering.goldBalance!-=r.cost.gold;const doc=JSON.parse(encodeSave(m,view));doc.configVersion='tribute-config-66';const migrated=decodeSave(JSON.stringify(doc));expect(migrated).toMatchObject({ok:true});if(!migrated.ok)throw Error(migrated.error);expect(migrated.match.gathering.wood).toBe(400);expect(migrated.match.soldierProduction.queue).toEqual([]);expect(decodeSave(encodeSave(migrated.match,view))).toMatchObject({ok:true});doc.state.soldierProduction.queue[0].cost.wood++;expect(decodeSave(JSON.stringify(doc)).ok).toBe(false);});
});
