import {expect,it} from 'vitest';
import {createMatch} from './match';
import {matchFog} from './matchFog';
import {castSpell,advanceSpells,spellModifiers,spellTargetReason,selectedSpellCaster} from './spells';
import {decodeSave,encodeSave} from './save';
import {updateCombat} from './combat';
import {actionPanel} from '../presentation/actionPanel';
import type {Soldier} from './gathering';
const unit=(id:string,x:number,hp:number,archetype?:'specialist'):Soldier=>({id,kind:'soldier',owner:'player',hp,archetype,cargo:0,selected:!!archetype,position:{x,y:300},target:{x,y:300},order:{kind:'idle'},...(archetype?{mana:60}:{})});
function fixture(){const m=createMatch('skirmish');m.gathering.units.push(unit('unit-4',400,100,'specialist'),unit('unit-5',460,20));m.production.nextUnitNumber=6;m.soldierProduction.nextUnitNumber=6;m.combat.enemies.push({id:'enemy-produced-1',owner:'enemy',kind:'unit',role:'soldier',hp:66,position:{x:520,y:300},order:{kind:'idle'}});m.enemyProduction!.production.nextUnitNumber=2;m.enemyProduction!.acceptedJobs=1;m.fog=matchFog(m);return m;}
it('heal caps at max HP, pays once and preserves orders/selection; cooldown prevents repeat',()=>{const m=fixture(),result=castSpell(m,'unit-4','heal','unit-5');expect(result.reason).toBeNull();expect(result.match.gathering.units[4]).toMatchObject({hp:45,order:{kind:'idle'},selected:false});expect(result.match.gathering.units[3]).toMatchObject({mana:40,spellCooldowns:{heal:6},selected:true});const repeat=castSpell(result.match,'unit-4','heal','unit-5');expect(repeat.match).toBe(result.match);expect(repeat.reason).toMatch(/Cooldown/);const healed=castSpell(advanceSpells(result.match,6),'unit-4','heal','unit-5').match;expect(healed.gathering.units[4].hp).toBe(60);});
it('ward and hex change combat, not just labels, and expire on gameplay time',()=>{let m=fixture();m=castSpell(m,'unit-4','ward','unit-5').match;m=castSpell(m,'unit-4','hex','enemy-produced-1').match;expect(spellModifiers(m.gathering.units[4] as Soldier).defense).toBe(.75);expect(spellModifiers(m.combat.enemies.at(-1)!).attack).toBe(.75);const tick=advanceSpells(m,5);expect(tick.combat.enemies.at(-1)!.spellEffects).toEqual([]);expect((tick.gathering.units[4] as Soldier).spellEffects).toMatchObject([{remainingSeconds:1}]);expect(advanceSpells(tick,1).gathering.units[4]).toMatchObject({spellEffects:[]});expect(advanceSpells({...m,paused:true},10)).toMatchObject({gathering:m.gathering});
 const victim=m.gathering.units[4] as Soldier;m.gathering.units=[victim];m.combat.enemies=[{...m.combat.enemies.at(-1)!,position:{x:480,y:300},order:{kind:'defend',targetId:'unit-5'}}];const fight=updateCombat(m.gathering,m.combat,1,m.map,m.placement);expect(fight.gathering.units[0].hp).toBeCloseTo(20-20*.75*.75);
});
it.each(['unknown','enemy-produced-1','unit-1','base'])('rejects invalid heal target %s without mutation, mana or cooldown',id=>{const m=fixture(),result=castSpell(m,'unit-4','heal',id);expect(result.reason).toBeTruthy();expect(result.match).toBe(m);expect(m.gathering.units[3]).toMatchObject({mana:60});expect(m.gathering.units[3]).not.toHaveProperty('spellCooldowns');});
it('validates living caster, resources, owner, current fog, range, full HP and target still alive',()=>{let m=fixture();expect(castSpell(m,'enemy-produced-1','heal','unit-5').match).toBe(m);expect(castSpell(m,'unit-4','hex','unit-5').match).toBe(m);m.gathering.units[4].hp=60;expect(spellTargetReason(m,'unit-4','heal','unit-5')).toBe('Target at full HP');m.gathering.units[4].hp=0;expect(castSpell(m,'unit-4','heal','unit-5').match).toBe(m);m.gathering.units[4].hp=20;m.gathering.units[4].position.x=700;m.fog=matchFog(m);expect(spellTargetReason(m,'unit-4','heal','unit-5')).toMatch(/range/);m.gathering.units[4].position.x=460;(m.gathering.units[3] as Soldier).mana=19;expect(spellTargetReason(m,'unit-4','heal','unit-5')).toBe('Needs 20 mana');(m.gathering.units[3] as Soldier).mana=60;const enemy=m.combat.enemies.at(-1)!;enemy.position={x:1200,y:800};m.fog=matchFog(m);expect(spellTargetReason(m,'unit-4','hex',enemy.id)).toMatch(/vision/);(m.gathering.units[3] as Soldier).hp=0;expect(castSpell(m,'unit-4','ward','unit-5').match).toBe(m);});
it('reapplication replaces the buff channel rather than multiplying it; ready selected caster wins over exhausted caster',()=>{let m=fixture();m=castSpell(m,'unit-4','ward','unit-5').match;m=advanceSpells(m,8);m.gathering.units.push({...unit('unit-6',420,100,'specialist'),mana:100});m.gathering.units[3]={...m.gathering.units[3],mana:0} as Soldier;expect(selectedSpellCaster(m,'ward')!.id).toBe('unit-6');m=castSpell(m,'unit-6','ward','unit-5').match;(m.gathering.units[5] as Soldier).spellCooldowns={};m=castSpell(m,'unit-6','ward','unit-5').match;expect((m.gathering.units[4] as Soldier).spellEffects).toHaveLength(1);expect(spellModifiers(m.gathering.units[4] as Soldier).defense).toBe(.75);});
it('saves effects/cooldowns and rejects malformed duration, duplicate channels, foreign keys and worker effects',()=>{let m=fixture();m=castSpell(m,'unit-4','ward','unit-5').match;m=castSpell(m,'unit-4','hex','enemy-produced-1').match;const json=encodeSave(m,{camera:{x:0,y:0},building:null}),loaded=decodeSave(json);expect(loaded.ok,loaded.ok?'':loaded.error).toBe(true);if(loaded.ok){expect(loaded.match.gathering.units[3]).toMatchObject({mana:15,spellCooldowns:{ward:8,hex:8}});expect(loaded.match.combat.enemies.at(-1)).toMatchObject({spellEffects:[{spell:'hex',remainingSeconds:5}]});}
 for(const mutate of [(d:any)=>d.state.gathering.units[4].spellEffects[0].remainingSeconds=7,(d:any)=>d.state.gathering.units[4].spellEffects.push(d.state.gathering.units[4].spellEffects[0]),(d:any)=>d.state.gathering.units[3].spellCooldowns.hack=1,(d:any)=>d.state.gathering.units[0].spellEffects=d.state.gathering.units[4].spellEffects]){const d=JSON.parse(json);mutate(d);expect(decodeSave(JSON.stringify(d)).ok).toBe(false);}
});
it('explains mana, range, cooldown and unavailable caster in UI while keeping worker build actions',()=>{const m=fixture();m.gathering.units[0].selected=true;expect(actionPanel(m,null,true)['cast-heal']).toMatchObject({visible:true,reason:'',cost:expect.stringContaining('20 mana · Range 160px · Cooldown 6s')});(m.gathering.units[3] as Soldier).mana=0;expect(actionPanel(m,null,true)['cast-heal'].reason).toBe('Needs 20 mana');expect(actionPanel(m,null,true)['build-gate'].visible).toBe(true);expect(actionPanel(m,null,false)['cast-heal'].reason).toBe('Match is paused or ended');});
