import {battleEnemies} from './bosses';
import {hasMainBase} from './extraBases';
import {campaignActionReason} from '../config/campaignContent';
import {towerTargets} from '../config/domains';
import {targetDomain,isAir} from './domains';
import {fortificationSafety} from './gates';
import {defenseConfig,towerSpecializations} from '../config/defenses';import {canAfford,payCost} from './economy';import {placementVisible,entityVisible} from './visibility';import {buildingFootprint,placementPreviewError,placementError,placementObstacles} from './placement';import {replaceObstacles} from './map';import {canReachFootprint} from './approach';import {updateSite} from './construction';import {prerequisiteReason,technologyFor} from './productionPrerequisites';import {factionForTeam} from '../config/factions';import type {MatchState} from './match';import type {Position} from './movement';import type {PlacementState,Footprint,ConstructionJob} from './placement';import type {Enemy} from './combat';import type {Projectile} from './projectiles';
export type TowerSpecialization='ground'|'air';
export interface Defense {specialization?:TowerSpecialization;readyAfter?:number;upgradeAfter?:number;id:`tower-${number}`|`wall-${number}`|`gate-${number}`;open?:boolean;kind:'tower'|'wall'|'gate';owner:'player';footprint:Footprint;hp:number;construction:ConstructionJob;level:1|2;upgradeRemaining:number|null;cooldown:number}
export function towerUpgradeReason(m:MatchState,id:string):string|null{const locked=campaignActionReason(m,'upgrade-tower');if(locked)return locked;const t=m.placement.defenses?.find(t=>t.id===id&&t.kind==='tower');return !t||t.hp<=0?'Tower missing':m.paused||m.outcome!=='playing'||!!m.multiplePlayers&&!hasMainBase(m)?'Match is paused or ended':t.construction.remainingSeconds>0?'Construction unfinished':t.level===2?'Permanent specialization already selected':t.upgradeRemaining!==null?'Upgrade in progress':prerequisiteReason(factionForTeam(m,'player'),{baseLevel:2,buildings:['forge'],research:{attack:1}},technologyFor(m,'player'))??(!canAfford(m.gathering,defenseConfig.upgrade.cost)?'Not enough wood or gold':null);}
export function upgradeTower(m:MatchState,id:string,specialization:TowerSpecialization='ground'):MatchState{if(towerUpgradeReason(m,id))return m;return {...m,gathering:payCost(m.gathering,defenseConfig.upgrade.cost),placement:{...m.placement,defenses:m.placement.defenses!.map(t=>t.id===id?{...t,specialization,upgradeRemaining:defenseConfig.upgrade.seconds}:t)}};}
function checkTowerPlacement(m:MatchState,p:Position,preview=false):string|null{const kind=m.placement.kind==='wall'||m.placement.kind==='gate'?m.placement.kind:'tower',cfg=defenseConfig[kind],rect=buildingFootprint(p,kind),worker=m.gathering.units.find(u=>u.kind==='worker'&&u.selected);if(m.paused||m.outcome!=='playing'||!!m.multiplePlayers&&!hasMainBase(m))return 'Match is paused or ended';if(!worker)return 'Select a worker';if(!m.fog||!placementVisible(m.fog,rect))return 'The site must be visible';if((m.placement.defenses?.length??0)>=32)return 'Fortification limit reached';if(!canAfford(m.gathering,cfg.cost))return 'Not enough wood or gold';return (preview?placementPreviewError:placementError)({...m.placement,kind},p,m.gathering.wood,placementObstacles(m.gathering),{map:m.map,gathering:m.gathering,enemies:battleEnemies(m),technology:technologyFor(m,'player')})??(preview?null:fortificationSafety(m,rect,kind==='gate')??(!canReachFootprint(m.map,worker.position,rect,24)?'Builder cannot reach site':null));}
export const towerPlacementError=(m:MatchState,p:Position)=>checkTowerPlacement(m,p);
export const towerPreviewError=(m:MatchState,p:Position)=>checkTowerPlacement(m,p,true);
export function placeTower(m:MatchState,p:Position):MatchState{if(!m.placement.active||towerPlacementError(m,p))return m;const kind=m.placement.kind==='wall'||m.placement.kind==='gate'?m.placement.kind:'tower',cfg=defenseConfig[kind],rect=buildingFootprint(p,kind),n=m.placement.nextDefenseNumber??1,id=`${kind}-${n}` as const,worker=m.gathering.units.find(u=>u.kind==='worker'&&u.selected)!;return {...m,map:replaceObstacles(m.map,[...m.map.obstacles,rect]),gathering:{...payCost(m.gathering,cfg.cost),units:m.gathering.units.map(u=>u.id===worker.id&&u.kind==='worker'?{...u,commandMode:undefined,orderQueue:undefined,navigation:undefined,order:{kind:'build' as const,buildingId:id}}:u)},placement:{...m.placement,active:false,nextDefenseNumber:n+1,defenses:[...(m.placement.defenses??[]).map(t=>t.kind==='wall'&&t.construction.builderId===worker.id?{...t,construction:{...t.construction,builderId:null}}:t),{id,kind,...(kind==='gate'?{open:false}:{}),owner:'player',footprint:rect,hp:cfg.hp,construction:{remainingSeconds:cfg.seconds,builderId:worker.id},level:1,upgradeRemaining:null,cooldown:0}]}};}
export function updateTowers(m:MatchState,delta:number):MatchState{let g=m.gathering;const completedBuilders=new Set<string>();const defenses=m.placement.defenses?.map(t=>{const result=updateSite(g,t.construction,t.footprint,t.id,m.map,delta);g=result.gathering;if(t.kind==='wall'&&result.completedAfterSeconds!==undefined&&t.construction.builderId)completedBuilders.add(t.construction.builderId);const remaining=t.upgradeRemaining===null?null:Math.max(0,t.upgradeRemaining-delta)<1e-9?0:Math.max(0,t.upgradeRemaining-delta);return {...t,readyAfter:t.construction.remainingSeconds>0?(result.completedAfterSeconds??delta):0,upgradeAfter:t.upgradeRemaining!==null&&remaining===0?t.upgradeRemaining:undefined,construction:result.job,level:remaining===0?2 as const:t.level,upgradeRemaining:remaining===0?null:remaining};});// Advance only after completion, once per step; stopped/dead builders never restart.
for(const id of completedBuilders){const site=defenses?.find(t=>t.kind==='wall'&&t.hp>0&&t.construction.remainingSeconds>0&&t.construction.builderId===id);if(site)g={...g,units:g.units.map(u=>u.id===id&&u.kind==='worker'&&u.order.kind==='idle'?{...u,navigation:undefined,order:{kind:'build' as const,buildingId:site.id}}:u)};}return defenses?{...m,gathering:g,placement:{...m.placement,defenses}}:m;}
/** Nearest visible hostile unit, stable ID tie-break; fixed aim, existing collision/impact. */
export function towerShots(p:PlacementState|undefined,enemies:Enemy[],delta:number,next:number,visible:(e:Enemy)=>boolean){const shots:{projectile:Projectile;time:number}[]=[];const defenses=p?.defenses?.map(t=>{if(t.kind!=='tower'||t.hp<=0||t.construction.remainingSeconds>0||t.upgradeRemaining!==null)return t;const cfg=t.level===2?towerSpecializations[t.specialization??'ground']:{...defenseConfig.tower,targets:towerTargets},pos={x:t.footprint.x+16,y:t.footprint.y-1},distance=(e:Enemy)=>Math.hypot(e.position.x-(t.footprint.x+16),e.position.y-(t.footprint.y+16));const target=enemies.filter(e=>e.hp>0&&!e.footprint&&visible(e)&&cfg.targets.some(d=>d===targetDomain(e))&&distance(e)<=cfg.range).sort((a,b)=>distance(a)-distance(b)||a.id.localeCompare(b.id))[0];if(!target)return {...t,cooldown:Math.max(0,t.cooldown-delta)};let time=(t.readyAfter??0)+t.cooldown;if(t.upgradeAfter!==undefined)time=Math.max(time,t.upgradeAfter);while(time<delta-1e-9){shots.push({projectile:{bossProfile:'projectile' as const,targets:cfg.targets,...(isAir(target)?{airborne:true as const}:{}),id:`tower-shot-${next++}`,shooterId:t.id,shooterFootprint:t.footprint,targetId:target.id,position:pos,destination:{...target.position},speed:defenseConfig.tower.speed,remainingLife:2,damage:cfg.damage,hitRadius:16},time:delta-time});time+=defenseConfig.tower.interval;}return {...t,cooldown:Math.max(0,time-delta)};});return {shots,next,placement:p&&defenses?{...p,defenses}:p};}
