import {battleEnemies} from './bosses';
import {hasMainBase} from './extraBases';
import {campaignActionReason} from '../config/campaignContent';
import {towerTargets} from '../config/domains';
import {isAir} from './domains';
import {fortificationSafety} from './gates';
import {defenseConfig} from '../config/defenses';import {canAfford,payCost} from './economy';import {placementVisible,entityVisible} from './visibility';import {buildingFootprint,placementPreviewError,placementError,placementObstacles} from './placement';import {replaceObstacles} from './map';import {approachRoute} from './approach';import {updateSite} from './construction';import {prerequisiteReason,technologyFor} from './productionPrerequisites';import {factionForTeam} from '../config/factions';import type {MatchState} from './match';import type {Position} from './movement';import type {PlacementState,Footprint,ConstructionJob} from './placement';import type {Enemy} from './combat';import type {Projectile} from './projectiles';
export interface Defense {readyAfter?:number;upgradeAfter?:number;id:`tower-${number}`|`wall-${number}`|`gate-${number}`;open?:boolean;kind:'tower'|'wall'|'gate';owner:'player';footprint:Footprint;hp:number;construction:ConstructionJob;level:1|2;upgradeRemaining:number|null;cooldown:number}
export function towerUpgradeReason(m:MatchState,id:string):string|null{const locked=campaignActionReason(m,'upgrade-tower');if(locked)return locked;const t=m.placement.defenses?.find(t=>t.id===id&&t.kind==='tower');return !t||t.hp<=0?'Tower missing':m.paused||m.outcome!=='playing'||!!m.multiplePlayers&&!hasMainBase(m)?'Match is paused or ended':t.construction.remainingSeconds>0?'Construction unfinished':t.level===2?'Maximum tower level':t.upgradeRemaining!==null?'Upgrade in progress':prerequisiteReason(factionForTeam(m,'player'),{baseLevel:2,buildings:['forge']},technologyFor(m,'player'))??(!canAfford(m.gathering,defenseConfig.upgrade.cost)?'Not enough wood or gold':null);}
export function upgradeTower(m:MatchState,id:string):MatchState{if(towerUpgradeReason(m,id))return m;return {...m,gathering:payCost(m.gathering,defenseConfig.upgrade.cost),placement:{...m.placement,defenses:m.placement.defenses!.map(t=>t.id===id?{...t,upgradeRemaining:defenseConfig.upgrade.seconds}:t)}};}
function checkTowerPlacement(m:MatchState,p:Position,preview=false):string|null{const kind=m.placement.kind==='wall'||m.placement.kind==='gate'?m.placement.kind:'tower',cfg=defenseConfig[kind],rect=buildingFootprint(p,kind),worker=m.gathering.units.find(u=>u.kind==='worker'&&u.selected);if(m.paused||m.outcome!=='playing'||!!m.multiplePlayers&&!hasMainBase(m))return 'Match is paused or ended';if(!worker)return 'Select a worker';if(!m.fog||!placementVisible(m.fog,rect))return 'The site must be visible';if((m.placement.defenses?.length??0)>=32)return 'Fortification limit reached';if(!canAfford(m.gathering,cfg.cost))return 'Not enough wood or gold';return (preview?placementPreviewError:placementError)({...m.placement,kind},p,m.gathering.wood,placementObstacles(m.gathering),{map:m.map,gathering:m.gathering,enemies:battleEnemies(m),technology:technologyFor(m,'player')})??(preview?null:fortificationSafety(m,rect,kind==='gate')??(approachRoute(m.map,worker.position,rect,24).status==='blocked'?'Builder cannot reach site':null));}
export const towerPlacementError=(m:MatchState,p:Position)=>checkTowerPlacement(m,p);
export const towerPreviewError=(m:MatchState,p:Position)=>checkTowerPlacement(m,p,true);
export function placeTower(m:MatchState,p:Position):MatchState{if(!m.placement.active||towerPlacementError(m,p))return m;const kind=m.placement.kind==='wall'||m.placement.kind==='gate'?m.placement.kind:'tower',cfg=defenseConfig[kind],rect=buildingFootprint(p,kind),n=m.placement.nextDefenseNumber??1,id=`${kind}-${n}` as const,worker=m.gathering.units.find(u=>u.kind==='worker'&&u.selected)!;return {...m,map:replaceObstacles(m.map,[...m.map.obstacles,rect]),gathering:{...payCost(m.gathering,cfg.cost),units:m.gathering.units.map(u=>u.id===worker.id&&u.kind==='worker'?{...u,navigation:undefined,order:{kind:'build' as const,buildingId:id}}:u)},placement:{...m.placement,active:false,nextDefenseNumber:n+1,defenses:[...(m.placement.defenses??[]),{id,kind,...(kind==='gate'?{open:false}:{}),owner:'player',footprint:rect,hp:cfg.hp,construction:{remainingSeconds:cfg.seconds,builderId:worker.id},level:1,upgradeRemaining:null,cooldown:0}]}};}
export function updateTowers(m:MatchState,delta:number):MatchState{let g=m.gathering;const defenses=m.placement.defenses?.map(t=>{const result=updateSite(g,t.construction,t.footprint,t.id,m.map,delta);g=result.gathering;const remaining=t.upgradeRemaining===null?null:Math.max(0,t.upgradeRemaining-delta);return {...t,readyAfter:t.construction.remainingSeconds>0?(result.completedAfterSeconds??delta):0,upgradeAfter:t.upgradeRemaining!==null&&remaining===0?t.upgradeRemaining:undefined,construction:result.job,level:remaining===0?2 as const:t.level,upgradeRemaining:remaining===0?null:remaining};});return defenses?{...m,gathering:g,placement:{...m.placement,defenses}}:m;}
/** Nearest visible hostile unit, stable ID tie-break; fixed aim, existing collision/impact. */
export function towerShots(p:PlacementState|undefined,enemies:Enemy[],delta:number,next:number,visible:(e:Enemy)=>boolean){const shots:{projectile:Projectile;time:number}[]=[];const defenses=p?.defenses?.map(t=>{if(t.kind!=='tower'||t.hp<=0||t.construction.remainingSeconds>0)return t;const cfg=t.level===2?defenseConfig.upgrade:defenseConfig.tower,pos={x:t.footprint.x+16,y:t.footprint.y-1},distance=(e:Enemy)=>Math.hypot(e.position.x-(t.footprint.x+16),e.position.y-(t.footprint.y+16));const target=enemies.filter(e=>e.hp>0&&!e.footprint&&visible(e)&&distance(e)<=cfg.range).sort((a,b)=>distance(a)-distance(b)||a.id.localeCompare(b.id))[0];if(!target)return {...t,cooldown:Math.max(0,t.cooldown-delta)};let time=(t.readyAfter??0)+t.cooldown;if(t.upgradeAfter!==undefined&&distance(target)>defenseConfig.tower.range)time=Math.max(time,t.upgradeAfter);while(time<delta-1e-9){shots.push({projectile:{targets:towerTargets,...(isAir(target)?{airborne:true as const}:{}),id:`tower-shot-${next++}`,shooterId:t.id,shooterFootprint:t.footprint,targetId:target.id,position:pos,destination:{...target.position},speed:defenseConfig.tower.speed,remainingLife:2,damage:t.upgradeAfter!==undefined&&time<t.upgradeAfter?defenseConfig.tower.damage:cfg.damage,hitRadius:16},time:delta-time});time+=defenseConfig.tower.interval;}return {...t,cooldown:Math.max(0,time-delta)};});return {shots,next,placement:p&&defenses?{...p,defenses}:p};}
