import {expect,it} from 'vitest';
import {trafficGates,type TrafficBody} from './traffic';
import {advanceRoute,planRoute} from './navigation';
import {bodyFits,type WorldMap} from './map';
const map:WorldMap={width:512,height:256,tileSize:32,revision:0,obstacles:[{x:0,y:64,width:128,height:128},{x:160,y:64,width:352,height:128}]};
function fixture(){return [{id:'a',position:{x:144,y:40},destination:{x:144,y:216}},{id:'b',position:{x:144,y:216},destination:{x:144,y:40}}].map(b=>({...b,half:12,speed:80,active:true,route:planRoute(map,b.position,b.destination,12)}));}
it('admits one of opposing entrants and both eventually pass without terrain crossing or lost commands',()=>{let bodies=fixture();let simultaneous=0;for(let i=0;i<240;i++){const gates=trafficGates(map,bodies.map(b=>({...b,waypoints:b.route.waypoints})),i*.05,.05);bodies=bodies.map(b=>{const next=advanceRoute(map,b.position,b.route,b.speed,.05,gates(b.id));return {...b,position:next.position,route:next.route,active:next.route.status==='moving'};});simultaneous=Math.max(simultaneous,bodies.filter(b=>b.position.y>52&&b.position.y<204).length);expect(bodies.every(b=>bodyFits(map,b.position,b.half))).toBe(true);}expect(simultaneous).toBe(1);expect(bodies.every(b=>b.route.status==='arrived')).toBe(true);expect(bodies.map(b=>b.position)).toEqual(bodies.map(b=>b.destination));});
it('idle, dead/removed and redirected units do not retain a passage reservation',()=>{const [a,b]=fixture();const blocker:TrafficBody={...a,position:{x:144,y:100},active:false,waypoints:[]};let gate=trafficGates(map,[blocker,{...b,waypoints:b.route.waypoints}],0,2);expect(advanceRoute(map,b.position,b.route,b.speed,2,gate(b.id)).position.y).toBeLessThan(100);gate=trafficGates(map,[{...b,waypoints:b.route.waypoints}],0,2);expect(advanceRoute(map,b.position,b.route,b.speed,2,gate(b.id)).position.y).toBeLessThan(100);const away=planRoute(map,a.position,{x:220,y:40},12);gate=trafficGates(map,[{...a,waypoints:away.waypoints},{...b,waypoints:b.route.waypoints}],0,2);expect(advanceRoute(map,b.position,b.route,b.speed,2,gate(b.id)).position.y).toBeLessThan(100);});
it('reversing the input array preserves admission and a large delta cannot admit both entrants',()=>{const bodies=fixture(),run=(bs:typeof bodies)=>{const gates=trafficGates(map,bs.map(b=>({...b,waypoints:b.route.waypoints})),0,1);return Object.fromEntries(bs.map(b=>[b.id,advanceRoute(map,b.position,b.route,b.speed,1,gates(b.id)).position]));};expect(run(bodies)).toEqual(run([...bodies].reverse()));const p=Object.values(run(bodies));expect(p.filter(p=>p.y>52&&p.y<204)).toHaveLength(1);});
