import {legacyTerrainFixture} from './testHelpers/legacyTerrainFixture';
import {expect,it} from 'vitest';
import {createClassicMatch as createMatch} from './testHelpers/classicMatch';
import {updateMatch,type MatchState} from './match';
import {placeHarbor,trainShip,updateNavy,matchPopulation,commandShips,attackShips} from './navy';
import {loadTransport,unloadTransport} from './transport';
import {orderUnits,updateGathering} from './gathering';
import {cleanDestroyed} from './destruction';
import {encodeSave,decodeSave} from './save';
import {matchStats} from './matchStats';
import {matchFog} from './matchFog';
import {bodyFits,replaceObstacles} from './map';
const view={camera:{x:0,y:0},building:null};
function paid(){
 let m=createMatch('mission-outpost','easy');m.gathering.units=m.gathering.units.map(u=>({...u,selected:u.id==='unit-1'}));m.placement={...m.placement,active:true,kind:'harbor'};m=placeHarbor(m,{x:192,y:416});for(let i=0;i<200&&m.navy!.harbor!.construction.remainingSeconds>0;i++)m=updateMatch(m,.05);
 m.gathering.units=m.gathering.units.map(u=>({...u,selected:u.id!=='unit-3'}));m.gathering.units=orderUnits(m.gathering.units,m.gathering.node.position,m.gathering.node);m.gathering.units=m.gathering.units.map(u=>({...u,selected:u.id==='unit-3'}));m.gathering.units=orderUnits(m.gathering.units,m.gathering.gold!.position,m.gathering.gold!);m.gathering=updateGathering(m.gathering,120,m.map);
 const bank={wood:m.gathering.wood,gold:m.gathering.goldBalance!};m=trainShip(m,'transport');expect(m.gathering.wood).toBe(bank.wood-40);expect(m.gathering.goldBalance).toBe(bank.gold-10);expect(m.navy!.production.queue![0].kind).toBe('transport');expect(updateNavy(m,7.99).navy!.ships).toHaveLength(0);m=updateNavy(m,8);expect(m.navy!.ships[0]).toMatchObject({role:'transport',passengers:[],selected:false});
 return m;
}
function shore(){let m=paid();m.navy!.ships[0].selected=true;m.navy=commandShips(m,{x:208,y:512});m=updateNavy(m,2);
 // Walk actual workers to land contact, without teleporting them into a boat.
 m.gathering.units=m.gathering.units.map(u=>({...u,selected:u.id==='unit-1'}));m.gathering.units=orderUnits(m.gathering.units,{x:272,y:512});m.gathering=updateGathering(m.gathering,30,m.map);expect(m.gathering.units[0].position).toEqual({x:272,y:512});m.fog=matchFog(m);return m;}
it('paid transport shares FIFO/supply, cannot cannon-attack, and starts with an empty hold',()=>{let m=paid();expect(matchPopulation(m).used).toBe(5);m.navy!.ships[0].selected=true;expect(attackShips(m,'enemy-1')!.ships[0].order.kind).toBe('idle');const bank=m.gathering.wood;m=trainShip(m,'warship');expect(m.gathering.wood).toBe(bank-40);expect(m.navy!.production.queue![0].kind).toBe('warship');});
it('loading preserves ID/HP/cargo and supply while clearing ground orders, selection and groups',()=>{let m=shore();const unit=m.gathering.units[0],before=matchPopulation(m),stats=matchStats(m);m.controlGroups={'1':[unit.id,'ship-1']};m=loadTransport(m,'ship-1');expect(m.gathering.units).toHaveLength(2);expect(m.navy!.ships[0].passengers).toHaveLength(1);expect(m.navy!.ships[0].passengers![0]).toMatchObject({id:unit.id,hp:unit.hp,cargo:unit.cargo,selected:false,order:{kind:'idle'}});expect(matchPopulation(m)).toEqual(before);expect(matchStats(m)).toEqual(stats);expect(m.controlGroups).toEqual({'1':['ship-1']});m=updateMatch(m,.1);expect(m.navy!.ships[0].passengers![0].position).toEqual(unit.position);});
it('far/unselected/loading full/blocked contact leave units intact',()=>{let m=paid();expect(loadTransport(m,'ship-1')).toBe(m);m=shore();m.gathering.units[0].selected=false;expect(loadTransport(m,'ship-1')).toBe(m);m.gathering.units[0].selected=true;m.navy!.ships[0].passengers=Array.from({length:4},(_,i)=>({...m.gathering.units[1],id:`unit-${i+10}`,selected:false}));expect(loadTransport(m,'ship-1')).toBe(m);
 m=shore();m.map=replaceObstacles(m.map,[...m.map.obstacles,{x:248,y:490,width:8,height:64}]);expect(loadTransport(m,'ship-1')).toBe(m);});
it('valid landing restores the same unit to legal free land; water/far/occupied/hidden reject atomically',()=>{let m=loadTransport(shore(),'ship-1');const id=m.navy!.ships[0].passengers![0].id;expect(unloadTransport(m,'ship-1',{x:208,y:512})).toBe(m);expect(unloadTransport(m,'ship-1',{x:800,y:600})).toBe(m);const hidden=structuredClone(m);hidden.fog!.teams.player.visible.fill(false);expect(unloadTransport(hidden,'ship-1',{x:272,y:512})).toBe(hidden);const blocked={...m,map:replaceObstacles(m.map,[...m.map.obstacles,{x:224,y:480,width:96,height:96}])};expect(unloadTransport(blocked,'ship-1',{x:272,y:512})).toBe(blocked);
 const before=matchPopulation(m);m=unloadTransport(m,'ship-1',{x:272,y:512});expect(m.navy!.ships[0].passengers).toEqual([]);expect(m.gathering.units.find(u=>u.id===id)).toMatchObject({selected:false,order:{kind:'idle'}});expect(bodyFits(m.map,m.gathering.units.find(u=>u.id===id)!.position,8)).toBe(true);expect(matchPopulation(m)).toEqual(before);});
it('Save/load validates passengers identity and inactive orders; old12 migrates',()=>{const m=loadTransport(shore(),'ship-1'),json=encodeSave(m,view),loaded=decodeSave(json);expect(loaded.ok).toBe(true);if(loaded.ok){expect(loaded.match.navy!.ships[0].passengers).toEqual(m.navy!.ships[0].passengers);expect(matchPopulation(loaded.match)).toEqual(matchPopulation(m));}
 for(const change of [(d:any)=>d.state.navy.ships[0].passengers.push(d.state.gathering.units[0]),(d:any)=>d.state.navy.ships[0].passengers[0].selected=true,(d:any)=>d.state.navy.ships[0].role='warship',(d:any)=>d.configVersion='tribute-config-12']){const d=JSON.parse(json);change(d);expect(decodeSave(JSON.stringify(d)).ok).toBe(false);}const d=JSON.parse(encodeSave(createMatch(),view));legacyTerrainFixture(d);d.configVersion='tribute-config-12';delete d.state.statLedger;expect(decodeSave(JSON.stringify(d)).ok).toBe(true);});
it('sinking kills passengers, frees their supply, and accounts carried resources exactly once',()=>{let m=shore();const worker=m.gathering.units[0];if(worker.kind!=='worker')throw Error('worker fixture');m.gathering.units[0]={...worker,cargo:3,cargoType:'wood'};m=loadTransport(m,'ship-1');const before=matchPopulation(m).used;m.navy!.ships[0].hp=0;m=cleanDestroyed(m);expect(m.navy!.ships).toEqual([]);expect(m.gathering.units.some(u=>u.id==='unit-1')).toBe(false);expect(m.gathering.lostCargo!.wood).toBe(3);expect(matchPopulation(m).used).toBe(before-3);expect(cleanDestroyed(m).gathering.lostCargo!.wood).toBe(3);});
it('pause/gameover block load/unload and restart creates no passengers',()=>{let m=shore();for(const state of [{...m,paused:true},{...m,outcome:'defeat' as const}])expect(loadTransport(state,'ship-1')).toBe(state);m=loadTransport(m,'ship-1');for(const state of [{...m,paused:true},{...m,outcome:'victory' as const}])expect(unloadTransport(state,'ship-1',{x:272,y:512})).toBe(state);expect(createMatch().navy).toBeUndefined();});

it('capacity is four; multi-passenger landing preserves types and uses distinct land bodies',()=>{
 let m=shore();const w=m.gathering.units[0];if(w.kind!=='worker')throw Error('worker fixture');
 // Explicit identity/capacity fixture, independent of paid unit-production tests.
 m.gathering.units=Array.from({length:5},(_,i)=>({...w,id:`unit-${i+4}`,position:{x:240,y:512},selected:true}));m.production.nextUnitNumber=m.soldierProduction.nextUnitNumber=9;m=loadTransport(m,'ship-1');expect(m.navy!.ships[0].passengers).toHaveLength(4);expect(m.gathering.units).toHaveLength(1);
 m.gathering.units[0].position={x:400,y:300};m=unloadTransport(m,'ship-1',{x:272,y:512});expect(m.navy!.ships[0].passengers).toEqual([]);expect(m.gathering.units).toHaveLength(5);const bodies=m.gathering.units.slice(1).map(u=>({x:u.position.x-8,y:u.position.y-8,width:16,height:16}));for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++)expect(bodies[i].x+16<=bodies[j].x||bodies[j].x+16<=bodies[i].x||bodies[i].y+16<=bodies[j].y||bodies[j].y+16<=bodies[i].y).toBe(true);
});
it('loaded archer identity/HP is saved and it returns idle without a hidden attack order',()=>{
 let m=shore();m.gathering.units.push({id:'unit-4',kind:'soldier',owner:'player',archetype:'archer',hp:40,cargo:0,position:{x:272,y:512},target:{x:272,y:512},selected:true,order:{kind:'attack',enemyId:'historical'},attackMoveTarget:{x:700,y:500}});m.production.nextUnitNumber=m.soldierProduction.nextUnitNumber=5;m=loadTransport(m,'ship-1');expect(m.navy!.ships[0].passengers).toHaveLength(2);const saved=decodeSave(encodeSave(m,view));expect(saved.ok).toBe(true);if(saved.ok){m=unloadTransport(saved.match,'ship-1',{x:272,y:512});expect(m.gathering.units.find(u=>u.id==='unit-4')).toMatchObject({archetype:'archer',hp:40,order:{kind:'idle'},selected:false});}
});

it('a saved moving loaded carrier resumes its water route and keeps its passengers inactive',()=>{
 let m=loadTransport(shore(),'ship-1');m.navy=commandShips(m,{x:144,y:512});m=updateNavy(m,.1);m.fog=matchFog(m);const loaded=decodeSave(encodeSave(m,view));expect(loaded.ok).toBe(true);if(!loaded.ok)throw Error(loaded.error);const a=updateNavy(m,1),b=updateNavy(loaded.match,1);expect(b.navy!.ships[0].position).toEqual(a.navy!.ships[0].position);expect(b.navy!.ships[0].passengers).toEqual(a.navy!.ships[0].passengers);expect(b.gathering.units.map(u=>u.id)).toEqual(a.gathering.units.map(u=>u.id));expect(b.navy!.ships[0].passengers![0].selected).toBe(false);
});
