import {campaignPlans} from './campaignPhases';
import type {MatchFactions} from './factions';
import {maps} from './maps';
import {scenarioConfig} from './scenarios';

/** The existing playable missions, in order. New missions belong to RTS-143–145. */
export const campaignMissions=[
 {id:'first-steps',factions:{player:'crown',enemy:'clans'},scenario:'tutorial',briefing:'Command the Human garrison. Learn selection and movement, deliver wood, build Barracks and train a Guard. Right-click the practice target with your selected Guard; no enemy pressure while learning.',debriefing:'The garrison is ready. Forest Watch is now available.'},
 {id:'forest-watch',factions:{player:'clans',enemy:'crown'},scenario:'mission-waves',briefing:'The Orcs hold Forest Watch. Gather wood and gold, build a War Hut and train Axe Warriors before the three finite raider waves. Select your army and press E for Fury in close combat. Keep your Stronghold alive.',debriefing:'The watch holds. Take the fight to the enemy stronghold in The Siege.'},
 {id:'the-siege',factions:{player:'elves',enemy:'goblins'},scenario:'mission-base',briefing:'Elven Wardens must remove a Goblin stronghold. Deliver wood and gold, build a Ranger Lodge and enough supply for a larger army. Explore the northeast, use True Shot [E], and destroy the Workshop Hall. Longbows and Moon Workshop research are optional tactical choices.',debriefing:'The stronghold has fallen. Establish a defensive foothold in The Outpost.'},
 {id:'the-outpost',factions:{player:'dwarves',enemy:'goblins'},scenario:'mission-outpost',briefing:'The Dwarves hold the foothold for 90 gameplay seconds. Gather resources, build a Guard Hall and train Iron Guards before the incoming raiders. Brace [E] reduces incoming damage; keep the Stone Hold alive until reinforcements arrive.',debriefing:'The foothold is secure. The Crossing is now available.'},
 {id:'the-crossing',factions:{player:'goblins',enemy:'crown'},scenario:'mission-sea',briefing:'The Goblins secure the crossing. Pay for a Scrap Yard, supply, Scrappers, a Junk Dock and Junk Ferry. Load your army, sail across the channel and land. Defeat the Human Keep; use Overcharge [E] carefully, as it increases incoming damage too.',debriefing:'The crossing is secured. Escort the mountain courier in Ridge Convoy.'},
 {id:'ridge-convoy',factions:{player:'clans',enemy:'dwarves'},scenario:'mission-escort',briefing:'The Orcs escort Ridge Courier through Highland Crossroads. Train a paid escort, scout the central pass and defeat Pass Guard and Ridge Guard. Then move the courier into the marked safe zone (1504,544). Losing the courier or Stronghold ends the operation. The courier is a starting worker, not a trained reward.',debriefing:'The courier reached safety. Rescue the valley prisoners in Valley Rescue.'},
 {id:'valley-rescue',factions:{player:'elves',enemy:'clans'},scenario:'mission-rescue',briefing:'The Elves reach Frontier Valley. Train an army, cross the central dry river passage and defeat Camp Guard West and Camp Guard East. Bring a living combat unit to the marked camp (1088,640). Workers alone cannot complete the rescue. Keep the Grove Hall alive.',debriefing:'The camp is free. Secure the coastal banner in the final operation.'},
 {id:'coastal-banner',factions:{player:'crown',enemy:'dwarves'},scenario:'mission-capture',briefing:'The Human forces carry the allied banner across Shattered Coast. Pay for your army, supply, Harbor and Transport, then land on the eastern coast. Clear the Dwarf guards and keep a living land combat unit in the banner zone (1600,384) for 30 continuous seconds. Enemy combatants or your absence reset the timer; ships and workers cannot hold it.',debriefing:'The coastal banner stands. The eight-operation campaign reaches its conclusion; completed operations remain available for replay.'},
] as const;
export type CampaignMissionId=typeof campaignMissions[number]['id'];
export function campaignMission(id:unknown){return campaignMissions.find(m=>m.id===id);}
export function campaignMissionForScenario(scenario:unknown){return campaignMissions.find(m=>m.scenario===scenario);}
export function campaignDetails(id:CampaignMissionId){const m=campaignMission(id)!;const plan=campaignPlans[id];return {...m,...(plan?{briefing:`${plan.intro} Map: ${maps[plan.map].label}. ${plan.phases.map(p=>p.text).join(' ')} Keep your base alive.`,map:plan.map}:{}),title:scenarioConfig[m.scenario].label,goal:plan?.phases[0].text??scenarioConfig[m.scenario].instruction};}

/** Presets only constrain new campaign starts; loaded match factions remain authoritative. */
export function campaignPreset(id:unknown):MatchFactions|undefined {const mission=campaignMission(id);return mission&&'factions' in mission?{...mission.factions}:undefined;}
