import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core');
const browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE}),out='artifacts/rts-170',reports=[];
await mkdir(out,{recursive:true});
try {for(const width of [800,1280]){
 const height=width===800?600:720,page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.ts*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});
 await page.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5184/',{waitUntil:'domcontentloaded'});
 await page.locator('#menu-settings').click();await page.selectOption('#display-resolution',`${width}x${height}`);await page.selectOption('#display-mode','native');await page.locator('#menu-back').click();await page.locator('#menu-skirmish').click();await page.selectOption('#scenario-select','skirmish');await page.selectOption('#map-select','arena');await page.locator('#start-match').click();
 await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');
 await page.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene;s.__update=s.update;s.update=()=>{};s.sys.sceneUpdate=()=>{};s.cameras.main.setScroll(0,100);s.gathering.units.forEach((u,i)=>{u.selected=false;u.order={kind:'idle'};u.position={x:300+i*50,y:300};u.target={...u.position};u.navigation=undefined;});s.syncVisuals();});
 await page.waitForTimeout(100);
 const clickWorld=async(x,y,options={})=>{const p=await page.evaluate(({x,y})=>{const s=window.__gameCheck.scene.keys.BootScene,c=s.cameras.main,rect=s.game.canvas.getBoundingClientRect();return {x:rect.left+(c.x+x-c.scrollX)*rect.width/s.scale.width,y:rect.top+(c.y+y-c.scrollY)*rect.height/s.scale.height};},{x,y});await page.mouse.click(p.x,p.y,options);};
 await clickWorld(300,300);await clickWorld(450,300,{button:'right'});await page.keyboard.down('Shift');await clickWorld(500,350,{button:'right'});await page.keyboard.up('Shift');await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.syncVisuals());
 let queued=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.selected));assert.equal(queued.orderQueue.length,1);assert.equal(queued.order.kind,'move');assert.match(await page.locator('#selection-stats').textContent(),/Queue 1/);
 await page.screenshot({path:`${out}/queue-${width}.png`});
 await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.__update(0,10000);s.skipGameplayFrame=false;s.__update(0,100);});
 queued=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.selected));assert.equal(queued.target.x,500);assert.equal(queued.orderQueue,undefined);
 await page.locator('#hold-position').click();await page.keyboard.down('Shift');await clickWorld(450,300,{button:'right'});await page.keyboard.up('Shift');
 const held=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return s.gathering.units.find(u=>u.selected);});assert.equal(held.commandMode.kind,'hold');assert.equal(held.orderQueue.length,1);
 // Actual local Save/Load through the shipped buttons.
 await page.locator('#match-menu-button').click();await page.locator('#save-match').click();await page.locator('#load-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending);
 await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.update=()=>{};s.sys.sceneUpdate=()=>{};});
 const loaded=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.selected));assert.deepEqual(loaded.commandMode,held.commandMode);assert.deepEqual(loaded.orderQueue,held.orderQueue);
 await page.locator('#resume-match').click();await page.locator('#stop-units').click();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.selected).commandMode),undefined);
 await page.locator('#patrol-units').click();await clickWorld(450,300);assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.selected).commandMode.kind),'patrol');await page.screenshot({path:`${out}/patrol-${width}.png`});
 await page.locator('#stop-units').click();await page.locator('#patrol-units').click();await page.locator('#game canvas').focus();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.patrolMode),false);
 await page.evaluate(async()=>{const {matchFog}=await import('/src/gameplay/matchFog.ts'),s=window.__gameCheck.scene.keys.BootScene;s.gathering.units.forEach(u=>u.selected=false);s.gathering.units.push({id:'unit-4',kind:'soldier',archetype:'archer',owner:'player',hp:40,cargo:0,selected:false,position:{x:300,y:300},target:{x:300,y:300},order:{kind:'idle'}});s.enemyAI=undefined;s.enemyProduction=undefined;s.combat.enemies=[...s.combat.enemies.filter(e=>e.kind==='base'),{id:'enemy-1',kind:'unit',owner:'enemy',hp:100,position:{x:380,y:300},order:{kind:'idle'}}];s.fog=matchFog(s.currentMatch());s.syncVisuals();});await page.waitForTimeout(100);await clickWorld(300,300);await page.locator('#hold-position').click();
 await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.__update(0,1000);});const fight=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {unit:s.gathering.units.find(u=>u.id==='unit-4'),enemy:s.combat.enemies.find(e=>e.id==='enemy-1')};});assert.deepEqual(fight.unit.position,{x:300,y:300});assert(fight.enemy.hp<100,JSON.stringify(fight));await page.screenshot({path:`${out}/hold-combat-${width}.png`});
 await page.locator('#patrol-units').click();await clickWorld(450,350);await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.combat.enemies=s.combat.enemies.filter(e=>e.kind==='base');for(let i=0;i<25;i++){s.skipGameplayFrame=false;s.__update(0,100);}s.syncVisuals();});const patrolling=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.id==='unit-4'));assert.equal(patrolling.commandMode.kind,'patrol');assert.notDeepEqual(patrolling.position,{x:300,y:300});
 await page.locator('#match-menu-button').click();await page.locator('#restart-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending);assert(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.every(u=>!u.orderQueue&&!u.commandMode)));
 assert.deepEqual(errors,[]);reports.push({width,queued,held,loaded,errors});await page.close();
 }await writeFile(`${out}/browser.json`,JSON.stringify(reports,null,2));console.log('PASS physical queue, next order, Hold, Stop, Patrol and local Save/Load at 800/1280.');}finally{await browser.close();}
