import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core');
const browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE}),out='artifacts/rts-169',reports=[];
await mkdir(out,{recursive:true});
try {for(const faction of ['crown','clans','elves','dwarves','goblins'])for(const width of [800]) {
 const height=width===800?600:720,page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.ts*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});
 await page.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5183/',{waitUntil:'domcontentloaded'});
 await page.locator('#menu-settings').click();await page.selectOption('#display-resolution',`${width}x${height}`);await page.selectOption('#display-mode','native');await page.locator('#menu-back').click();await page.locator('#menu-skirmish').click();await page.selectOption('#faction-select',faction);await page.selectOption('#enemy-faction-select',faction);await page.selectOption('#scenario-select','skirmish');await page.selectOption('#map-select','arena');await page.locator('#start-match').click();
 await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');
 const recipe=await page.evaluate(async faction=>{const {factions}=await import('/src/config/factions.ts'),{replaceObstacles}=await import('/src/gameplay/map.ts'),{matchFog}=await import('/src/gameplay/matchFog.ts'),s=window.__gameCheck.scene.keys.BootScene,f=factions[faction];s.__update=s.update;s.update=()=>{};s.sys.sceneUpdate=()=>{};s.skipGameplayFrame=false;s.enemyProduction.wood=250;s.enemyProduction.gold=120;s.enemyProduction.acceptedJobs=4;s.enemyProduction.production.nextUnitNumber=2;s.enemyPolicy.research={attack:1,defense:1,job:null};
 const oldSites=s.combat.enemies.filter(e=>e.buildingType);s.map=replaceObstacles(s.map,s.map.obstacles.filter(o=>!oldSites.some(e=>e.footprint&&o.x===e.footprint.x&&o.y===e.footprint.y&&o.width===e.footprint.width&&o.height===e.footprint.height)));s.combat.enemies=s.combat.enemies.filter(e=>!e.buildingType);for(const e of s.combat.enemies)if(e.work){e.work.order={kind:'idle'};e.navigation=undefined;}
 for(const [i,role] of ['barracks','farm','forge'].entries()){const footprint={x:1120,y:224+i*96,width:64,height:64};s.combat.enemies.push({id:role==='farm'?'enemy-farm-1':`enemy-${role}`,kind:'building',buildingType:role,owner:'enemy',hp:f.buildings[role].hp,footprint,position:{x:1152,y:256+i*96},construction:{remainingSeconds:0,builderId:null}});s.map=replaceObstacles(s.map,[...s.map.obstacles,footprint]);}
 for(const [i,role]of ['archer'].entries())s.combat.enemies.push({id:`enemy-produced-${i+1}`,kind:'unit',owner:'enemy',role,hp:f.units[role].hp,position:{x:1024,y:192+i*40},order:{kind:'idle'}});
 const observer=s.gathering.units[0];observer.position={x:1060,y:200};observer.target={...observer.position};observer.order={kind:'idle'};s.cameras.main.setScroll(880,80);s.fog=matchFog(s.currentMatch());s.__update(0,10);s.syncVisuals();return f.units.air;},faction);
 const paid=await page.evaluate(async()=>{const {enemyPriority}=await import('/src/gameplay/enemyPolicy.ts'),{enemyPopulation}=await import('/src/gameplay/enemyConstruction.ts'),{technologyFor}=await import('/src/gameplay/productionPrerequisites.ts'),s=window.__gameCheck.scene.keys.BootScene,m=s.currentMatch();return {wood:s.enemyProduction.wood,gold:s.enemyProduction.gold,head:s.enemyProduction.production.queue?.[0],bank:s.enemyProduction,priority:enemyPriority(m),population:enemyPopulation(m),tech:technologyFor(m,'enemy'),phase:s.session.phase,active:s.gameplayActive(),elapsed:s.waves.elapsedSeconds};});assert.equal(paid.head?.kind,'air',JSON.stringify(paid));assert(paid.wood<=250-recipe.cost.wood);assert(paid.gold<=120-recipe.cost.gold);
 await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.__update(0,20000);});const produced=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.combat.enemies.filter(e=>e.role==='air'));assert(produced.length>0);
 await page.evaluate(async faction=>{const {factions}=await import('/src/config/factions.ts'),{matchFog}=await import('/src/gameplay/matchFog.ts'),s=window.__gameCheck.scene.keys.BootScene,f=factions[faction],base=s.combat.enemies.find(e=>e.kind==='base'),position={x:base.position.x-90,y:base.position.y};s.gathering.units.forEach(u=>u.selected=false);s.gathering.units.push({id:'unit-4',kind:'soldier',archetype:'air',faction,owner:'player',hp:f.units.air.hp,cargo:0,selected:true,autoDisabled:true,position,target:{...position},order:{kind:'idle'}});for(const e of s.combat.enemies)if(e.role==='soldier')e.hp=0;const archer=s.combat.enemies.find(e=>e.id==='enemy-produced-1');archer.position={x:base.position.x-70,y:base.position.y+40};archer.order={kind:'idle'};archer.navigation=undefined;s.fog=matchFog(s.currentMatch());s.skipGameplayFrame=false;s.__update(0,100);s.syncVisuals();},faction);
 const defense=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {threat:s.enemyAI.threatId,defenders:s.enemyAI.defenders,head:s.enemyProduction.production.queue?.[0]};});assert.equal(defense.threat,'unit-4');assert(defense.defenders.some(d=>d.id==='enemy-produced-1'));await page.screenshot({path:`${out}/${faction}-ai-air-defense-800.png`});
 await page.evaluate(async()=>{const {matchFog}=await import('/src/gameplay/matchFog.ts'),s=window.__gameCheck.scene.keys.BootScene,u=s.gathering.units.find(u=>u.id==='unit-4');u.position={x:200,y:800};u.target={...u.position};s.fog=matchFog(s.currentMatch());s.skipGameplayFrame=false;s.__update(0,100);});const hidden=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.enemyAI.threatId);assert.equal(hidden,null);assert.deepEqual(errors,[]);reports.push({faction,fixture:'Explicit completed tech/bank/army preconditions; real Scene.update paid production/counter/defense. Not regular economy or human playtest.',paid,produced,defense,hidden,errors});await page.close();
 }await writeFile(`${out}/browser-ai-air.json`,JSON.stringify(reports,null,2));console.log('PASS five AI profiles: real Scene.update pays/spawns aircraft, reacts to visible air with ground archers, releases defense when target leaves fog.');}finally{await browser.close();}
