import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core'),browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),out='artifacts/rts-222',results=[];await mkdir(out,{recursive:true});
try{for(const faction of ['crown','clans','elves','dwarves','goblins']){
 const p=await browser.newPage({viewport:{width:800,height:600}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.clear());await p.route('**/src/main.ts*',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});await p.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5181');await p.locator('#menu-settings').click();await p.selectOption('#display-resolution','800x600');await p.selectOption('#display-mode','native');await p.locator('#menu-back').click();await p.locator('#menu-skirmish').click();await p.selectOption('#faction-select',faction);await p.selectOption('#map-select','arena');await p.locator('#start-match').click();await p.waitForFunction(()=>window.__gameCheck?.scene.keys.BootScene.session.phase==='playing'&&!window.__gameCheck.scene.keys.BootScene.restartPending);
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{applyResourceCheat,resourceCheatCode}=await import('/src/gameplay/cheats.ts');s.update=()=>{};s.sys.sceneUpdate=()=>{};s.applyMatch(applyResourceCheat(s.currentMatch(),resourceCheatCode));s.cameras.main.setScroll(100,200);s.syncVisuals();});
 const click=async(q,button='left')=>{const pos=await p.evaluate(q=>{const c=window.__gameCheck.scene.keys.BootScene.cameras.main;return {x:c.x+(q.x-c.scrollX)*c.zoom,y:c.y+(q.y-c.scrollY)*c.zoom};},q),box=await p.locator('#game canvas').boundingBox(),sz=await p.locator('#game canvas').evaluate(c=>({w:c.width,h:c.height}));await p.mouse.click(box.x+pos.x*box.width/sz.w,box.y+pos.y*box.height/sz.h,{button});};
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{factions}=await import('/src/config/factions.ts');s.research={...s.research,attack:2,defense:2};s.combat.baseDevelopment={level:3,remainingSeconds:null};s.placement.forge={id:'forge',owner:'player',hp:factions[s.factions.player].buildings.forge.hp,footprint:{x:640,y:352,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};s.map.obstacles.push(s.placement.forge.footprint);s.syncVisuals();});
 const worker=await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.kind==='worker').position);await click(worker);await p.locator('#build-academy').click();await click({x:512,y:384});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.academy?.construction.remainingSeconds),10);
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<600&&s.placement.academy.construction.remainingSeconds>0;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.academy.construction.remainingSeconds),0);
 await click({x:544,y:416});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.selectedBuilding),'academy');assert(await p.locator('#train-giant').isVisible());const before=await p.evaluate(()=>{const g=window.__gameCheck.scene.keys.BootScene.gathering;return {wood:g.wood,gold:g.goldBalance};});await p.locator('#train-giant').click();const queued=await p.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {wood:s.gathering.wood,gold:s.gathering.goldBalance,job:s.placement.academy.production.queue[0]};});assert.equal(before.wood-queued.wood,90);assert.equal(before.gold-queued.gold,70);assert.equal(queued.job.durationSeconds,24);await p.screenshot({path:`${out}/${faction}-production.png`});
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<240;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});
 const g=await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='giant'));assert(g);await click(g.position);assert.match(await p.locator('#selection-stats').textContent(),/Supply 4/);await click({x:600,y:460},'right');await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<60;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});await p.screenshot({path:`${out}/${faction}-giant.png`});
 const opponent=await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{matchFog}=await import('/src/gameplay/matchFog.ts'),{factions}=await import('/src/config/factions.ts');const e={id:'enemy-forge',owner:'enemy',kind:'building',buildingType:'forge',hp:factions[s.factions.enemy].buildings.forge.hp,position:{x:704,y:480},footprint:{x:672,y:448,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};s.combat.enemies.push(e);s.map.obstacles.push(e.footprint);s.fog=matchFog(s.currentMatch());s.syncVisuals();return {id:e.id,hp:e.hp,position:e.position};});await click(opponent.position,'right');const fought=await p.evaluate(async id=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts'),ordered=s.gathering.units.find(u=>u.archetype==='giant').order;for(let i=0;i<12;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();return {ordered,hp:s.combat.enemies.find(e=>e.id===id)?.hp??0};},opponent.id);assert.equal(fought.ordered.kind,'attack');assert(fought.hp<opponent.hp);await p.screenshot({path:`${out}/${faction}-attack.png`});await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<60;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});
 await p.locator('#tech-tree-button').click();await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.syncVisuals());await p.getByRole('button',{name:'Army',exact:true}).click();await p.locator('[data-tech-node="unit-giant"]').click();assert.match(await p.locator('#technology-details').textContent(),/2.5× building damage/);await p.screenshot({path:`${out}/${faction}-tech-tree.png`});await p.keyboard.press('Escape');
 const probe=await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{encodeSave,decodeSave}=await import('/src/gameplay/save.ts');try{return decodeSave(encodeSave(s.currentMatch(),{camera:{x:100,y:200},building:null}));}catch(e){return {error:e.message};}});assert(probe.ok,JSON.stringify(probe));
 await p.locator('#match-menu-button').click();await p.locator('#save-match').click();assert.match(await p.locator('#save-status').textContent(),/saved/i);await p.locator('#load-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='paused');assert(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.some(u=>u.archetype==='giant')));await p.locator('#restart-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.academy),undefined);assert.deepEqual(errors,[]);results.push({faction,actualMouseAcademyBuildTrainMoveBuildingAttack:true,queued,fought,saveLoadRestart:true,errors});console.log('PASS '+faction);await p.close();
}await writeFile(`${out}/browser.json`,JSON.stringify({fixture:'Actual menu/clicks; resource-cheat funding, seeded completed Forge/research II/base III; .1s gameplay ticks; enemy Forge staged for attack probe',results},null,2)+'\n');}finally{await browser.close();}
