import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core'),browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),out='artifacts/rts-212',results=[];await mkdir(out,{recursive:true});
try{for(const run of [{id:'bramblemaw',faction:'crown',series:'human-frontier-v1',mission:'forest-watch'},{id:'gravelheart',faction:'dwarves',series:'dwarves-road-v1',mission:'ridge-convoy'}]){
 const p=await browser.newPage({viewport:{width:800,height:600}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(run=>{localStorage.clear();localStorage.setItem('warcraft-2-tribute.campaign.v2',JSON.stringify({version:2,campaigns:{[`${run.series}/${run.faction}/beginner`]:['first-steps','forest-watch','the-siege','the-outpost','the-crossing','ridge-convoy','valley-rescue','coastal-banner']}}));},run);
 await p.route('**/src/main.ts*',async r=>{const a=await r.fetch();await r.fulfill({response:a,body:(await a.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});
 await p.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5181');await p.locator('#menu-settings').click();await p.selectOption('#display-resolution','800x600');await p.selectOption('#display-mode','native');await p.locator('#menu-back').click();await p.locator('#menu-campaign').click();await p.selectOption('#faction-select',run.faction);await p.locator('#campaign-next-faction').click();await p.selectOption('#difficulty-select','beginner');await p.locator('#campaign-next-difficulty').click();await p.locator(`[data-campaign-mission="${run.mission}"]`).click();await p.locator('#start-match').click();await p.waitForFunction(()=>window.__gameCheck?.scene.keys.BootScene.session.phase==='playing'&&!window.__gameCheck.scene.keys.BootScene.restartPending);
 const initial=await p.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.update=()=>{};s.sys.sceneUpdate=()=>{};return {bosses:s.bosses,visibleBosses:[...s.enemyVisuals.keys()].filter(id=>id.startsWith('enemy-boss-'))};});assert.equal(initial.visibleBosses.length,0);
 const preparation=await p.evaluate(async run=>{
  const s=window.__gameCheck.scene.keys.BootScene,{bossDefinitions}=await import('/src/config/bosses.ts'),{updateMatch}=await import('/src/gameplay/match.ts'),{beginPlacement,placeBuilding,placementObstacles}=await import('/src/gameplay/placement.ts'),{enqueueProduction,updateQueuedProduction}=await import('/src/gameplay/productionQueue.ts'),{matchPopulation}=await import('/src/gameplay/navy.ts'),{bodyFits}=await import('/src/gameplay/map.ts'),{matchFog}=await import('/src/gameplay/matchFog.ts'),{matchStats}=await import('/src/gameplay/matchStats.ts');let m=s.currentMatch();
  // Funding fixture is tracked by the existing resource-cheat ledger. Buildings/units use paid game APIs.
  m.gathering.resourceCheatUses=(m.gathering.resourceCheatUses??0)+1;m.gathering.wood+=100000;m.gathering.goldBalance+=100000;m.gathering.units[0].selected=true;
  for(const kind of ['barracks','farm','farm']){let placed;for(let y=352;y<=640&&!placed;y+=64)for(let x=448;x<=832&&!placed;x+=64){const r=placeBuilding(beginPlacement(m.placement,kind),{x,y},m.gathering.wood,placementObstacles(m.gathering),{map:m.map,gathering:m.gathering,enemies:m.combat.enemies});if(!r.placement.active&&r.gathering){m={...m,placement:r.placement,gathering:r.gathering,map:r.map};placed=true;}}if(!placed)throw Error('No paid building site');for(let i=0;i<2000&&(kind==='barracks'?m.placement.construction.remainingSeconds>0:m.placement.farms.at(-1).construction.remainingSeconds>0);i++)m=updateMatch(m,.1);}
  for(let i=0;i<14;i++){const b={kind:'barracks',bounds:m.map,footprint:m.placement.barracks,ready:true},q=enqueueProduction(m.gathering,m.soldierProduction,b,matchPopulation(m));if(q.production===m.soldierProduction)throw Error('Paid recruit admission failed');const r=updateQueuedProduction(q.gathering,q.production,30,b,{map:m.map,enemies:m.combat.enemies});m={...m,gathering:r.gathering,soldierProduction:r.production};const u=m.gathering.units.at(-1);u.position={x:600+(i%5)*40,y:800+Math.floor(i/5)*40};u.target={...u.position};u.order={kind:'idle'};if(!bodyFits(m.map,u.position,12))throw Error('Paid staging body blocked');}
  m.production.nextUnitNumber=m.soldierProduction.nextUnitNumber;
  const b=bossDefinitions[run.id],fighters=m.gathering.units.filter(u=>u.kind==='soldier'),positions=[];
  for(let row=0;row<7;row++)for(let col=0;col<9;col++){const p={x:b.position.x-160+col*40,y:b.position.y-120+row*40};if(Math.hypot(p.x-b.position.x,p.y-b.position.y)>80&&Math.hypot(p.x-b.position.x,p.y-b.position.y)<=180&&(p.x<=b.position.x-40||p.y<=b.position.y-40)&&bodyFits(m.map,p,14))positions.push(p);}
  if(positions.length<fighters.length)throw Error('No legal encounter formation');fighters.forEach((u,i)=>{u.position={...positions[i]};u.target={...positions[i]};u.order={kind:'idle'};u.selected=false;u.autoDisabled=true;delete u.navigation;});m.gathering.units.filter(u=>u.kind==='worker').forEach(u=>u.selected=false);m.fog=matchFog(m);s.applyMatch(m);s.cameras.main.setScroll(b.position.x-320,b.position.y-190);s.syncVisuals();return {fighters:fighters.map(u=>({id:u.id,position:u.position})),bossPosition:b.position,name:b.name,population:matchPopulation(m),wood:m.gathering.wood,gold:m.gathering.goldBalance,stats:matchStats(m).player};
 },run);assert.equal(preparation.fighters.length,14);assert(preparation.population.used<=preparation.population.cap);await p.screenshot({path:`${out}/${run.id}-discovered.png`});
 // Select the prepared army with a real mouse drag, then attack the visible guardian.
 const box=await p.locator('#game canvas').boundingBox(),size=await p.locator('#game canvas').evaluate(c=>({w:c.width,h:c.height})),screen=async q=>{const v=await p.evaluate(q=>{const c=window.__gameCheck.scene.keys.BootScene.cameras.main;return {x:c.x+(q.x-c.scrollX)*c.zoom,y:c.y+(q.y-c.scrollY)*c.zoom};},q);return {x:box.x+v.x*box.width/size.w,y:box.y+v.y*box.height/size.h};};
 const positions=preparation.fighters.map(u=>u.position),a=await screen({x:Math.min(...positions.map(p=>p.x))-18,y:Math.min(...positions.map(p=>p.y))-18}),z=await screen({x:Math.max(...positions.map(p=>p.x))+18,y:Math.max(...positions.map(p=>p.y))+18});await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(z.x,z.y,{steps:5});await p.mouse.up();const target=await screen(preparation.bossPosition);await p.mouse.click(target.x,target.y,{button:'right'});
 const battle=await p.evaluate(async run=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');const ordered=s.gathering.units.filter(u=>u.kind==='soldier'&&u.order.kind==='attack').length;let frames=0;for(let i=0;i<2400&&s.bosses.guardians[run.id].hp>0;i++){s.applyMatch(updateMatch(s.currentMatch(),.05));if(i%20===0)s.syncVisuals();frames++;if(i===40)break;}s.syncVisuals();return {ordered,frames,hp:s.bosses.guardians[run.id].hp,engaged:s.bosses.guardians[run.id].engaged,alive:s.gathering.units.filter(u=>u.kind==='soldier').length};},run);assert.equal(battle.ordered,14);assert.equal(battle.engaged,true);assert(battle.hp<initial.bosses.guardians[run.id].hp);await p.screenshot({path:`${out}/${run.id}-combat.png`});
 await p.locator('#match-menu-button').click();await p.locator('#save-match').click();assert.match(await p.locator('#save-status').textContent(),/saved/i);await p.locator('#load-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='paused');assert.equal(await p.evaluate(id=>window.__gameCheck.scene.keys.BootScene.bosses.guardians[id].hp,run.id),battle.hp);await p.locator('#resume-match').click();
 const defeated=await p.evaluate(async run=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');s.update=()=>{};s.sys.sceneUpdate=()=>{};for(let i=0;i<2400&&s.bosses.guardians[run.id].hp>0;i++)s.applyMatch(updateMatch(s.currentMatch(),.05));s.syncVisuals();return {boss:s.bosses.guardians[run.id],alive:s.gathering.units.filter(u=>u.kind==='soldier').length,outcome:s.outcome,wood:s.gathering.wood,gold:s.gathering.goldBalance};},run);assert.equal(defeated.boss.hp,0);assert(defeated.alive>0);assert.equal(defeated.outcome,'playing');await p.screenshot({path:`${out}/${run.id}-defeated.png`});
 const loot=await p.evaluate(async id=>{const s=window.__gameCheck.scene.keys.BootScene,{bossLootPosition}=await import('/src/gameplay/bosses.ts'),{updateMatch}=await import('/src/gameplay/match.ts'),{commandGroupMove}=await import('/src/gameplay/groupMovement.ts');const p=bossLootPosition(id);s.gathering.units=s.gathering.units.map(u=>({...u,selected:u.kind==='soldier'}));s.gathering.units=commandGroupMove(s.gathering.units,p,s.map);for(let i=0;i<2000&&!s.bosses.guardians[id].claimed;i++)s.applyMatch(updateMatch(s.currentMatch(),.05));s.syncVisuals();return {claimed:s.bosses.guardians[id].claimed,wood:s.gathering.wood,gold:s.gathering.goldBalance};},run.id);assert.equal(loot.claimed,true);const reward=run.id==='bramblemaw'?{wood:300,gold:200}:{wood:200,gold:350};assert.equal(loot.wood-preparation.wood,reward.wood);assert.equal(loot.gold-preparation.gold,reward.gold);await p.screenshot({path:`${out}/${run.id}-loot.png`});
 await p.locator('#match-menu-button').click();await p.locator('#save-match').click();assert.match(await p.locator('#save-status').textContent(),/saved/i);await p.locator('#load-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='paused');assert.equal(await p.evaluate(id=>window.__gameCheck.scene.keys.BootScene.bosses.guardians[id].claimed,run.id),true);assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.wood),loot.wood);
 await p.locator('#restart-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');assert.equal(await p.evaluate(id=>window.__gameCheck.scene.keys.BootScene.bosses.guardians[id].claimed,run.id),false);assert.deepEqual(errors,[]);results.push({run,initial,preparation,battle,defeated,loot,actualMouseAttack:true,paidArmy:true,woundedSaveLoad:true,claimedSaveLoad:true,restart:true,errors});console.log('PASS '+run.id);await p.close();
 }await writeFile(`${out}/browser.json`,JSON.stringify({fixture:'Scoped campaign completions unlock mission; ledger-tracked funding; paid building/production APIs; troops staged near guardian; real mouse attack and actual match steps',results},null,2)+'\n');
}finally{await browser.close();}
