import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core'),browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE}),out=process.env.W2T_SCREENSHOTS??'artifacts/rts-180/local',url=process.env.W2T_RELEASE_URL??'http://127.0.0.1:4186/warcraft-2-tribute/',version=process.env.W2T_RELEASE_VERSION??'v0.3.0';await mkdir(out,{recursive:true});const reports=[];
try{for(const [width,height,resolution,mode] of [[800,600,'800x600','native'],[1280,720,'1280x720','native'],[1600,900,'800x600','native'],[1600,900,'800x600','fit']]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[],failed=[],assets=new Set();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(/\/(audio|assets|art|sprites|textures)\//.test(r.url())){if(r.status()>=400)failed.push({url:r.url(),status:r.status()});else assets.add(r.url());}});
 await page.addInitScript(()=>localStorage.setItem('warcraft-2-tribute.campaign.v1',JSON.stringify({version:1,completed:['first-steps','forest-watch','the-siege','the-outpost','the-crossing','ridge-convoy','valley-rescue','coastal-banner']})));
 await page.route('**/assets/index-*.js',async route=>{const response=await route.fetch();let body=await response.text();const matches=[...body.matchAll(/new ([A-Za-z_$][\w$]*)\.Game\(\{/g)],last=matches.at(-1);assert(last,'Phaser bootstrap missing');body=body.slice(0,last.index)+'window.__gameCheck='+body.slice(last.index);await route.fulfill({response,body});});
 await page.goto(url,{waitUntil:'networkidle'});assert.equal(await page.locator('#home-release').innerText(),version);const build=await page.locator('#home-release').getAttribute('title');if(process.env.W2T_EXPECT_BUILD)assert.equal(build,`Build ${process.env.W2T_EXPECT_BUILD}`);await page.locator('#menu-changelog').click();assert.match(await page.locator('#changelog').innerText(),/Expanded campaign, independent AI and teams/);await page.locator('#menu-back').click();await page.locator('#menu-settings').click();
 const resolutions=[];if(width===1280)for(const id of ['800x600','1024x768','1280x720','1600x900','1920x1080','2048x1332']){await page.selectOption('#display-resolution',id);const size=await page.evaluate(()=>({width:parseInt(document.getElementById('app').style.width),height:parseInt(document.getElementById('app').style.height)}));assert.equal(`${size.width}x${size.height}`,id);resolutions.push(id);}
 await page.selectOption('#display-resolution',resolution);await page.selectOption('#display-mode',mode);await page.locator('#menu-back').click();await page.locator('#menu-campaign').click();await page.locator('[data-campaign-mission="forest-watch"]').click();await page.locator('#start-match').click();
 const ready=async()=>page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending),freeze=async()=>page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.__tick=Object.getPrototypeOf(s).update.bind(s);s.update=()=>{};s.sys.sceneUpdate=()=>{};s.skipGameplayFrame=false;});await ready();await freeze();assert.equal(await page.locator('#top-release').innerText(),version);
 const geometry=await page.evaluate(()=>{const a=document.getElementById('app').getBoundingClientRect(),c=window.__gameCheck.canvas;return {width:a.width,height:a.height,canvasWidth:c.width,canvasHeight:c.height,gameWidth:document.getElementById('game').clientWidth,gameHeight:document.getElementById('game').clientHeight,mode:document.getElementById('display-mode').value,minimap:document.getElementById('minimap-overlay').getBoundingClientRect().width};});const [rw,rh]=resolution.split('x').map(Number),scale=mode==='fit'?Math.min(width/rw,height/rh):Math.min(1,width/rw,height/rh);assert(Math.abs(geometry.width-rw*scale)<1);assert(Math.abs(geometry.height-rh*scale)<1);assert(geometry.minimap>50);assert.equal(geometry.canvasWidth,geometry.gameWidth);assert.equal(geometry.canvasHeight,geometry.gameHeight);
 await page.locator('#fullscreen-button').click();await page.waitForFunction(()=>!!document.fullscreenElement);assert.equal(await page.locator('#display-resolution').inputValue(),resolution);await page.locator('#fullscreen-button').click();await page.waitForFunction(()=>!document.fullscreenElement);assert.equal(await page.locator('#display-mode').inputValue(),mode);
 const workerPoint=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene,c=s.cameras.main,u=s.gathering.units[0],b=s.game.canvas.getBoundingClientRect();return {x:b.x+(c.x+u.position.x-c.scrollX)*b.width/s.game.canvas.width,y:b.y+(c.y+u.position.y-c.scrollY)*b.height/s.game.canvas.height};});await page.mouse.click(workerPoint.x,workerPoint.y);assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units[0].selected),true);
 await page.locator('#match-menu-button').click();const clock=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene,saved=s.waves.elapsedSeconds;s.__tick(0,1000);return {before:saved,after:s.waves.elapsedSeconds};});assert.equal(clock.before,clock.after);await page.locator('#save-match').click();await page.locator('#load-match').click();await ready();await freeze();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.session.phase),'paused');assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.campaignRun.phase),0);await page.locator('#resume-match').click();
 await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.campaignRun={version:1,phase:4,waveStartedSeconds:0};s.combat.enemies=[];s.__tick(0,0);});assert.match(await page.locator('#match-results').innerText(),/Victory/);const once=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene,k='warcraft-2-tribute.highscores.v1',a=localStorage.getItem(k),time=s.waves.elapsedSeconds;s.__tick(0,2000);s.syncVisuals();s.syncVisuals();return {once:a===localStorage.getItem(k)&&!!a&&JSON.parse(a).entries.filter(e=>e.id===s.matchId).length===1,frozen:time===s.waves.elapsedSeconds};});assert(once.once&&once.frozen);await page.screenshot({path:`${out}/campaign-result-${width}-${mode}.png`});await page.locator('#result-play-again').click();await ready();await freeze();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.campaignRun.phase),0);
 await page.locator('#match-menu-button').click();await page.locator('#quit-request').click();await page.locator('#new-match').click();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.campaignRun),undefined);await page.locator('#menu-skirmish').click();await page.selectOption('#scenario-select','skirmish');await page.selectOption('#map-select','plains96');await page.locator('#start-match').click();await ready();await freeze();await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.combat.baseHP=0;s.__tick(0,0);});assert.match(await page.locator('#match-results').innerText(),/Defeat/);await page.locator('#result-main-menu').click();
 await page.locator('#menu-skirmish').click();await page.selectOption('#map-select','plains96');await page.selectOption('#player-count-select','3');await page.selectOption('#ai-2-team-select','1');await page.locator('#start-match').click();await ready();await freeze();await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.combat.baseHP=0;s.__tick(0,250);});assert.match(await page.locator('#session-status').innerText(),/Spectating your team/);assert.equal(await page.locator('#gameplay-controls').evaluate(e=>e.disabled),true);
 await page.locator('#match-menu-button').click();await page.locator('#save-match').click();await page.locator('#load-match').click();await ready();await freeze();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.multiplePlayers.roster[2].teamId),1);await page.locator('#resume-match').click();await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.multiplePlayers.ai.find(b=>b.id==='ai-2').state.combat.enemies.find(e=>e.kind==='base').hp=0;s.__tick(0,250);});assert.match(await page.locator('#match-results').innerText(),/Defeat/);await page.locator('#result-statistics').click();assert.match(await page.locator('#match-results').innerText(),/Team/);await page.screenshot({path:`${out}/team-result-${width}-${mode}.png`});await page.locator('#result-main-menu').click();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.multiplePlayers),undefined);
 await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#home-release').innerText(),version);assert.equal(await page.locator('#display-resolution').inputValue(),resolution);assert.equal(await page.locator('#display-mode').inputValue(),mode);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert([...assets].some(u=>u.includes('/audio/')));assert([...assets].some(u=>/\.png/.test(u)));reports.push({width,height,resolution,mode,version,build,resolutions,geometry,pause:clock,campaignSavePhase0:true,explicitCompletedCampaignPhasesVictoryFixture:true,once,replay:true,skirmishDefeatFixture:true,teamSpectatorSaveDefeatFixture:true,menuClearsState:true,fullscreenEnterExit:true,reload:true,assets:[...assets],failed,errors});await page.close();
}await writeFile(`${out}/browser.json`,JSON.stringify(reports,null,2));console.log('PASS production release/campaign/skirmish/team/save/pause/replay/menu/fullscreen/resolutions/Native/Fit/assets/reload.');}finally{await browser.close();}
