import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core'),browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),out='artifacts/rts-221',results=[];await mkdir(out,{recursive:true});
try{for(const faction of ['crown','clans','elves','dwarves','goblins']){
 const p=await browser.newPage({viewport:{width:800,height:600}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.clear());await p.route('**/src/main.ts*',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});await p.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5181');await p.locator('#menu-settings').click();await p.selectOption('#display-resolution','800x600');await p.selectOption('#display-mode','native');await p.locator('#menu-back').click();await p.locator('#menu-skirmish').click();await p.selectOption('#faction-select',faction);await p.selectOption('#map-select','arena');await p.locator('#start-match').click();await p.waitForFunction(()=>window.__gameCheck?.scene.keys.BootScene.session.phase==='playing'&&!window.__gameCheck.scene.keys.BootScene.restartPending);
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{applyResourceCheat,resourceCheatCode}=await import('/src/gameplay/cheats.ts');s.update=()=>{};s.sys.sceneUpdate=()=>{};s.applyMatch(applyResourceCheat(s.currentMatch(),resourceCheatCode));s.cameras.main.setScroll(100,200);s.syncVisuals();});
 const click=async(q,button='left')=>{const pos=await p.evaluate(q=>{const c=window.__gameCheck.scene.keys.BootScene.cameras.main;return {x:c.x+(q.x-c.scrollX)*c.zoom,y:c.y+(q.y-c.scrollY)*c.zoom};},q),box=await p.locator('#game canvas').boundingBox(),sz=await p.locator('#game canvas').evaluate(c=>({w:c.width,h:c.height}));await p.mouse.click(box.x+pos.x*box.width/sz.w,box.y+pos.y*box.height/sz.h,{button});};
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{factions}=await import('/src/config/factions.ts');s.research={...s.research,attack:1,defense:1};s.placement.forge={id:'forge',owner:'player',hp:factions[s.factions.player].buildings.forge.hp,footprint:{x:640,y:352,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};s.map.obstacles.push(s.placement.forge.footprint);s.syncVisuals();});
 const worker=await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.kind==='worker').position);await click(worker);await p.locator('#build-academy').click();await click({x:512,y:384});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.academy?.construction.remainingSeconds),10);
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<600&&s.placement.academy.construction.remainingSeconds>0;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.academy.construction.remainingSeconds),0);
 await click({x:544,y:416});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.selectedBuilding),'academy');assert(await p.locator('#train-healer').isVisible());const before=await p.evaluate(()=>{const g=window.__gameCheck.scene.keys.BootScene.gathering;return {wood:g.wood,gold:g.goldBalance};});await p.locator('#train-healer').click();const queued=await p.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {wood:s.gathering.wood,gold:s.gathering.goldBalance,job:s.placement.academy.production.queue[0]};});assert.equal(before.wood-queued.wood,40);assert.equal(before.gold-queued.gold,30);assert.equal(queued.job.durationSeconds,10);await p.screenshot({path:`${out}/${faction}-production.png`});
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<100;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});
 const target=await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{matchFog}=await import('/src/gameplay/matchFog.ts');const h=s.gathering.units.find(u=>u.archetype==='healer'),w=s.gathering.units.find(u=>u.kind==='worker');h.position={x:600,y:460};h.target={...h.position};w.position={x:630,y:460};w.target={...w.position};w.order={kind:'idle'};w.navigation=undefined;w.hp=10;s.fog=matchFog(s.currentMatch());s.syncVisuals();return {healerId:h.id,workerId:w.id};});
 await click({x:600,y:460});await p.locator('#cast-heal').click();await click({x:630,y:460});const manual=await p.evaluate(ids=>{const s=window.__gameCheck.scene.keys.BootScene,h=s.gathering.units.find(u=>u.id===ids.healerId),w=s.gathering.units.find(u=>u.id===ids.workerId);return {mana:h.mana,cooldown:h.spellCooldowns?.heal,hp:w.hp,pulse:w.healFlash>s.waves.elapsedSeconds};},target);assert.equal(manual.mana,30);assert.equal(manual.cooldown,6);assert(manual.hp>10);assert(manual.pulse);await p.screenshot({path:`${out}/${faction}-heal.png`});
 await p.evaluate(async ids=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<60;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.gathering.units.find(u=>u.id===ids.workerId).hp=10;s.syncVisuals();},target);await p.locator('#autocast-heal').click();const auto=await p.evaluate(async ids=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<5;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();return {hp:s.gathering.units.find(u=>u.id===ids.workerId).hp,enabled:s.gathering.units.find(u=>u.id===ids.healerId).healAutocast};},target);assert(auto.enabled);assert(auto.hp>10);
 await p.locator('#tech-tree-button').click();await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.syncVisuals());await p.getByRole('button',{name:'Army',exact:true}).click();await p.locator('[data-tech-node="unit-healer"]').click();assert.match(await p.locator('#technology-details').textContent(),/Healing support/);await p.screenshot({path:`${out}/${faction}-tech-tree.png`});await p.keyboard.press('Escape');
 const probe=await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{encodeSave,decodeSave}=await import('/src/gameplay/save.ts');try{return decodeSave(encodeSave(s.currentMatch(),{camera:{x:100,y:200},building:null}));}catch(e){return {error:e.message};}});assert(probe.ok,JSON.stringify(probe));
 await p.locator('#match-menu-button').click();await p.locator('#save-match').click();assert.match(await p.locator('#save-status').textContent(),/saved/i);await p.locator('#load-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='paused');assert(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.some(u=>u.archetype==='healer'&&u.healAutocast)));await p.locator('#restart-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.academy),undefined);assert.deepEqual(errors,[]);results.push({faction,actualMouseAcademyBuildTrainManualHealAutocast:true,queued,manual,auto,saveLoadRestart:true,errors});console.log('PASS '+faction);await p.close();
}await writeFile(`${out}/browser.json`,JSON.stringify({fixture:'Actual menu/clicks; resource-cheat funding, seeded completed Forge/research I; .1s gameplay ticks; wounded target staging for Heal probes',results},null,2)+'\n');}finally{await browser.close();}
