import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core'),browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE}),out='artifacts/rts-175',reports=[];await mkdir(out,{recursive:true});
try{for(const width of [800,1280]){
 const height=width===800?600:720,page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.ts*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});
 await page.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5186/');await page.locator('#menu-settings').click();await page.selectOption('#display-resolution',`${width}x${height}`);await page.selectOption('#display-mode','native');await page.locator('#menu-back').click();await page.locator('#menu-skirmish').click();await page.selectOption('#scenario-select','skirmish');await page.selectOption('#map-select','plains96');await page.selectOption('#player-count-select','3');await page.selectOption('#ai-2-team-select','1');await page.locator('#ai-2-team-select').scrollIntoViewIfNeeded();await page.screenshot({path:`${out}/teams-${width}.png`});await page.locator('#start-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending);
 await page.evaluate(async()=>{const {updatePreferences}=await import('/src/presentation/preferences.ts');updatePreferences({camera:{edgePan:false}});const s=window.__gameCheck.scene.keys.BootScene;s.update=()=>{};s.sys.sceneUpdate=()=>{};const {updateMatch}=await import('/src/gameplay/match.ts');s.applyMatch(updateMatch(s.currentMatch(),.25));s.cameras.main.centerOn(1664,384);s.syncVisuals();});
 const shared=await page.evaluate(()=>{const m=window.__gameCheck.scene.keys.BootScene.currentMatch();return {sameVisible:JSON.stringify(m.fog.teams.player.visible)===JSON.stringify(m.multiplePlayers.ai[1].vision.visible),sameExplored:JSON.stringify(m.fog.teams.player.explored)===JSON.stringify(m.multiplePlayers.ai[1].vision.explored),thirdBaseVisible:m.fog.teams.player.visible[Math.floor(384/m.fog.tileSize)*m.fog.columns+Math.floor(1664/m.fog.tileSize)]};});assert(shared.sameVisible&&shared.sameExplored&&shared.thirdBaseVisible);assert.match(await page.locator('#minimap-player-legend').innerText(),/AI2 T1/);await page.screenshot({path:`${out}/shared-vision-${width}.png`});
 const click=async(point,button='left')=>{await page.evaluate(p=>window.__gameCheck.scene.keys.BootScene.cameras.main.centerOn(p.x,p.y),point);await page.waitForTimeout(25);const q=await page.evaluate(p=>{const s=window.__gameCheck.scene.keys.BootScene,c=s.cameras.main,b=s.game.canvas.getBoundingClientRect();return {x:b.x+(c.x+p.x-c.scrollX)*b.width/s.game.canvas.width,y:b.y+(c.y+p.y-c.scrollY)*b.height/s.game.canvas.height};},point);await page.mouse.click(q.x,q.y,{button});};
 await page.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,m=s.currentMatch(),{projectMultiplePlayers,shareTeamVision}=await import('/src/gameplay/multiplePlayers.ts');m.gathering.units.push({id:'unit-4',kind:'soldier',archetype:'specialist',faction:'crown',owner:'player',hp:100,mana:100,cargo:0,selected:false,position:{x:400,y:500},target:{x:400,y:500},order:{kind:'idle'}});m.production.nextUnitNumber=m.soldierProduction.nextUnitNumber=5;const ally=m.multiplePlayers.ai[1];ally.state.combat.enemies.push({id:'enemy-produced-1',kind:'unit',role:'soldier',owner:'enemy',hp:20,position:{x:450,y:500},order:{kind:'idle'}});ally.state.enemyProduction.production.nextUnitNumber=2;s.applyMatch(shareTeamVision(projectMultiplePlayers(m)));s.syncVisuals();});
 await click({x:450,y:500});await click({x:550,y:550},'right');assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.multiplePlayers.ai[1].state.combat.enemies.find(e=>e.id==='enemy-produced-1').order.kind),'idle');
 await click({x:400,y:500});await click({x:450,y:500},'right');assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.id==='unit-4').order.kind),'idle');
 await page.keyboard.press('F2');await click({x:450,y:500});const healed=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.multiplePlayers.ai[1].state.combat.enemies.find(e=>e.id==='enemy-produced-1').hp);assert(healed>20);await page.screenshot({path:`${out}/allied-heal-${width}.png`});
 await page.locator('#match-menu-button').click();await page.locator('#save-match').click();assert.match(await page.locator('#save-status').innerText(),/saved/i);await page.locator('#load-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending);assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.multiplePlayers.roster[2].teamId),1);
 await page.locator('#restart-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending);
 await page.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene;s.update=()=>{};s.sys.sceneUpdate=()=>{};let m=s.currentMatch();const {projectMultiplePlayers}=await import('/src/gameplay/multiplePlayers.ts'),{withGateRules}=await import('/src/gameplay/gates.ts');const footprint={x:704,y:480,width:64,height:32};m.placement.defenses=[{id:'gate-1',kind:'gate',owner:'player',hp:180,level:1,upgradeRemaining:null,cooldown:0,open:false,footprint,construction:{remainingSeconds:0,builderId:null}}];for(const bot of m.multiplePlayers.ai){bot.state.enemyAI=undefined;bot.state.combat.enemies.push({id:'enemy-produced-1',kind:'unit',role:'soldier',owner:'enemy',hp:48,position:{x:bot.id==='enemy'?640:672,y:496},order:{kind:'muster',destination:{x:832,y:496}}});bot.state.enemyProduction.production.nextUnitNumber=2;}s.applyMatch(withGateRules(projectMultiplePlayers(m)));s.syncVisuals();});
 await click({x:736,y:496});await page.locator('#toggle-gate').click();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.defenses[0].open),true);
 const passage=await page.evaluate(async()=>{const {updateMatch}=await import('/src/gameplay/match.ts'),s=window.__gameCheck.scene.keys.BootScene,trace=[];for(let i=0;i<16;i++){s.applyMatch(updateMatch(s.currentMatch(),.1));trace.push(s.multiplePlayers.ai.map(bot=>({id:bot.id,position:bot.state.combat.enemies.find(e=>e.id==='enemy-produced-1').position})));}s.syncVisuals();return trace;});
 assert(passage.some(frame=>frame[1].position.x>704&&frame[1].position.x<768&&Math.abs(frame[1].position.y-496)<1));assert(passage.every(frame=>!(frame[0].position.x>704&&frame[0].position.x<768&&frame[0].position.y>480&&frame[0].position.y<512)));await page.screenshot({path:`${out}/gate-passage-${width}.png`});
 assert.deepEqual(errors,[]);reports.push({width,height,physicalTeamSettings:true,shared,independentControl:true,manualAllyAttackBlocked:true,physicalFriendlySpellHP:healed,saveLoadTeams:true,physicalOpenGate:true,passage,explicitUnitGateFixtures:true,errors});await page.close();
}await writeFile(`${out}/browser.json`,JSON.stringify(reports,null,2));console.log('PASS native800/1280 team setup/shared vision/no allied control/attack, friendly cast, team save and allied-only open-gate passage.');}finally{await browser.close();}
