import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core'),browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE});
try{for(const [width,height]of [[800,600],[1280,720]]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.ts*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});
 await page.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5190');await page.locator('#menu-skirmish').click();await page.locator('#start-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending);
 const snapshot=()=>page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {wood:s.gathering.wood,gold:s.gathering.goldBalance,orders:JSON.stringify(s.gathering.units.map(u=>u.order)),placement:s.placement.active};});
 await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.update=()=>{};s.sys.sceneUpdate=()=>{};document.querySelector('#game canvas').focus();});
 const before=await snapshot();await page.keyboard.press('Enter');await page.locator('#cheat-code').pressSequentially('icanseemyhousefromhere');assert.equal(await page.locator('#cheat-code').inputValue(),'icanseemyhousefromhere');const typing=await snapshot();assert.equal(typing.orders,before.orders);assert.equal(typing.placement,before.placement);await page.keyboard.press('Enter');assert(!(await page.locator('#cheat-dialog').evaluate(d=>d.open)));const after=await snapshot();assert.equal(after.wood,before.wood+100000);assert.equal(after.gold,before.gold+100000);
 await page.keyboard.press('Enter');await page.locator('#cheat-code').fill('wrong');await page.keyboard.press('Enter');assert.match(await page.locator('#cheat-result').textContent(),/Unknown/);await page.keyboard.press('Escape');assert.deepEqual(await snapshot(),after);
 await page.keyboard.press('Enter');await page.locator('#cheat-code').fill('icanseemyhousefromhere');await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal((await snapshot()).wood,after.wood+100000);
 await page.keyboard.press('Enter');await page.locator('#cheat-cancel').focus();await page.keyboard.press('Enter');assert(!(await page.locator('#cheat-dialog').evaluate(d=>d.open)));assert.equal((await snapshot()).wood,after.wood+100000);
 await page.keyboard.press('p');assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.session.phase),'paused');await page.keyboard.press('Enter');assert(!(await page.locator('#cheat-dialog').evaluate(d=>d.open)));await page.locator('#match-menu-button').click();await page.locator('#save-match').click();assert.match(await page.locator('#save-status').textContent(),/saved|spar/i);await page.locator('#load-match').click();await page.waitForFunction(expected=>window.__gameCheck.scene.keys.BootScene.gathering.wood===expected&&!window.__gameCheck.scene.keys.BootScene.restartPending,after.wood+100000);assert.equal((await snapshot()).gold,after.gold+100000);assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.resourceCheatUses),2);await page.keyboard.press('Escape');assert.deepEqual(errors,[]);await page.close();
}console.log('PASS native800/1280 cheat typing, Enter/Apply/repeat, invalid code, Escape and paused rejection; no gameplay hotkeys while typing');}finally{await browser.close();}
