import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core'),browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),out='artifacts/rts-220',results=[];await mkdir(out,{recursive:true});
try{for(const faction of ['crown','clans','elves','dwarves','goblins']){
 const p=await browser.newPage({viewport:{width:800,height:600}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.clear());await p.route('**/src/main.ts*',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});await p.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5181');await p.locator('#menu-settings').click();await p.selectOption('#display-resolution','800x600');await p.selectOption('#display-mode','native');await p.locator('#menu-back').click();await p.locator('#menu-skirmish').click();await p.selectOption('#faction-select',faction);await p.selectOption('#map-select','arena');await p.locator('#start-match').click();await p.waitForFunction(()=>window.__gameCheck?.scene.keys.BootScene.session.phase==='playing'&&!window.__gameCheck.scene.keys.BootScene.restartPending);
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{applyResourceCheat,resourceCheatCode}=await import('/src/gameplay/cheats.ts');s.update=()=>{};s.sys.sceneUpdate=()=>{};s.applyMatch(applyResourceCheat(s.currentMatch(),resourceCheatCode));s.cameras.main.setScroll(100,200);s.syncVisuals();});
 const click=async(q,button='left')=>{const pos=await p.evaluate(q=>{const c=window.__gameCheck.scene.keys.BootScene.cameras.main;return {x:c.x+(q.x-c.scrollX)*c.zoom,y:c.y+(q.y-c.scrollY)*c.zoom};},q),box=await p.locator('#game canvas').boundingBox(),sz=await p.locator('#game canvas').evaluate(c=>({w:c.width,h:c.height}));await p.mouse.click(box.x+pos.x*box.width/sz.w,box.y+pos.y*box.height/sz.h,{button});};
 const base=await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.base);await click(base);await p.locator('#upgrade-base').click();await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<200;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.combat.baseDevelopment.level),2);
 const worker=await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.kind==='worker').position);await click(worker);await p.locator('#build-stable').click();await click({x:512,y:384});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.stable?.construction.remainingSeconds),10);
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<600&&s.placement.stable.construction.remainingSeconds>0;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.stable.construction.remainingSeconds),0);
 await click({x:544,y:416});assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.selectedBuilding),'stable');assert(await p.locator('#train-cavalry').isVisible());const before=await p.evaluate(()=>{const g=window.__gameCheck.scene.keys.BootScene.gathering;return {wood:g.wood,gold:g.goldBalance};});await p.locator('#train-cavalry').click();const queued=await p.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {wood:s.gathering.wood,gold:s.gathering.goldBalance,job:s.placement.stable.production.queue[0]};});assert.equal(before.wood-queued.wood,45);assert.equal(before.gold-queued.gold,25);assert.equal(queued.job.durationSeconds,12);await p.screenshot({path:`${out}/${faction}-production.png`});
 await p.locator('#tech-tree-button').click();await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.syncVisuals());await p.getByRole('button',{name:'Army',exact:true}).click();await p.locator('[data-tech-node="unit-cavalry"]').click();assert.match(await p.locator('#technology-details').textContent(),/45 wood \+ 25 gold.*12s.*2 supply/);await p.screenshot({path:`${out}/${faction}-tech-tree.png`});await p.keyboard.press('Escape');
 await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');for(let i=0;i<120;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();});const rider=await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='cavalry'));assert(rider);await click(rider.position);assert.match(await p.locator('#selection-stats').textContent(),/Supply 2/);assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.selectedBuilding),null);await click({x:600,y:460},'right');const movement=await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');const u=s.gathering.units.find(u=>u.archetype==='cavalry'),before={...u.position};for(let i=0;i<10;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();return {before,after:s.gathering.units.find(u=>u.archetype==='cavalry').position};});assert.notDeepEqual(movement.before,movement.after);await p.screenshot({path:`${out}/${faction}-rider.png`});
 const opponent=await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{matchFog}=await import('/src/gameplay/matchFog.ts');const e=s.combat.enemies.find(e=>e.kind==='worker');e.position={x:616,y:460};e.navigation=undefined;e.work={...e.work,target:{...e.position},order:{kind:'idle'}};s.fog=matchFog(s.currentMatch());s.syncVisuals();return {id:e.id,hp:e.hp,position:e.position};});await click(opponent.position,'right');const fought=await p.evaluate(async id=>{const s=window.__gameCheck.scene.keys.BootScene,{updateMatch}=await import('/src/gameplay/match.ts');const ordered=s.gathering.units.find(u=>u.archetype==='cavalry').order;for(let i=0;i<5;i++)s.applyMatch(updateMatch(s.currentMatch(),.1));s.syncVisuals();return {ordered,hp:s.combat.enemies.find(e=>e.id===id)?.hp??0};},opponent.id);assert.equal(fought.ordered.kind,'attack');assert(fought.hp<opponent.hp);
 const saveProbe=await p.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{encodeSave,decodeSave}=await import('/src/gameplay/save.ts');try{return decodeSave(encodeSave(s.currentMatch(),{camera:{x:100,y:200},building:null}));}catch(e){return {error:e.message};}});assert(saveProbe.ok,JSON.stringify(saveProbe));
 await p.locator('#match-menu-button').click();await p.locator('#save-match').click();assert.match(await p.locator('#save-status').textContent(),/saved/i);await p.locator('#load-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='paused');assert(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.some(u=>u.archetype==='cavalry')));await p.locator('#restart-match').click();await p.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');assert.equal(await p.evaluate(()=>window.__gameCheck.scene.keys.BootScene.placement.stable),undefined);assert.deepEqual(errors,[]);results.push({faction,actualMouseBaseUpgradeBuildTrainMoveAttack:true,fought,queued,movement,saveLoadRestart:true,errors});console.log('PASS '+faction);await p.close();
}await writeFile(`${out}/browser.json`,JSON.stringify({fixture:'Real menu/clicks; resource-cheat funding; paused render with explicit .1s gameplay steps',results},null,2)+'\n');}finally{await browser.close();}
