import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core');
const browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE});
const out='artifacts/rts-165';await mkdir(out,{recursive:true});const reports=[];
try{for(const faction of ['crown','clans','elves','dwarves','goblins'])for(const width of [800,1280]){
 const height=width===800?600:720,page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.ts*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});
 await page.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5182/',{waitUntil:'domcontentloaded'});
 await page.locator('#menu-settings').click();await page.selectOption('#display-resolution',`${width}x${height}`);await page.selectOption('#display-mode','native');await page.locator('#menu-back').click();await page.locator('#menu-skirmish').click();await page.selectOption('#faction-select',faction);await page.selectOption('#scenario-select','skirmish');await page.selectOption('#map-select','arena');await page.locator('#start-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');
 await page.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{factions}=await import('/src/config/factions.ts'),f=factions[s.factions.player];s.__update=s.update;s.update=()=>{};s.sys.sceneUpdate=()=>{};s.skipGameplayFrame=false;s.gathering.units.forEach(u=>u.selected=false);s.gathering.wood=200;s.gathering.goldBalance=120;s.placement.barracks={x:512,y:384,width:64,height:64};s.placement.barracksHP=f.buildings.barracks.hp;s.placement.barracksOwner='player';s.placement.construction={remainingSeconds:0,builderId:null};s.map.obstacles.push(s.placement.barracks);s.selectedBuilding='barracks';s.cameras.main.setScroll(120,160);s.syncVisuals();});
 assert.equal(await page.locator('#train-specialist').isDisabled(),true);
 const recipe=await page.evaluate(async()=>{const s=window.__gameCheck.scene.keys.BootScene,{factions}=await import('/src/config/factions.ts'),f=factions[s.factions.player];s.placement.forge={id:'forge',owner:'player',hp:f.buildings.forge.hp,footprint:{x:640,y:384,width:64,height:64},construction:{remainingSeconds:0,builderId:null}};s.map.obstacles.push(s.placement.forge.footprint);s.research.attack=1;s.research.defense=1;s.syncVisuals();return {name:f.unitNames.specialist,...f.units.specialist};});
 assert.equal(await page.locator('#train-specialist').isDisabled(),false);await page.locator('#train-specialist').click();
 const initial=await page.evaluate(seconds=>{const s=window.__gameCheck.scene.keys.BootScene;s.__update(0,seconds*1000);const u=s.gathering.units.find(u=>u.archetype==='specialist');u.position={x:460,y:220};u.target={...u.position};u.selected=false;s.selectedBuilding=null;s.syncVisuals();return {mana:u.mana,wood:s.gathering.wood,gold:s.gathering.goldBalance};},recipe.durationSeconds);
 const box=await page.locator('#game canvas').boundingBox(),camera=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {x:s.cameras.main.x,y:s.cameras.main.y,sx:s.cameras.main.scrollX,sy:s.cameras.main.scrollY,w:s.game.canvas.width,h:s.game.canvas.height};});await page.mouse.click(box.x+(camera.x+460-camera.sx)*box.width/camera.w,box.y+(camera.y+220-camera.sy)*box.height/camera.h);assert.equal(await page.locator('#selection-name').innerText(),recipe.name);
 assert.equal(initial.mana,recipe.mana.initial);assert.equal(initial.wood,200-recipe.cost.wood);assert.equal(initial.gold,120-recipe.cost.gold);assert.match(await page.locator('#selection-health').innerText(),new RegExp(`Mana ${recipe.mana.initial} / ${recipe.mana.max}`));
 await page.screenshot({path:`${out}/${faction}-${width}-selected.png`});
 await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.__update(0,2000);});const mana=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='specialist').mana);assert.equal(mana,recipe.mana.initial+2*recipe.mana.regenerationPerSecond);
 await page.locator('#match-menu-button').click();await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.__update(0,3000));assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='specialist').mana),mana);const validation=await page.evaluate(async()=>{const {encodeSave}=await import('/src/gameplay/save.ts'),s=window.__gameCheck.scene.keys.BootScene;try{encodeSave(s.currentMatch(),{camera:{x:s.cameras.main.scrollX,y:s.cameras.main.scrollY},building:null});return 'ok';}catch(e){return e.message;}});assert.equal(validation,'ok');await page.locator('#save-match').click();assert.match(await page.locator('#save-status').innerText(),/saved/i);await page.locator('#load-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='paused');await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.update=()=>{};s.sys.sceneUpdate=()=>{};});assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='specialist').mana),mana);
 await page.evaluate(max=>window.__manaMax=max,recipe.mana.max);await page.locator('#resume-match').click();await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.gathering.units.find(u=>u.archetype==='specialist').mana=window.__manaMax-.1;s.__update(0,1000);});assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='specialist')?.mana),recipe.mana.max);
 assert.deepEqual(errors,[]);reports.push({faction,width,initial,mana,max:recipe.mana.max,errors});await page.close();
}await writeFile(`${out}/browser.json`,JSON.stringify(reports,null,2));console.log('PASS five factions at800/1280: locked/unlocked paid production, initial mana, HUD, regen, pause, Save/Load and cap');}finally{await browser.close();}
