import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.W2T_PLAYWRIGHT_MODULE??'playwright-core');
const browser=await chromium.launch({headless:true,executablePath:process.env.W2T_BROWSER_EXECUTABLE}),out='artifacts/rts-168',reports=[];
await mkdir(out,{recursive:true});
try {for(const faction of ['crown','clans','elves','dwarves','goblins'])for(const width of [800,1280]) {
 const height=width===800?600:720,page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.ts*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('new Phaser.Game({','window.__gameCheck=new Phaser.Game({')});});
 await page.goto(process.env.W2T_UI_URL??'http://127.0.0.1:5183/',{waitUntil:'domcontentloaded'});
 await page.locator('#menu-settings').click();await page.selectOption('#display-resolution',`${width}x${height}`);await page.selectOption('#display-mode','native');await page.locator('#menu-back').click();await page.locator('#menu-skirmish').click();await page.selectOption('#faction-select',faction);await page.selectOption('#enemy-faction-select',faction);await page.selectOption('#scenario-select','skirmish');await page.selectOption('#map-select','arena');await page.locator('#start-match').click();
 await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');
 const recipe=await page.evaluate(async faction=>{const {factions}=await import('/src/config/factions.ts'),{replaceObstacles}=await import('/src/gameplay/map.ts'),{matchFog}=await import('/src/gameplay/matchFog.ts'),s=window.__gameCheck.scene.keys.BootScene,f=factions[faction];s.__update=s.update;s.update=()=>{};s.sys.sceneUpdate=()=>{};s.skipGameplayFrame=false;
 s.gathering.units.forEach(u=>u.selected=false);s.gathering.wood=300;s.gathering.goldBalance=120;
 s.placement.barracks={x:352,y:224,width:64,height:64};s.placement.barracksHP=f.buildings.barracks.hp;s.placement.barracksOwner='player';s.placement.construction={remainingSeconds:0,builderId:null};s.placement.forge={id:'forge',owner:'player',footprint:{x:448,y:224,width:64,height:64},hp:f.buildings.forge.hp,construction:{remainingSeconds:0,builderId:null}};
 s.placement.farms=[{id:'farm-1',owner:'player',footprint:{x:352,y:320,width:64,height:64},hp:f.buildings.farm.hp,construction:{remainingSeconds:0,builderId:null}}];s.placement.nextFarmNumber=2;
 s.research={attack:1,defense:1,job:null};s.map=replaceObstacles(s.map,[...s.map.obstacles,s.placement.barracks,s.placement.forge.footprint,s.placement.farms[0].footprint]);s.selectedBuilding='barracks';s.cameras.main.setScroll(160,160);s.fog=matchFog(s.currentMatch());s.syncVisuals();return f.units.air;},faction);
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const point=async(x,y)=>{const box=await page.locator('#game canvas').boundingBox(),c=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;return {x:s.cameras.main.x,y:s.cameras.main.y,sx:s.cameras.main.scrollX,sy:s.cameras.main.scrollY,w:s.game.canvas.width,h:s.game.canvas.height};});return {x:box.x+(c.x+x-c.sx)*box.width/c.w,y:box.y+(c.y+y-c.sy)*box.height/c.h};};
 const click=async(x,y,button='left')=>{const p=await point(x,y);await page.mouse.click(p.x,p.y,{button});await page.waitForTimeout(50);};
 await click(384,256);assert.equal(await page.locator('#train-air').isEnabled(),true);assert.match(await page.locator('#train-air').getAttribute('title'),/TEMP ART/);
 const before=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.wood);await page.locator('#train-air').click();assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.wood),before-recipe.cost.wood);
 await page.evaluate(seconds=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.__update(0,seconds*1000);},recipe.durationSeconds);
 const air=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene,u=s.gathering.units.find(u=>u.archetype==='air');u.autoDisabled=true;for(const e of s.combat.enemies)if(!e.footprint){e.position={x:900,y:160};if(e.work)e.work.order={kind:'idle'};e.navigation=undefined;}s.syncVisuals();return u;});assert(air,'paid air must spawn');
 await click(air.position.x,air.position.y-24);assert.match(await page.locator('#selection-detail').innerText(),/TEMP ART/);await page.screenshot({path:`${out}/${faction}-selected-${width}.png`});
 await click(480,256,'right');await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.__update(0,50);});
 const flight=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene,u=s.gathering.units.find(u=>u.archetype==='air');return {position:u.position,order:u.order,hp:u.hp};});assert.equal(flight.order.kind,'move',JSON.stringify(flight));assert.notDeepEqual(flight.position,air.position);
 const valid=await page.evaluate(async()=>{const {encodeSave,decodeSave}=await import('/src/gameplay/save.ts'),s=window.__gameCheck.scene.keys.BootScene;const r=decodeSave(encodeSave(s.currentMatch(),{camera:{x:0,y:0},building:s.selectedBuilding}));return r.ok?'ok':r.error;});assert.equal(valid,'ok');await page.locator('#match-menu-button').click();await page.locator('#save-match').click();assert.match(await page.locator('#save-status').innerText(),/saved/i);await page.locator('#load-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='paused');await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.update=()=>{};s.sys.sceneUpdate=()=>{};});assert.deepEqual(await page.evaluate(()=>{const u=window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='air');return {position:u.position,order:u.order,hp:u.hp};}),flight);
 await page.locator('#resume-match').click();await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.__update(0,5000);});await page.screenshot({path:`${out}/${faction}-over-building-${width}.png`});
 await click(384,256);for(let i=0;i<3;i++)if(await page.locator('#train-archer').isEnabled())await page.locator('#train-archer').click();
 const panels=await page.evaluate(()=>['bottom-bar','context-actions','selection-info','production-queue'].map(id=>{const el=document.getElementById(id);return el?{id,width:el.clientWidth,scrollWidth:el.scrollWidth,height:el.clientHeight,scrollHeight:el.scrollHeight}:null;}).filter(Boolean));for(const p of panels){assert(p.scrollWidth<=p.width+1,JSON.stringify(p));assert(p.scrollHeight<=p.height+1,JSON.stringify(p));}await page.screenshot({path:`${out}/${faction}-production-${width}.png`});
 const foe=await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene,u=s.gathering.units.find(u=>u.archetype==='air'),id='enemy-air-fixture',position={x:u.position.x+100,y:u.position.y};s.combat.enemies.push({id,kind:'unit',owner:'enemy',role:'air',hp:u.hp,position,order:{kind:'defend',targetId:u.id}});s.syncVisuals();return {id,position,hp:u.hp};});
 const ownAir=await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.find(u=>u.archetype==='air'));await click(ownAir.position.x,ownAir.position.y-24);await click(foe.position.x,foe.position.y-24,'right');await page.evaluate(()=>{const s=window.__gameCheck.scene.keys.BootScene;s.skipGameplayFrame=false;s.__update(0,2000);});
 const hit=await page.evaluate(id=>window.__gameCheck.scene.keys.BootScene.combat.enemies.find(e=>e.id===id)?.hp,foe.id);assert.equal(hit<foe.hp,faction!=='goblins',`${faction}: individual air target mask`);await page.screenshot({path:`${out}/${faction}-air-combat-${width}.png`});
 if(width===1280){await page.evaluate(()=>{document.getElementById('display-mode').value='fit';document.getElementById('display-mode').dispatchEvent(new Event('change'));});await page.screenshot({path:`${out}/${faction}-fit-${width}.png`});}
 await page.locator('#match-menu-button').click();await page.locator('#restart-match').click();await page.waitForFunction(()=>!window.__gameCheck.scene.keys.BootScene.restartPending&&window.__gameCheck.scene.keys.BootScene.session.phase==='playing');assert.equal(await page.evaluate(()=>window.__gameCheck.scene.keys.BootScene.gathering.units.some(u=>u.archetype==='air')),false);assert.deepEqual(errors,[]);reports.push({faction,width,recipe,flight,panels,errors});await page.close();
 }await writeFile(`${out}/browser.json`,JSON.stringify(reports,null,2));console.log('PASS five air recipes ×800/1280: paid UI production, elevated selection, flight over building, Save/Load, full queue, bounds/unit tests, restart; temporary art only');}finally{await browser.close();}
