/** English player-facing copy. IDs, saved state and gameplay rules are language-independent. */
export const text={
  "lowerEnemyPressureAndLaterAttacks": "Lower enemy pressure and later attacks.",
  "standardEnemyPressureAndAttackTiming": "Standard enemy pressure and attack timing.",
  "higherEnemyPressureWithEarlierLargerAttacks": "Higher enemy pressure with earlier, larger attacks.",
  "anOpenBattlefieldWithRockAndWaterA": "An open battlefield with rock and water. A balanced setting for land combat.",
  "forestPassHasNarrowPassagesMoreWoodAnd": "Forest Pass has narrow passages, more wood and less gold. Find alternative routes around obstacles.",
  "riverBendDividesTheBattlefieldWithWaterPlan": "River Bend divides the battlefield with water. Plan land routes and protect the crossings.",
  "twoIslandsWithoutALandConnectionAHarbor": "Two islands without a land connection. A harbor and transport are needed for a landing.",
  "theMapIsFixedForThisScenario": " The map is fixed for this scenario.",
  "netSpentIsPaidCostsMinusRefundsIncluding": "Net spent is paid costs minus refunds, including unfinished jobs. Unit statistics exclude buildings; units created exclude starting units.",
  "factionAbilitySelectedCombatUnitsThatAreReady": "Faction ability – selected combat units that are ready",
  "stopSelectedUnits": "Stop – selected units",
  "attackMoveSelectACombatUnitThenClick": "Attack-move – select a combat unit, then click a destination",
  "buildBarracksSelectAWorker": "Build barracks – select a worker",
  "buildFarmSelectAWorker": "Build farm – select a worker",
  "buildForgeSelectAWorker": "Build forge – select a worker",
  "trainWorkerSelectTheBase": "Train worker – select the base",
  "trainSoldierSelectBarracks": "Train soldier – select barracks",
  "trainArcherSelectBarracks": "Train archer – select barracks",
  "trainCatapultSelectBarracks": "Train catapult – select barracks",
  "attackResearchCompletedForge": "Attack research – completed forge",
  "defenseResearchCompletedForge": "Defense research – completed forge",
  "shiftClickToggleShiftDragAdd": "Shift-click: toggle · Shift-drag: add",
  "ctrlCmd19AssignGroup19": "Ctrl/Cmd+1–9: assign group · 1–9: recall",
  "pPauseResumeEscapeCancelPreviewOtherwisePause": "P: pause/resume · Escape: cancel preview, otherwise pause/resume",
  "aDisabledButtonMeansTheActionIsUnavailable": "A disabled button means the action is unavailable; check selection, resources, population, queue and status.",
  "clickTheWorldForKeyboardFocusUiFields": "Click the world for keyboard focus. UI fields, repeated key presses, pause and game over block gameplay hotkeys.",
  "audioUnavailableGameplayRemainsAvailable": "Audio unavailable – gameplay remains available",
  "theDestinationIsOutsideTheWorld": "The destination is outside the world",
  "theDestinationIsBlocked": "The destination is blocked",
  "theStartingPositionIsBlocked": "The starting position is blocked",
  "noRouteToTheDestination": "No route to the destination",
  "noFreeReachableDestination": "No free reachable destination",
  "theMatchHasEnded": "The match has ended",
  "buildBarracksFirst": "Build barracks first",
  "theBuildingIsUnfinished": "The building is unfinished",
  "completeSpawnExitBlocked": "Complete – spawn exit blocked",
  "readyToTrain": "Ready to train",
  "noValidSpawnPosition": "No valid spawn position",
  "noUnitSelected": "No unit selected",
  "savedLocallyInSlot1": "Saved locally in slot 1",
  "couldNotSaveLocallyCheckBrowserStorage": "Could not save locally. Check browser storage.",
  "noLocalSaveExists": "No local save exists",
  "thisSaveUsesAnUnsupportedFormatOrGame": "This save uses an unsupported format or game version. The active match is unchanged.",
  "couldNotReadTheSaveTheActiveMatch": "Could not read the save. The active match is unchanged.",
  "loadedPausedNoGameplayTimePassesUntilResume": "Loaded – paused. No gameplay time passes until Resume.",
  "loadedCompletedMatch": "Loaded – completed match",
  "loadedMatchResumed": "Loaded – match resumed",
  "chooseAScenarioAndDifficultyThenStartMatch": "Choose a scenario and difficulty, then Start Match",
  "pausedSimulationIsFrozen": "Paused – simulation is frozen",
  "theMatchHasEndedRestartOrChooseA": "The match has ended – restart or choose a new match",
  "buildAForgeForUpgrades": "Build a forge for upgrades",
  "theSiteMustBeVisible": "The site must be visible",
  "validSite": "Valid site",
  "barracksComplete": "Barracks complete",
  "selectAWorkerToBuild": "Select a worker to build",
  "selectAWorkerACompletedFarmAdds5": "Select a worker – a completed farm adds 5 population",
  "attackMoveClickADestinationEscapeCancels": "Attack-move: click a destination (Escape cancels)",
  "defeatYourBaseWasDestroyed": "Defeat – your base was destroyed",
  "victoryTheEnemyBaseWasDestroyed": "Victory – the enemy base was destroyed",
  "victoryTheOutpostSurvivedFor90Seconds": "Victory – the outpost survived for 90 seconds",
  "victoryAllWavesDefeated": "Victory – all waves defeated",
  "theProductionQueueIsEmpty": "The production queue is empty",
  "selectABuildingToTrainUnitsOrCancel": "Select a building to train units or cancel production",
  "groupsCtrl19Assign19Recall": "Groups: Ctrl+1–9 assign, 1–9 recall",
  "clickAVisibleFreeLandingWithin64Px": "Click a visible free landing within 64 px (Escape/right-click cancels)",
  "selectATransportToBoardOrUnload": "Select a transport to board or unload",
  "selectAWorkerPlaceOnAVisibleCoast": "Select a worker – place on a visible coast",
  "waitingForAFreeWaterExit": "waiting for a free water exit",
  "outsideTheWorld": "Outside the world",
  "overlapsTheBaseOrAResourceNode": "Overlaps the base or a resource node",
  "notEnoughWoodOrGold": "Not enough wood or gold",
  "overlapsTerrainOrABuilding": "Overlaps terrain or a building",
  "overlapsAUnit": "Overlaps a unit",
  "blocksAWorkerRouteToTheBaseOr": "Blocks a worker route to the base or resources",
  "blocksTheBuilderRoute": "Blocks the builder route",
  "blocksAProductionExit": "Blocks a production exit",
  "blocksTheEnemyWaveRouteToTheBase": "Blocks the enemy wave route to the base",
  "theBuildingSiteCannotBeReached": "The building site cannot be reached",
  "theRallyDestinationIsBlockedOrUnreachable": "The rally destination is blocked or unreachable",
  "aHarborNeedsAFreeCoastWithLand": "A harbor needs a free coast with land and water",
  "noFreeWaterExit": "No free water exit",
  "selectCombatUnitsToUseTheAbility": "Select combat units to use the ability",
  "gatherWoodAndGoldBuildBarracksAndDefeat": "Gather wood and gold, build barracks and defeat all three waves. Protect your base.",
  "buildAnArmyAndExploreTheNortheastDestroy": "Build an army and explore the northeast. Destroy the enemy base and protect your own.",
  "defeatThreeFiniteWavesStartWith20Wood": "Defeat three finite waves. Start with 20 wood and 10 gold. Deliver resources and build a mixed army.",
  "destroyTheEnemyBaseInTheNortheastStart": "Destroy the enemy base in the northeast. Start with 20 wood and 10 gold. Your base must survive.",
  "gatherOnTheWesternIslandStartWith20": "Gather on the western island. Start with 20 wood and 10 gold. Build a harbor and transport, land your army and destroy the enemy base. Protect your base from the enemy landing.",
  "keepYourBaseAliveFor90GameplaySeconds": "Keep your base alive for 90 gameplay seconds. Start with 40 wood and 10 gold. Enemies may remain when time runs out.",
  "gatherOnTheWesternIslandBuildAHarbor": "Gather on the western island. Build a harbor and transport, board an army at the coast and land on the eastern island. Destroy the enemy base.",
  "mission1ForestWatch": "Mission 1 – Forest Watch",
  "mission2TheSiege": "Mission 2 – The Siege",
  "mission3TheOutpost": "Mission 3 – The Outpost",
  "mission4TheCrossing": "Mission 4 – The Crossing",
  "arena": "Arena",
  "forestPass": "Forest Pass",
  "riverBend": "River Bend",
  "islands": "Islands",
  "crownAlliance": "Crown Alliance",
  "ironClan": "Iron Clan",
  "clanWorker": "Clan Worker",
  "worker": "Worker",
  "axeWarrior": "Axe Warrior",
  "guard": "Guard",
  "archer": "Archer",
  "hunter": "Hunter",
  "stoneThrower": "Stone Thrower",
  "catapult": "Catapult",
  "keep": "Keep",
  "barracks": "Barracks",
  "farm": "Farm",
  "forge": "Forge",
  "stronghold": "Stronghold",
  "warHut": "War Hut",
  "cattlePen": "Cattle Pen",
  "smithy": "Smithy",
  "defensiveStance": "Defensive Stance",
  "value25IncomingDamage": "−25% incoming damage",
  "fury": "Fury",
  "value25OutgoingDamage": "+25% outgoing damage",
  "enableAudio": "Enable audio",
  "keysAndCommands": "Keys and commands",
  "trainWorker20Wood": "Train worker – 20 wood",
  "trainSoldier20Wood5Gold": "Train soldier – 20 wood + 5 gold",
  "trainArcher20Wood10Gold": "Train archer – 20 wood + 10 gold",
  "trainCatapult40Wood20Gold": "Train catapult – 40 wood + 20 gold",
  "buildHarbor40Wood10Gold": "Build harbor – 40 wood + 10 gold",
  "buildTransport40Wood10Gold": "Build transport – 40 wood + 10 gold",
  "buildWarship40Wood15Gold": "Build warship – 40 wood + 15 gold",
  "buildBarracks40Wood": "Build barracks – 40 wood",
  "buildFarm20Wood": "Build farm – 20 wood",
  "buildForge": "Build forge",
  "protectYourBase": "Protect your base",
  "saveLocally": "Save locally",
  "loadSave": "Load save",
  "startMatch": "Start Match",
  "pauseP": "Pause [P]",
  "resumeP": "Resume [P]",
  "newMatchMenu": "New match / menu",
  "restart": "Restart",
  "difficulty": "Difficulty",
  "faction": "Faction",
  "map": "Map",
  "unload": "Unload",
  "ability": "Ability",
  "gameWorld": "Game world",
  "couldNotReadTheSave": "Could not read the save",
  "storageUnavailable": "Storage unavailable",
  "couldNotReadLocalStorage": "Could not read local storage",
  "gathered": "Gathered",
  "delivered": "Delivered",
  "netSpent": "Net spent",
  "unitsCreated": "Units created",
  "unitsLost": "Units lost",
  "unitsDefeated": "Units defeated",
  "statistics": "Statistics",
  "enemy": " (enemy)",
  "sRemaining": " s remaining",
  "allWavesHaveArrived": "all waves have arrived",
  "rightClickSetsRally2": "– right-click sets rally",
  "shipQueue": "– ship queue",
  "active": "Active",
  "queued": "Queued",
  "harbor": "Harbor",
  "warship": "Warship",
  "resourceOutpost": "Resource outpost · ",
  "muted": "muted",
  "complete5": "complete (+5)",
  "construction3": "construction ",
  "production": "production ",
  "developerFixture": "Developer fixture",
  "audio": "Audio",
  "effects": "Effects",
  "music": "Music",
  "campaign": "Campaign",
  "skirmish": "Skirmish",
  "loadGame": "Load Game",
  "settings": "Settings",
  "chooseYourBattle": "Choose your battle",
  "anIndependentFantasyRts": "An independent fantasy RTS",
  "localSinglePlayerYourSavesStayInThis": "Local single-player · Your saves stay in this browser",
  "back": "← Back",
  "gameSpeed": "Game speed",
  "value1Standard": "1× · Standard",
  "standardGameplaySpeedSlowerSpeedWillBeAvailable": "Standard gameplay speed. Slower speed will be available in a later update.",
  "campaignChooseAMission": "Campaign · Choose a mission",
  "skirmishChooseYourBattle": "Skirmish · Choose your battle",
  "harborUsesCoastRules": "Harbors use coastal placement rules",
  "forgeExists": "A forge already exists",
  "barracksExists": "Barracks already exist",
  "farmLimit": "Maximum number of farms reached",
  "buildingMissing": "The building is missing",
  "harborExists": "A harbor already exists",
  "scenario": "Scenario",
  "master": "Master",
  "cameraControls": "Arrow keys: pan camera. Middle-drag: pan. Hover the world edge to scroll. Click the world for keyboard focus."
} as const;

export function applyEnglishText():void{for(const element of document.querySelectorAll<HTMLElement>('[data-ui-text]')){const key=element.dataset.uiText as keyof typeof text;if(Object.hasOwn(text,key))element.textContent=text[key];}}
